---
title: "Administrivia  🧐"
subtitle: "IT as a Service Enabler (ITSE)"

bibliography: ../assets/literature.bib

format: 
  html:
    output-file: index.html
  revealjs:
    date: "Winter Term 2022"
    output-file: slides.html 
    include-after-body: ../assets/footer.html  
---

# Top{visibility="hidden" .slide-link-hidden .unlisted .unnumbered}

{{< include ../assets/_top.qmd >}}

# Formalities {.vertical-center background-color=blue}

## Seminar paper

Please use this [template](../assets/template)

:::{.incremental}
- The paper should be at least 10 pages long and must not exceed 15 pages (per student, excluding references)
- The paper must be uploaded as PDF in Moodle (deadline announced on moodle)
:::

## Meetings

You must attend at least the following meetings

:::{.incremental}
- Kick-off
- Review #1 (literature)
- Review #2 (findings)
- Review #3 (paper draft)
:::

. . .

You are responsible for arranging the meetings (except the kick-off) via [calendly](https://calendly.com/awe-hnu/office).


# Paper structure

Please follow this generic structure (level 1), sub-sections can be defined individually.


:::{.notes}
You do neither need to add a table of contents nor a list of figures.
:::

**Introduction**

:::{.notes}
-	Motivation (relevance, research gap)
-	Research question
:::

. . .

**Theoretical Background**

:::{.notes}
-	State of research (what is known, what is not yet known)
-	Introduction of the main theoretical concepts
:::

. . .

**Method**

:::{.notes}
-	Presentation of the approach to data collection and analysis (how did you proceed, e.g., how the structured literature review was conducted or how the cases have been selected, data has been gained and analyzed) 
Findings
-	Description of the results (what have you found out?)
(for literature reviews: concept-centric presentation, not author-based) 
:::

. . .

**Discussion**

:::{.notes}
-	The answers to the research questions are presented and discussed
-	Evaluation of the findings considering existing literature (usually the literature discussed in the background section) 
-	Elaboration of theoretical and practical contributions of your work (e.g., what can be learned from your work on a theoretical and practical level)
-	Limitations and further research
:::

# Evaluation

The final paper is graded based on following criteria

Originality (passsing criterion)
: The paper complies with the rules of good scientific practice, plagiarism will not be accepted.

. . .

Logic & consistency (80%)
: The red thread of the paper and the scientific approach is clearly recognizable and logically comprehensible.

:::{.notes}
-	The topic is clearly outlined and motivated in the introduction
-	The research question is explicitly stated 
- All core terms are introduced and clearly defined 
-	The background/state of research is sufficiently substantiated
-	Data collection and analysis methods are clearly outlined and correctly applied
-	The results are comprehensible and offer novel answers to the research question 
-	The findings are critically discussed (contributions, implications for practice, own thoughts; literature is used)
:::

. . .

Composition and formalities (20%) 
: The paper follows scientific standards concering literature use, structure and language.

:::{.notes}
-	A sufficient amount of predominantly scientific literature is used (peer-reviewed articles)
-	Literature is correctly and consistently cited 
-	Works is well structured (length and balance of chapters) and formal requirements are fulfilled (grammar, spelling, formatting)
-	The argumentation is well comprehensible (linguistic stylistics)
:::