---
title: "Administrivia 🧐"  
subtitle: "`SIM_1` Technology & Application Management (TAM)"

format: 
  html:
    output-file: index.html
  revealjs:
    output-file: slides.html 
    include-after-body: ../assets/footer.html
---

# Top{visibility="hidden" .slide-link-hidden .unlisted .unnumbered}

{{< include ../assets/_top.qmd >}}

__Printing/export:__ If you want to print or export the slides, open the slides, press `e` on your keyboard and then print (to pdf).

# Motivation {.vertical-center background-color=blue background-image="images/bg.jpeg"}

> Technology has changed significantly over the past 50 years. However, for too many CIOs, the way it is managed has not! *Brian Adams, CIO Worley Parsons*

# Contents

IT management today is challenged by fast technological change, new digital opportunities, growing cost pressure, and increasing need to comply with business and regulatory requirements. 

. . .

State-of-the-art IT management needs to ensure that organizations are capable of managing technologies and applications more agile, flexible and efficient than ever before. 

. . .

Being able to achieve this requires not only a good understanding of the opportunities the digital age and new technologies offer, but also a good understanding of the core business of the company and sound IT cost management capabilities.

---

This course offers you the possibility to gain a solid know-how regarding theories, methods and tools for 

:::{.incremental}
- __selecting the right technologies and applications__ (e.g., business-IT alignment, technology foresight and evaluation, program management)
- __creating and managing efficient sociotechnical solutions__ (e.g., enterprise architecture management)
- __delivering technologies and applications efficiently__ (e.g., scaled agility, demand and service management, cybersecurity risk management)
- __ensuring IT-busienss value realization__ (e.g., cost accounting, data governance management)
:::

# Learning outcomes

Upon successful completion of this course, you will have advanced knowledge and skills in following areas

::: {.incremental}
- capacity to explain why technology and application management (TAM) is key for organizations to survive in the digital age,
- understanding of the __key challenges of TAM__
- expertise regarding the __main frameworks for managing IT in organizations__
- capacity to design __end-to-end TAM approaches__ by selecting and adapting available approaches, methods and tools
- ability to make responsible decisions with incomplete or limited information
- capacity for __agile teamwork__ aiming to develop independent solutions
:::

# Approach

This course will be taught using an __agile, self-directed learning approach__. It combines presence teaching (_in-class_), teamwork (_pre- and post-class_), and self-learning components (_pre- and post-class_).

. . .

The focus of the presence-teaching sessions is on giving you input to selected topics, answering your questions and giving you feedback on your learning progress. The learning progress is reflected in the deliverables of the [assignment](../assignment/) and the learning you take from working on the assignment, both individually and as a team.

. . .

It is really important that you prepare yourself for every session.  
For details what needs to be prepared, please see @tbl-schedule.

## Effort

You will gain 5 ECTS for this course. This equals approx. __125 hours workload__, of which you need most to pass the course.

::: {.incremental}
-	Joint sessions including follow-up: __approx. 40 hours__
-	Assignment (teamwork and individual contributions): __approx. 80 hours__
:::

. . .

You need to work on the assignment between the sessions and prepare for the sessions (individually and as a team).

. . .

Please prepare your schedule accordingly.

## Schedule {.scrollable .smaller}

::: {.column-page-right}

|Date        |Session-Type                  |Input                         |Deliverable                   |
|:-----------|:-----------------------------|:-----------------------------|:-----------------------------|
|`10/10/2022`|Kick-off                      |Relevance                     |-
|`17/10/2022`|Sprint planning               |Overview (frameworks)         |Team set-up
|            |__Sprint #1__ (framework)
|`24/10/2022`|Execution (stand-up)          |Demand/programm mgtm          |-
|`31/10/2022`|Execution (stand-up)          |Cost accounting               |-
|`07/11/2022`|Sprint review & planning      |-                             |PI presentation
|            |__Sprint #2__ (tools)
|`14/11/2022`|Execution (stand-up)          |EAM                           |-
|`21/11/2022`|Execution (stand-up)          |Evaluation/scouting           |-
|`28/11/2022`|Sprint review & planning      |-                             |PI presentation
|            |__Sprint #3__ (refinement)
|`05/12/2022`|Execution (stand-up)          |SAFe                          |-
|`12/12/2022`|Execution (stand-up)          |Cyber security risk mgmt      |-
|`19/12/2022`|Sprint review & planning      |-                             |PI presentation
|            |__Wrap-up__
|`09/01/2023`|Retrospective                 |-                             |Lessons learned
|`16/01/2022`|Final presentations           |-                             |Final group presentation

: Schedule winter term 2022 (may be subjected to changes) {#tbl-schedule}

:::

## Sessions' structure

::: {#tbl-panel layout-ncol=2}

| Duration | Topic                                            |
|---------:|--------------------------------------------------|
| 10 min   | Warm-up (all)
| 40 min   | Input (all)
| 30 min   | PO Q&A (all)
| 5 min    | Stand-up (group-wise)
| 50 min   | Project work (group-wise)

:Execution (stand-up)


| Duration | Topic                                            |
|---------:|--------------------------------------------------|
| 10 min   | Warm-up (all)
| 95 min   | PI presentation (all, 7 + 3)
| 30 min   | Sprint planning (group-wise)

:Sprint review & planning

Live sessions' agenda (timings are approximate)

:::


# Grading

The grade is based on the evaluation of the __[assignment](../assignment/)__ (seminar paper).

:::{.incremental}
- The seminar paper is created in a team-based effort
- The paper must be handed in at the end of the semester
- Individual contributions need to be marked
- Interim and final presentations are mandatory for getting feedback on the progress and sharing your knowledge
- Presentations will not be graded individually
:::

# Q&A {.html-hidden .unlisted .vertical-center background-color=blue background-image="images/bg.jpeg"}