---
title: "Digital Innovation"  
subtitle: "💎 Business Value Creation with IT (BVC)"

bibliography: ../assets/literature.bib

format: 
  html:
    output-file: index.html
  letterbox-revealjs:
    output-file: slides.html
    include-before-body: ../assets/footer.html
---


# Top {visibility="hidden" .slide-link-hidden .unlisted .unnumbered}

{{< include ../assets/_top.qmd >}}

# Definitions {.vertical-center background-color="#0333ff"}

## Discussion {.html-hidden .unlisted .discussion-slide background-color=black}

:::{.large}
What constitutes **digital innovation**?
:::

## Digital Innovation

![Three-layer conceptualization of digital innovation [@hund2021digital, p.5]](images/DIconceptualization.svg){#fig-DIconceptualization}

:::{.notes}
@hund2021digital offers following definitions:

- **Digital objects** are enduring, structured collections of elements that include one or more bitstrings, which follow  a set of syntactical rules.
- **Digital technology** is a digital object that has been assigned a socially agreed-upon meaning. A digital object becomes a digital technology when it is assigned a meaning, namely a purpose for applying it, whereby the purpose is determined by social actors such as users.
- **Digital innovation** refers to the creation or adoption, and exploitation of an inherently unbounded, value-adding novelty (e.g., product, service, process, or business model) through the incorporation of digital technology
:::

## Digitization, digitalization and value creation

![Central concepts and their interrelations [@hund2021digital, p.5]](images/DIinterrelations.svg){#fig-DIinterrelations}

:::{.notes}
@yoo2010research identify three characteristics of digital innovation as key: homogenization of data, reprogrammability, and self-referentiality.

- **Homogenization of data** by means of digitization makes any form of digital content accessible to any kind of digital device, thereby, separating content and medium.
- **Reprogrammability** allows a digital device to perform an almost unlimited number of functions as long as users have to agree upon a shared meaning of the data.
- **Self-reference** is expressed by the use of digital technology to create positive network externalities "that further accelerate the creation and availability of digital devices, networks, services, and contents" which "in turn, fosters
further digital innovation through a virtuous cycle of lowered entry barriers, decreased learning costs, and accelerated diffusion rates" [@yoo2010research, p. 726].

Objects, digital objects, digital technology and digital innovation are related by following mechanisms:

- **Digitization** is "the process of converting analog signals into a digital form, and ultimately into binary digits (bits)" [@tilson2010research, p. 749].
- **Digitalization** refers to "[…] a sociotechnical process of applying digitizing techniques to broader social and institutional contexts that render digital technologies infrastructural" [@tilson2010research, p. 749].
- **Novel value creation** refers to a process that adds value to the sociotechnical environment (e.g., individual behavior, market offerings, business processes) in a novel way [@hund2021digital].
- **Ontological reversal** is where the digital version is created first, and the physical version second (if needed)” [@baskerville2020digital, p. 509].

:::

## Discussion {.html-hidden .unlisted .discussion-slide background-color=black}

:::{.large}
How do **digital infrastructures**, **digital platforms**, **digital ecosystems** differ?
:::

## Infrastructure, platform, and ecosystem

@hund2021digital offers following definitions:

**Digital infrastructures** are the technical foundation upon which digital platforms (i.e., "the basic information technologies and organizational structures, along with the related services and facilities necessary for an enterprise or industry to function" [@tilson2010research, p. 748]).

. . .

**Digital platforms** allow various actors to develop modules such as add-on software as they are the "extensible codebase of a software-based system that provides core functionality shared by the modules that interoperate with it and the interfaces through which they interoperate" [@tiwana2010research, p. 676].

. . .

**Digital ecosystems** refer to the “collection of the platform and the modules specific to it" [@tiwana2010research, p. 676].

## Discussion {.html-hidden .unlisted .discussion-slide background-color=black}

:::{.large}
What is the **paradox of openness**?
:::

## Discussion {.html-hidden .unlisted .discussion-slide background-color=black}

:::{.large}
What other paradoxes do you see?
:::

# Paradoxes

@hund2021digital highlights three paradoxes related to digital technology:

:::{.incremental}
- The **paradox of openness** relates to the tension between value creation and value appropriation. Organizations may open their platforms to engage with a broad set of external actors and enable their innovation activities (i.e., value creation), but likewise have to protect their own firm's knowledge from being copied by competitors (i.e., value appropriation).
- The **paradox of change** captures the persistent contradiction between stability (to allow enrolling new actors and developments) versus flexibility (to allow unbounded growth) .
- The **paradox of control** captures the contradiction between enabling individual autonomy through decentralized control to foster generativity, while maintaining centralized control over the platform or infrastructure.
:::

## Discussion {.html-hidden .unlisted .discussion-slide background-color=black}

:::{.large}
How do these relate to the **generative relationship** of heavyweight and lightweight IT?
:::

# Q&A {.html-hidden .unlisted .vertical-center background-color="#0333ff"}

# Literature

:::{.refs}
:::