---
title: "Assignment 📑"  
subtitle: "🧑‍🔬 DI in Industry (DIiI)"

bibliography: ../assets/literature.bib

format: 
  html:
    output-file: index.html
  letterbox-revealjs:
    output-file: slides.html
    date: "Summer Term 2023"
    include-before-body: ../assets/footer.html
---

# Top{visibility="hidden" .slide-link-hidden .unlisted .unnumbered}

{{< include ../assets/_top.qmd >}}

# Task

During the semester you will be required to

::: {.incremental}
- gain insights into **different application domains** of digital innovation;
- research an organization in a specific industry, its challenges and how it addressed these by means of developing and introducing a digital innovation;
- **present** defined interim results at defined dates (see [timetable](../admin/#schedule));
- summarize your findings in a __seminar paper__ (case research study);
- receive and process feedback after each presentation; and
- listen to the presentations of your fellow students and give constructive feedback.
:::

## Paper

The seminar paper is composed of following elements

::: {.notes}

- __Case summary__: A brief description of the case, the digital innovation and its impact on the organization and industry (i.e., abstract).

- __Introduction__: the beginning of the case that grabs the reader and generates interest in reading further. It should stimulate interest or curiosity in the reader for what is to come by suggesting the main challenge that is addressed by the digital innovation.

- __Industry__: here you characterize the industry and outline any information that is required or helpful for understanding the context of the innovation and the innovation process, e.g., relevant services or products, relevant frameworks like regulations, the primary factor that produces profit and key challenges addressed by the innovation described in this case study.

- __Company__: provides a decent overview of the company (organization, respectively) including the most salient features about the business and challenges faced that are related to the innovation.

- __Problem__: you outline and reflect the challenges which the digital innovation addresses (should address) and synthesize them into a concise problem statement.

- __Approach__: covers how the organization has developed and implemented the digital innovation and, if data is available, what challenges needed to be tackled.

- __Solution__: provides a rich description of the digital innovation, how it approaches the initially outlined problem statement and which effects it has generated on the organization (e.g., revenues) and the industry.

- __Discussion__: you comment, provide analysis and identify theories, or connect concepts or learning that help explain the mechanisms and effects of the innovation. 

- __Lessons learned__: you should make at least one firm recommendation for practitioners dealing with innovation management in the industry and explain why you have made this recommendation.

- __Appendix__: covers at least comprehensible information on how you did collect the research or this case study. You may also add any information that is helpful to gain a broader understanding of the case but is not necessary to follow your line of though in the main body of the text.

:::

:::: {.columns .html-hidden}
::: {.column}
::: {.incremental}
- Summary/abstract
- Introduction *(hook)*
- Industry *(characteristics, challenges)*
- Company *(overview, specifics)*
- Problem
:::
:::
::: {.column}
::: {.incremental}
- Approach *(innovation process)*
- Solution
- Discussion *(explanation)*
- Lessons Learned *(recommendations)*
- Appendix *(methods)*
:::
:::
::::

## Industries

The case should focus on a digital innovation in one of the following industries

:::{.incremental}
- Healthcare
- Manufacturing
- Construction
- Logistics/transportation
- Retail
- Professional services
- Entertainment
:::

## Presentations

You will present your interim results repeatedly throughout the semester

::: {.incremental}
- Ideas *(brief intro to two to three digital innovations)*  
  __GATE__ — assignment of the topics
- Industry & company *(characteristics & challenges)*
- Problem, approach and solution *(development & implementation)*
- Discussion *(theoretically grounded explanations and leassons learned)*
:::

. . .

:::{.small}
For dates please see the [schedule](../admin/#schedule)
:::

# Evaluation criteria

An __case study__ that matches expectations has the following characteristics 

::: {.incremental}

- The intro makes the reader want to read further
- All relevant aspects of the industry are highlighted
- The reader is able to picture the company and understand its actions
- The key situation of the case is fully elaborated and complete
- The DI, the process and its relations to the industry are well outlined
- Theory-based explanations of the mechanisms of the innovation are given
- The recommendations given as well as their rationale make sense
- There are very few errors, the writing is clear, and easy to read and engaging
- The methodology is elaborated and the sources are evident
:::

. . .

:::{.smaller}
An [example](assets/example.pdf) for inspiration (not for copying)
:::


## Formal requirements

#### Seminar paper

::: {.incremental}
- Use the template offered [here](assets/DI-in-Industry_Case-Study_Template.docx) 
- The paper should be at least 12 pages long and must not exceed 16 pages
- The paper must be uploaded as PDF (Moodle)
::::

#### Presentations

::: {.incremental}
- Summary of the main points 
- At least one question you want to have feedback to 
- Max. 7 minutes
- No formal requirements on the slides
- Slides must be handed in as PDF (Moodle)
:::

# {.html-hidden .unlisted background-color=black background-iframe="https://www.mentimeter.com/app/presentation/aly6sweyozwy1ke9ag9x7topk535qdno/zsy6drk9a3kq"}

# Literature
::: {#refs}

:::