---
title: "hello 👋"  

format: 
  html:
    toc: false
    alignment: left
    css: lib/theme/front.css
    output-file: index.html
    page-layout: full
    
---

# Welcome to my Academic Resource Hub

This site hosts lecture notes and materials for my bachelor's and master's courses at HNU. 

Feel free to explore and use these resources to support your studies.

#### Bachelor

<!-- - [`IMUK_1` — Grundzüge Informationsmanagement](lectures/GIM/23ST/admin/) -->
- [Digitalisierung und Informationssysteme (DEM)](lectures/DE1/25WT/admin/) `DE1` 
<!-- - [`IMA_5` — IT as a Service Enabler](lectures/ITSE/24ST/admin/) -->
- [Future Technologies and Media (DEM)](lectures/FTM/26ST/admin/) `FTM`
<!-- - [Emergent Technologies and Media (ETM)](lectures/ETM/25WT/admin/) `ETM` -->


#### Master

<!-- - [`SIM_1` — Technology & Application Management](lectures/TAM/22WT/admin/) -->
- [Academic Writing (AIDA, DIM, SIM)](lectures/AW/26WT/admin/) `AW`
- [Business Value Creation with IT (AIDA, SIM)](lectures/BVC/26ST/admin/) `BVC` 
- [Digital Innovation in Industry (DIM)](lectures/DIiI/26ST/admin/) `DIiI`
- [Digital Leadership (SIM)](lectures/DL/26ST/admin/) `DL ` 
- [Information Systems Research (DIM, AIDA)](lectures/ISR/26WT/admin/) `ISR`
- [Interpersonal Skills (AIDA, DIM, SIM)](lectures/IPS/25WT/admin/) `IPS`
- [Introduction to AI (DIM)](lectures/I2AI/26ST/admin/) `I2AI`  
- [Strategy and Performance Management (AIDA, DIM, SIM)](lectures/SPM/25WT/admin/) `SPM` 

