---
title: "Administrivia 🧐"  
subtitle: "🧭 Digital Leadership (DL)"
lang: en

bibliography: ../assets/literature.bib

format: 
  html:
    output-file: index.html
  letterbox-revealjs:
    output-file: slides.html
    date: "Summer Term 2023"
    include-before-body: ../assets/footer.html
---

# Top {visibility="hidden" .slide-link-hidden .unlisted .unnumbered}

{{< include ../assets/_top.qmd >}}

__Printing/export:__ If you want to print or export the slides, open the slides, press `e` on your keyboard and then print (to pdf).

# Expectations {.html-hidden .unlisted background-color=black}

:::{.h1}

What do you expect to learn in this course?

:::

# Motivation

:::{.notes}
Society often associates leaders with individuals that have grandiose titles, a large corner office, and make world-changing decisions. Thus, many people shy away from identifying themselves as a leader. However, real leadership can be seen most clearly in the small moments throughout the day. 

> Leadership is about behaving in a way that makes the life of another person better than before you arrived. *Drew Dudley*
:::

<div style="max-width:854px"><div style="position:relative;height:0;padding-bottom:45%"><iframe src="https://embed.ted.com/talks/lang/en/drew_dudley_everyday_leadership" width="854" height="480" style="position:absolute;left:0;top:0;width:100%;height:100%" frameborder="0" scrolling="no" allowfullscreen></iframe></div></div>

# General remarks

This module helps you to deepen your understanding of the requirements of leadership in the digital age — from leading oneself, to leading employees and leading systems. 

. . .

To achieve that, you will read a bunch of **scientific papers**, apply some of the findings in **(group) exercises** and, best case, reflect your own behavior.

. . .

As a **graded exam assignment**, research a theory/theoretical construct related to leadership, explain it to the class, and critically discuss its value to leadership practice.

. . .

It is very important that you prepare yourself for the classes (see @tbl-schedule for details).

# Contents

The following topics will be discussed in order to identify and reflect on challenges and opportunities in different leadership roles and situations:

:::{.incremental}
- __Challenges of leading in the digital age__ (e.g., VUCA, role of technology, etc.)
- __Basics of leadership__ (e.g., motivation, leadership types, empathy, etc.)
- __Theories__ (e.g., resources and demand theory, identities at work, trust, psychological safety, etc.)
- __Digital leadership tools__ (workshop tactics and storytelling, etc.)
:::

# Learning objectives

During this course, you should improve your ability to consciously use, reflect on and further develop your leadership skills in your day-to-day work, in particular with regard to

::: {.incremental}
- __Leadership requirements__ in the context of digital transformation,
- Identification of and reflection on __challenges and opportunities in your own leadership role__,
- Understanding of the facets of different __personality types__,
- Basic understanding of characteristics of __sustainable organizational systems__, and
- Lead hierarchically and laterally using __digital leadership tools__.
:::

# Effort

You will gain 5 ECTS for this course. This equals approx. __150 hours workload__, of which you need most to pass the course.

::: {.incremental}
-	Classes (approx. 30 hours)
- Preparation and follow-up (approx. 15 hours)
- Preparation of the presentation (remaining time)
:::

::: {.fragment}
Please prepare your schedule accordingly.
:::

# Schedule {.scrollable .smaller}

::: {.notes}
It is of importance that you prepare yourself for the sessions and work on the case study continually. Please prepare your schedule accordingly.
:::

| Date         | Topic                                                               | Preparation      |
|:-------------|:--------------------------------------------------------------------|:-----------------|
| `20.03.2023` | Administrivia & introduction (digital age)                          | -
| `27.03.2023` | Assessing the characteristics of effective (digital) leaders        | Reading
| `03.04.2023` | Exposing some myths of management                                   | Reading
| `17.04.2023` | Creating a culture of engagement                                    | Reading
| `24.04.2023` | Leading innovation, leading transformation                          | Reading
| `08.05.2023` | Excursion week (no lecture)                                         | -
| `15.05.2023` | Workshop: storytelling                                              | -
| `21.05.2023` | **Deadline** upload presentation slides                             | Deliverables
| `22.05.2023` | Student presentations — session #1                                  | -
| `12.06.2023` | Student presentations — session #2                                  | -
| `19.06.2023` | Student presentations — session #3                                  | -
| `26.06.2023` | Student presentations — session #4                                  | -
| `03.07.2023` | Workshop: retrospective                                             | -

: Schedule summer term 2023 (may be subjected to changes) {#tbl-schedule}
