---
title: "Administrivia 🧐"  
subtitle: "`DIM_3` Academic Writing (AW)"

format: 
  html:
    output-file: index.html
  revealjs:
    output-file: slides.html 
    include-after-body: ../assets/footer.html
---

# Top{visibility="hidden" .slide-link-hidden .unlisted .unnumbered}

{{< include ../assets/_top.qmd >}}

__Printing/export:__ If you want to print or export the slides, open the slides, press `e` on your keyboard and then print (to pdf).

# Motivation {.vertical-center background-color=blue background-image="images/bg.jpg"}

> Publication is an essential scholarly activity because it informs academic and other communities about lines of investigation, (and their
outcomes) related to relevant phenomenon being studied. *Jan Recker, Professor for Information Systems and Digital Innovation *

---

This course is designed to improve your academic writing skills by exercising the full publication cycle. While doing that, you will make significant progress on setting up your Master's thesis.

# Contents

Publishing research is the primary vehicle for __adding to the body of knowledge__.

. . .

Writing a good research article is challenging and consumes a great deal of time and dedication. This course aims to support you in these endeavours, particularly regarding

:::{.incremental}
- the __writing process and strategy__ (e.g., research, planning, summarizing, organizing, referencing).
- the __elements of writing__ (e.g., argument and discussion, cause and effect, style)
- writing __vocabulary and language__ (e.g., precision, clarity, conciseness)
- __structure of an academic paper__ (e.g., outline of the document)
- __review process__ (e.g., writing a review, writing a response to the reviewer letter)
:::

In addition, you will have the opportunity to discuss individual questions during __language coaching sessions__

# Learning outcomes

Upon successful completion of this course, you will have advanced knowledge and skills in following areas

::: {.incremental}
- techniques, guidelines, elements, structures, vocabulary and language, and formal requirements of __academic written communication__, particularly in the field of management and information system research,
- __development of scientific texts__ that are coherent, clear, concise and can be printed in a journal or conference proceedings,
- mastering the written elements of a __peer-review process__,
- __usage of tools__ that support the writing process,
- mastering the challenge of __building on work done by others__ and create something original from it, while maintaining academic integrity and uphold the standards of good academic work.
:::

# Approach

This course combines presence teaching (_in-class_), writting exercises (_pre- and post-class_), and self-learning components (_pre- and post-class_).

. . .

The focus of the presence-teaching sessions is on giving you input to selected topics, answering your questions, doing some short exercises, and choaching you on your writting project.

. . .

The learning progress is reflected in the learning you take from __working on an academic manuscript__ and __going through the review process__, more precisely, the deliverables of the [assignment](../assignment/) (portfolio exam).


## Effort

You will gain 5 ECTS for this course. This equals approx. __125 hours workload__, of which you need most to pass the course.

::: {.incremental}
-	Joint sessions including follow-up: __approx. 30 hours__
-	Assignment (manuscript, review, revision, presentation): __approx. 90 hours__
:::

. . .

Please prepare your schedule accordingly.

## Schedule {.scrollable .smaller}

:::{.notes}
To make this course as valuable as possible in preparation for your Master's thesis, we have blocked the bulk of the courses at the beginning of the semester. You will be through with the course by mid-December. 
:::

::: {.column-page-right}

|Date                  |Topic                          |Bonus  |Lecturer | Location  |
|:---------------------|:------------------------------|:------|:--------|:----------|
|`27/09/2022, 9.45 am` |Kick-off and topic selection   |Theory |Weeger   |E5.1.08
|`29/09/2022, 9.45 am` |Process & strategy             |Method |Weeger   |E5.1.08
|`30/09/2022, 9.45 am` |Structure and story            |-      |Weeger   |E5.1.08
|`05/10/2022, 9.45 am` |Review & revisions             |-      |Weeger   |A.2.48
|`05/10/2022, 2.00 pm` |Presentation & defense         |Method |Weeger   |A.2.48
|`tbd`                 |Elements of writing            |-      |Zenk     |
|`tbd`                 |Vocabulary & language          |-      |Zenk     |
|`tbd`                 |Writing styles                 |-      |Zenk     |
|`tbd`                 |Coaching                       |-      |Zenk     |
|`tbd`                 |Coaching                       |-      |Zenk     |
|`tbd`                 |Coaching                       |-      |Zenk     |
|`28/10/2022`          |__Deadline Proposal__          |-      |-        |
|`04/11/2022`          |__Deadline Review__            |-      |-        |
|`25/11/2022`          |__Deadline Revision__          |-      |-        |
|`08/12/2022`          |__Presentations__              |-      |Both     |

: Schedule winter term 2022 (may be subjected to changes) {#tbl-schedule}

:::

# Grading

The grade is based on the evaluation of multiple __[assignments](../assignment/)__ (portfolio exam):

:::{.incremental}
- thesis proposal *(40%)*
- review of a fellow student's proposal (*20%*)
- revision of the proposal incl. response letter (*20%*)
- presentation of the proposal (*20%*)
:::

# Q&A {.html-hidden .unlisted .vertical-center background-color=blue background-image="images/bg.jpg"}