---
title: "Assignment"  
subtitle: "Business Value Creation by IT (BVC)"
lang: en
categories: ["Exam"]

author: "Andy Weeger"

date: "03.06.2025"

bibliography: ../assets/literature.bib

format: 
  html:
    output-file: index.html
    margin-header: | 
      [Slides](slides.html){.btn .btn-primary target="blank"}
    format-links: false       
  presentation-revealjs:
    output-file: slides.html
    include-before-body: ../assets/footer.html
---


# Task

During the semester you will be required to work on a **business challenge** posed by a company partner. **As a group**, you

:::incremental
- gather information about the practical context of the business challenge,
- research information about the topic (state of research and practice),
- identify and understand stakeholders that are affected by the problem as well as their needs,
- develop an innovative, **agent-based approach** to tackle the problem,
- detail the solution and create a running prototype,
- create an implementation plan,
- detail and reflect on the specific value creation mechanisms (e.g., monetarization opportunities, cost savings, etc.), and
- discuss lessons learnt, contributions and practical recommendations for action.
:::

## Challenge

The __business challenges__ will be presented in our second session. 

:::incremental
- You are free to select one of the presented challenges within one week after presentation.
- You document your decision in Moodle.
:::

. . .

**Five (5) students form a group.**

:::incremental
- You can make an initial proposal for the group constellations within the first class.
- I will check the proposal and adjust it if necessary.
- I will assign all laggards to the groups.
:::

. . .

__Everyone shares responsibility for the results of the group.__ If you have problems in the cooperation that you cannot solve yourself, you must proactively indicate them.



## Deliverables

As a group, you will deliver a __final presentation__ and a __seminar paper__.

:::incremental
- The __presentation__ gets to the heart of your idea (25% of the grade):
  - Short summary of your concept (i.e., elevator pitch)
  - Presentation of the prototype of your design
- The __seminar paper__ is a detailed documentation of your approach and of the artefact (75%):
  - An understanding of the problem and the needs of the stakeholders
  - Your approach to IT-enabled value creation incl. boundary conditions
  - Details of the artifact (i.e., the prototype) that you have developed
  - Your implementation and value-realization plan
  - Lessons learnt, contributions and practical recommendations for action
:::


:::fragment
:::smaller
The grade is the weighted average of the group score (60%) and the individual contributions (40%); the individual contributions must be indicated.
:::
:::


## Presentation

You have 12 minutes for the presentation (date please see the [schedule](../admin/index.html#schedule))

:::incremental
- Every group member needs to take a part of the presentation.          
  Please make sure that the speaking time is distributed equally.
- Set-up the presentation as a convincing pitch.
- Show your prototype in action.
- There are no formal requirements on the slides.
- Slides must be handed in as PDF (Moodle).
- There will be a Q&A at the end (incl. hands-on with the prototype).
:::

----

#### Evaluation criteria

The main criteria is how convincing your pitch and solution is.

In addition, I look at the following criteria:

- The problem is clearly and comprehensively defined, with a strong understanding of the stakeholder(s) and their needs.
- The proposed approach to value creation is logical, complete, and well-aligned with the problem and stakeholder needs.
- The solution is well-developed, addresses the problem effectively, and reflects the characteristics of a viable MVP.
- The team communicates clearly, confidently, and professionally, telling a convincing story and using effective visuals.
- The presentation is well-structured with clear flow, transitions, and effective use of time.
- The presentation is free from language, spelling, or formatting errors and demonstrates high attention to quality.

## Seminar paper

[Contents and structure]{.h4}

:::notes

- __Abstract__: Gives a short elevator pitch of the approach that sums up your concept in a nutshell.

- __Introduction__: Provides an introduction that piques the reader's interest or curiosity for what is to come by indicating the main challenge.

- __Problem definition__: Outlines the specific problems that you have identified and that your solution is intended to address, as well as the stakeholders that will be affected and their needs. Also be clear about the consequences of failing to solve the challenge. You synthesise these into a concise problem statement. There is a need for reference to (scientific) literature here.

- __Approach__: Describe and discuss your approach to using IT to address the challenge and to create value for the organisation. You also need to consider alternatives to what you propose. Show why your approach is different from the alternatives and why it is more promising. 

- __Solution__: Provides a detailed description of the solution, including technical details. In this section you should clearly show how the (characteristics of the) solution will support or enable your approach to IT-enabled value creation. Please also be specific in your description of the innovative nature of your solution.

- __Implementation__: This section covers how the organisation should and has implemented your solution, including a discussion of any potential hurdles that may need to be overcome. Also include how you plan to evaluate effectiveness.

- __Discussion__: Presents lessons learned, contributions and practical recommendations for action that go beyond the specific challenge. This involves looking at (scientific) literature.

- __Appendix__: Provides information that may help to gain an even better understanding of your solution.

:::

:::html-hidden
::::columns
:::column
:::incremental
- Abstract
- Introduction and problem definition *(challenge, needs, status quo)*
- Approach *(value creation mechanism)*
:::
:::
:::column
:::incremental
- Solution *(detailed description)*
- Implementation *(value realization)*
- Discussion
- Appendix
:::
:::
::::
:::

:::fragment

[Formal requirements]{.h4}

:::incremental
- Use the template offered [here](assets/BVC_Template.docx) 
- The paper should contain min. 6 pages of text per person, maximum 10 (details see template)
- The paper must be uploaded as PDF (Moodle)
- Individual contributions must be identified (listed in a table in the Appendix)
:::
:::

----

[Evaluation criteria]{.h4}

An __exemplary seminar paper__ has the following characteristics 

- The intro makes the reader want to read further
- The problem definition is concise and comprehensive
- The reader is able to picture the stakeholder and their needs
- The approach to value creation is fully elaborated, complete and makes sense
- The characteristics of the solution relate well to the problem and the approach
- The solution has the maturity level of an MVP (value creation can be demonstrated)
- The description of the solution allow for a detailed understanding
- The recommendations for value realization as well as their rationale make sense
- The solution and the process are well reflected (lessons learned and contributions)
- There are very few errors, the writing is clear, and easy to read and engaging
- The originality of the solution is clear and the used sources are evident

## A note on grades

:::notes
It is unlikely that every student will receive a very good grade, i.e. deliver an outstanding performance - see the meaning of grades.  Instead, it is to be expected that the grades will spread across the spectrum. 
:::

| Grade                    | Meaning
| ------------------------ | -------------------------------------------------------------------- |
| `1` — very   good            | [A   truly outstanding achievement that (not only) shows no deficiencies in the criteria mentioned, but also gives both the supervisor and external assessors an excellent   impression.]{.fragment} |
| `2` — good                   | [Work   that exceeds the average requirements/performance and is easily recognizable   and presentable to the outside world as a “good performance”.]{.fragment}                                              |
| *Note*                   | *2.5   is the average of passed assessments, i.e., an “average   performance”*                                                                                             |
| `3` — satisfactory           | [A   performance that achieves the desired goal "to a satisfactory   extent";       however, deficiencies can be identified here and there. ]{.fragment}                                                      |
| `4` — sufficient             | [A   performance that “still adequately satisfies” the requirements,       but deviates from the expectations placed on it in several ways.  ]{.fragment}                                                     |
| `5` — not   sufficient      | [A   performance that does not meet several of the criteria mentioned.]{.fragment}                                                                                                                                  |
# Q&A {.html-hidden .unlisted background-color="#0333ff"}

# Literature
::: {#refs}
:::