---
title: "Topics"
subtitle: "IT as a Service Enabler (ITSE)"

bibliography: ../assets/literature.bib

format: 
  html:
    output-file: index.html
  presentation-revealjs:
    date: "Winter Term 2022"
    output-file: slides.html 
    include-before-body: ../assets/footer.html  
---


# Overview

**General remark:** When you work on the topics, your ambition should be to produce a solid scientific paper (good way to prepare for the BA)

. . .

Topics:

:::{.incremental}
- Mobility behavior change *(design science, group-work 3 students)*
- EV charging network apps *(empirical paper, 1 student)*
- Smart carpooling platforms *(empirical paper, 1 student)*
- Private car-sharing *(structured literature review, 1 student)*
- Gamification for sustainable innovation *(structured literature review, 1 student)*
:::

## App for mobility behavior change

Your task is to design and evaluate an app that leads to more sustainable mobility behavior in order to derive design principles for stimulating sustainable mobility behavior (RQ: "what are information system design principles for stimulating sustainable mobility behavior?).

As to that, you will adopt a design science approach [see e.g., @hevner2010design] and

- review the literature and summarize the knowledge about how to artefacts that support behavioral change *(joint work)*, 
- derive the design principles based on prior literature *(joint work)*, 
- create a concept for the app *(student A)*, 
- develop a minimal viable product, e.g. using low-code platforms *(student B)*,
- test the app and its effects, e.g. among students *(student C)*,
- update the design principles based on the evaluation *(joint work)*.

You will report and discuss your findings in **a joint paper**.

:::{.notes}
#### Starting points for reading:

- @koivisto2019rise
- @al2017discovering
- @yun2013sustainability
- @consolvo2006design
- @consolvo2009theory
:::

## Analysis of EV charging network apps

Your task is to compare two EV charging network apps (ENBW mobility+ and IONITY) to derive factors that determine customer perceived value of the apps.

As to that, you will adopt a qualitative research approach and

- review the literature on customer perceived value of (mobile) applications,
- summarize your assumptions based on the literature (e.g., what are critical factors),
- analyze reviews of the ENBW mobility+ and IONITY apps in the Apple App Store [similar to @schulz2021value] to see if your assumptions hold true.

You will report and discuss your findings in a paper.

:::{.notes}
#### Starting points for reading:

- @sanchez2007concept
- @wang2008assessing
:::

## Analysis of smart carpooling platforms

Your task is to analyze the the carpooling app [twogo](www.twogo.com) to derive factors that determine customer perceived value of such platforms

As to that, you will adopt a qualitative research approach and

- review the literature on customer perceived value (in general) and carpooling platforms,
- summarize your assumptions based on the literature (e.g., what are critical factors), and
- analyze reviews of the twogo app in the Apple App Store [similar to @schulz2021value] to see if your assumptions hold true.

You will report and discuss your findings in a paper.

:::{.notes}
#### Starting points for reading:

- @sanchez2007concept
- @wang2008assessing
:::

## Status quo of private car-sharing

Your task is to conduct a structured literature review on private car-sharing to summarize the knowledge on this approach and the technology used (RQ: "How do information systems support private car-sharing efforts?").

As to that, you will conduct a structured literature review [following @webster2002analyzing] and

- do an exploratory literature review to identify key-words,
- perform a systematic literature search using the *Web of Science*, and
- analyze the included papers and synthesize the status quo.

You will report and discuss your findings in a paper.

:::{.notes}
#### Starting points for reading:

- @ferrero2018car
- @hildebrandt2015value
- @degirmenci2014carsharing
:::

## Status quo of gamification for sustainable innovation

Your task is to conduct a structured literature review on gamifaction approaches for sustainable innovation (RQ: "How does gamification enable sustainable innovation?").

As to that, you will conduct a structured literature review [following @webster2002analyzing] and

- do an exploratory literature review to identify key-words,
- perform a systematic literature search using the *Web of Science*, and
- analyze the included papers and synthesize the status quo.

You will report and discuss your findings in a paper.

:::{.notes}
#### Starting points for reading (gamification in general):

- @koivisto2019rise
- @mora2017gamification
- @fortes2018theory
- @gholami2016information
:::


# References
::: {#refs}
:::