---
title: "Podcasts"
subtitle: "Grundzüge WI/IM"
lang: de

format: 
  revealjs:
    output-file: slides.html 
    include-after-body: assets/footer.html
---

# `K1` Einführung {.vertical-center background-color=black background-image="images/bg.jpeg"}

Was ist das und weshalb ist es wichtig?

`Grundzüge WI/IM`

# `K2` Das digitale Zeitalter {.vertical-center background-color=black background-image="images/bg.jpeg"}

Was macht unsere Zeit besonders?

`Grundzüge WI/IM`

# `K3` IT {.vertical-center background-color=black background-image="images/bg.jpeg"}

Was ist die Basis von Informationssystemen?

`Grundzüge WI/IM`

# `K4` Datenbanken #1 {.vertical-center background-color=black background-image="images/bg.jpeg"}

Wie können Daten strukturiert werden?

`Grundzüge WI/IM`

# `K5` Datenbanken #2 {.vertical-center background-color=black background-image="images/bg.jpeg"}

Wie können Datenstrukturen abgebildet werden?

`Grundzüge WI/IM`

# `K6` Anwendungssysteme {.vertical-center background-color=black background-image="images/bg.jpeg"}

Welche gibt es und wozu?

`Grundzüge WI/IM`

# `K7` Geschäftsprozessmanagement {.vertical-center background-color=black background-image="images/bg.jpeg"}

Wie können Abläufe gesteuert werden?

`Grundzüge WI/IM`

# `K8` Prozess-Modellierung {.vertical-center background-color=black background-image="images/bg.jpeg"}

Wie können Prozesse verständlich abbilden?

`Grundzüge WI/IM`

# `K9` IT-Management {.vertical-center background-color=black background-image="images/bg.jpeg"}

Wie steure ich IT im Unternehmen?

`Grundzüge WI/IM`

# `K10` Digitale Geschäftsmodelle {.vertical-center background-color=black background-image="images/bg.jpeg"}

Was ist das nächste große Ding?

`Grundzüge WI/IM`