---
title: "Assignment 📑"  
subtitle: "💎 Business Value Creation with IT (BVC)"
lang: en

date: 10.07.2024

format: 
  html:
    date-modified: "10.07.2024"       
    output-file: index.html
---


# General remarks

The lecture will not be offered in winter term 2024/2025. Therefore, only the information on the repeat examination is provided here. 

The exam is similar to that in summer term 2024 with two exceptions: 

- You work on your own
- You are not required to develop a MVP, but to propose a technical solution that would work.

In order to solve the challenge, you will

- gather information about the practical context of the business challenge,
- research information about the topic (state of research and practice),
- identify and understand stakeholders that are affected by the problem as well as their needs,
- develop an innovative approach to tackle the problem,
- detail technical details of your proposed solution,
- create an implementation plan,
- detail and reflect on the specific value creation mechanisms (e.g., considering privacy and traceability), and
- discuss lessons learnt, contributions and practical recommendations for action.

# Business challenge

It is important for (contemporary) organizations to know the knowledge and skills of their employees for several reasons:

- Effective use of resources: if an organization knows what skills and knowledge its employees have, it can target them and plan projects more efficiently.
- Employee development: By understanding current skills, targeted training and development programs can be created to enhance employee competencies.
- Innovation and competitive advantage: Employees with specific knowledge and skills can develop innovative solutions and help the organization stand out from the competition.
- Employee satisfaction: When employees are deployed in areas where they can play to their strengths, their satisfaction and motivation increases.
- Succession planning: Organizations can better plan which employees are suitable for future management positions if they know their skills and potential.

However, it is difficult to gain a good understanding of the (evolving) knowledge and skills of employees. Often, organizations rely on the knowledge acquired in development programs and the views of superiors, which may be collected in a very structured way as part of talent programs. With the new possibilities offered by generative AI, companies could not only increase the productivity of their employees, but also get to know and use their specific knowledge and skills in a contextual and a more informal and continuous mode.

Your task is to recommend a solution that leverages the potential of LLMs to improve an organization's ability to map, update and harness existing knowledge and skills.

## Key Questions

- How can LLMs be used to enhance the understanding of the skills and knowledge available in the organization?
- How can knowledge of employees be gained in a natural and non-disrupting mode?
- What techniques or approaches does your model employ to overcome challenges such as resistance to share knowledge and potential biases?

## Goals and outcome

The goal is to find innovative solutions that help to design interactions with an LLM-powered system that allow the organizations to map and harness existing knowledge and skills.

For this purpose, a concept with proof-of-concept is to be submitted as well as the concept and outline for further implementation.

### Requirements

Technology
: The proposed solution should be a large language model (LLM) that can be integrated directly into the web browser. You can propose to utilize available resources, such as leveraging an existing (open source) LLM or building your own model.

Willingness to use
: The proposed solution should enhance employees willingness to share their knowledge and skills and to track how it developed

Information aggregation
: The solution should focus on summarizing and aggregating information from various sources, both internal and external. Think of using APIs such as the google search API and APIs of document management systems and other internal enterprise information systems

Privacy
: Show how the proposed solution meets data protection requirements and provide users with a secure and trusted environment.

# Deliverables

You will deliver a __final presentation__ and a __seminar paper__.

- The __presentation__ gets to the heart of your idea (25% of the grade):
  - Short summary of your concept (i.e., elevator pitch)
  - Presentation of the technical design
- The __seminar paper__ is a detailed documentation of your approach (75%):
  - An understanding of the problem and the needs of the stakeholders
  - Your approach to value creation incl. boundary conditions
  - Technical details of the solution that you propose
  - Your implementation and value-realization plan
  - Lessons learnt, contributions and practical recommendations for action

## Dates

The scheduled date for the presentations is **January 16, 2024 at 8.30 am**. The room will be announced. The slides must be submitted via E-Mail beforehand.

The deadline for the seminar paper is **January 24, 2024 at 8 pm**. The seminar paper must be submitted in time via E-Mail

## Presentation

You have 15 minutes for the final presentation.

- Set-up the presentation as a convincing pitch.
- There are no formal requirements on the slides.
- Slides must be handed in as PDF via E-Mail.
- There will be a Q&A at the end.

### Evaluation criteria

An __exemplary presentation__ has the following characteristics 

- The student demonstrates excellent understanding of the problem, the approach, the solution and/or the implementation plan.
- The students is professional, extremely well prepared, and easily able to respond to even tough questions.
- Visual aids are well done and are used to make presentation more interesting and meaningful.
- The presentation is well organized with a beginning, middle and end. There is a strong organizing theme, with clear main ideas and transitions.
- The student speaks in a clear voice and show a flair for communicating with the audience.
- The students makes excellent use of the allowed time.
- The presentation slides are error free (spelling and language).

## Seminar paper

### Contents and structure

- __Abstract__: Gives a short elevator pitch of the approach that sums up your concept in a nutshell.

- __Introduction__: Provides an introduction that piques the reader's interest or curiosity for what is to come by indicating the main challenge.

- __Problem definition__: Outlines the specific problems that you have identified and that your solution is intended to address, as well as the stakeholders that will be affected and their needs. Also be clear about the consequences of failing to solve the challenge. You synthesise these into a concise problem statement. There is a need for reference to (scientific) literature here.

- __Approach__: Describe and discuss your approach to using IT to address the challenge and to create value for the organisation. You also need to consider alternatives to what you propose. Show why your approach is different from the alternatives and why it is more promising. 

- __Solution__: Provides a detailed description of the proposed solution, including technical details. In this section you should clearly show how the (characteristics of the) solution will support or tackle the business challenges outlined. Please also be specific in your description of the innovative nature of your solution.

- __Implementation__: This section covers how the organisation should and has implemented your solution, including a discussion of any potential hurdles that may need to be overcome. Also include how you plan to evaluate effectiveness.

- __Discussion__: Presents lessons learned, contributions and practical recommendations for action that go beyond the specific challenge. This involves looking at (scientific) literature.

- __Appendix__: Provides information that may help to gain an even better understanding of your solution.

### Formal requirements

- Use the template offered [here](assets/BVC_Template.docx) 
- The paper should contain min. 10 pages of text (details see template)
- The paper must be uploaded as PDF via E-Mail
- Individual contributions must be identified (listed in a table in the Appendix)


### Evaluation criteria

An __exemplary seminar paper__ has the following characteristics 

- The intro makes the reader want to read further
- The problem definition is concise and comprehensive
- The reader is able to picture the stakeholder and their needs
- The approach to value creation is fully elaborated, complete and makes sense
- The characteristics of the solution relate well to the problem and the approach
- The description of the solution allow for a detailed understanding
- The recommendations for value realization as well as their rationale make sense
- The solution and the process are well reflected (leassons learned and contributions)
- There are very few errors, the writing is clear, and easy to read and engaging
- The originality of the solution is clear and the used sources are evident

# Coaching

If you have questions or want to discuss intermediate results, please book an appointment via [calendly](https://calendly.com/awe-hnu/office).