---
title: "Übungsblatt (THE-2)"
subtitle: "Grundzüge Informationsmanagement (GIM)"
lang: de-DE

format: 
  html:
    output-file: index.html
---

# Lernkontrolle 🧐 {visibility="hidden"}

Bearbeiten Sie __selbstständig__, ohne Abstimmung in der Gruppe folgende Aufgaben.

## Aufgabe 1 (5 Punkte)

Modellieren Sie das __Entity-Relationship Modell in der (min,max)-Notation__ für folgendes Carsharing-Verwaltungssystem:

Über den Carsharing Dienst der Studierendenvertretung stehen mehrere Autos unterschiedlicher Typen und Hersteller zur Verfügung. Die Autos können über die Fahrgestellnummer (FIN) eindeutig identifiziert werden. 

Die Service-Mitarbeiter der Studierendenvertretung kümmern sich um die Autos. Zu den Mitarbeitern wird der Name und die Mitarbeiter-Nr. im System gespeichert. Damit eine Vertretung sichergestellt ist, kümmern sich jeweils genau zwei Mitarbeiter um ein Auto. Ein Service-Mitarbeiter kann sich um unterschiedliche Autos kümmern.

Studierende können mehrere Mietauträge für Autos platzieren. Von den Studierenden werden Matrikel-Nr. und Name gespeichert. Im Mietauftrag werden das geliehene Auto (je Auftrag eines), das Datum, die Start-km und die End-km festgehalten.

Sie können, falls für ein formal korrektes ERM notwendig, Annahmen treffen und Ergänzungen vornehmen. Machen Sie diese deutlich.

## Aufgabe 2 (2 Punkte)

Stellen Sie die Relation __Mietauftrag__ in der in der Vorlesung vorgestellten Form dar (tabellarisch).

## Aufgabe 3 (1 Punkt)

Zeigen Sie, wie die Beziehung zwischen __Service-Mitarbeiter und Auto__ im Relationenmodell aufgelöst wird.

## Aufgabe 4 (5 Punkte)

Erstellen Sie ein __eEPK__ zu folgendem Prozess:

Ein neuer Student registriert sich auf der App des Carsharing Dienst. Um Redundanzen zu vermeiden wird als nächstes geprüft, ob der Kunde bereits im Verwaltungssystem angelegt ist. Nur wenn zum Kunden noch kein Kundenstammdatensatz vorhanden ist, wird dieser in der Datenbank des Verwaltungssystems angelegt. Als nächstes wird immer die Kundenummer im Verwaltungssystem ausgelesen. Diese wird dann im Nutzerprofil in der App hinterlegt. Der Prozess endet grundsätzlich mit der Benachrichtigung des Kunden.

## Aufgabe 5 (2 Punkte)

Erläutern Sie in Ihren eigenen Worten, weshalb die Erstellung der ERM und eEPK-Modelle im Rahmen der Entwicklung des Carsharing-Verwaltungssystem notwendig ist und wobei insbesondere das eEPK-Modell über die Anwendungssystementwicklung hinaus hilfreich sein kann. Halten Sie Ihre Erläuterung kurz und präzise.

# Abgabe

Legen Sie für jede Aufgabe eine DIN A4 Seite an. Ergänzen Sie im Kopfbereich aller fünf Seiten folgende Informationen: „IMUK1 Grundzüge IM, Sommersemester 2022, Prüfungsleistung THE-2“, Ihren vollständigen Namen, Ihre Matrikel-Nummer und die Bezeichnung der Aufgabe.

Wenn Sie handschriftlich gearbeitet haben, fotografieren Sie alle Seiten und erstellen ein PDF. Wenn Sie am PC gearbeitet haben, erstellen Sie direkt ein PDF. Das PDF mit den Lösungen zu allen Aufgaben laden Sie als Ergebnis in Moodle hoch. Abgabefrist siehe Hinweise im Moodle-Kurs.

Bei Abgabe der Prüfungsleistung versichern Sie, dass Sie die eingereichte Prüfungsleistung ohne fremde Hilfe verfasst haben. Ihnen ist bewusst, dass bereits der Versuch, das Ergebnis der Arbeit durch Täuschung (z.B. durch Mithilfe Dritter, auch Kommilitonen) zu beeinflussen, zur Bewertung 5,0 („nicht ausreichend“) bzw. „nicht bestanden“ führen kann“.