---
title: "Pressemeldung (THE-1)"
subtitle: "Grundzüge Informationsmanagement (GIM)"
lang: de-DE

format: 
  html:
    output-file: index.html
---

# Kontext

Die Vereinten Nationen (UN) haben in ihrer Agenda 2030 __17 Ziele für nachhaltige Entwicklung__ (Sustainable Development Goals, SDGs) festgelegt. Die Agenda 2030 mit ihren Zielen ist ein globaler Plan zur Förderung nachhaltigen Friedens und Wohlstands und zum Schutz unseres Planeten. Seit 2016 arbeiten alle Länder daran, diese gemeinsame Vision zur Bekämpfung der Armut und Reduzierung von Ungleichheiten in nationale Entwicklungspläne zu überführen. 
Mehr Informationen zu den Zielen finden Sie auf der Website der UN ([United Nations Sustainable Development – 17 Goals to Transform Our World](https://sdgs.un.org/goals))

Im Zusammenhang mit den Zielen hat der Generalsekretär der UN, Antonio Guterres, bei der Abschlussveranstaltung des „High-level Political Forum on Sustainable Development 2018“ (HLPF 2018) folgendes gesagt: 

> Technology has great potential to help deliver the SDGs, but it can also be at the root of exclusion and inequality. We need to harness the benefits of advanced technologies for all.

Während des HLPF 2018 wurden verschiedene Möglichkeiten diskutiert, wie digitale Technologie helfen können, die SDGs zu erreichen. Zum Beispiel könnte IT helfen, Ungleichheit zu minimieren, indem sie den Zugang zu grundlegenden Dienstleistungen wie Gesundheit oder Bildung vereinfacht. Gleichsam kann Technologie von Regierungen genutzt werden, um sich durch E-Gouvernement-Tools besser mit ihren Bürgern zu vernetzen und die Einbindung von Stakeholdern und das Informationsmanagement zu verbessern.

# Aufgabe

Ihre Aufgabe ist es, zu überlegen, wie eine Organisation (bspw. die HNU) durch den Einsatz von Informationstechnologie (IT) und zum Erreichen eines __spezifischen Ziels der SDGs__ ("Target") beitragen kann. Überlegen Sie insbesondere, wie effizientes Informationsmanagement Unternehmen dabei unterstützen kann.

:::{.callout-note}
### Beispiel eines spezifischen Ziels
Das SDG#2 ist *"End hunger, achieve food security and improved nutrition and promote sustainable agriculture"*   
Unter diesem SDG wurde unter anderem folgendes __spezifische Ziel__ formuliert: *"By 2030, ensure sustainable food production systems and implement resilient agricultural practices that increase productivity and production, that help maintain ecosystems, that strengthen capacity for adaptation to climate change, extreme weather, drought, flooding and other disasters and that progressively improve land and soil quality."* (Target 2.4)
::::

Ihre Idee beschreiben Sie in einer Pressemitteilung, die das Unternehmen am 6. Mai veröffentlichen wird. Die Leser der Pressemitteilung müssen in wenigen Zeilen verstehen, wie die Organisation IT einsetzt, um zu den SDGs beizutragen und gleichzeitig den wirtschaftlichen Erfolg sicherstellt (bzw. ohne diesen zu gefährden). 

Im ersten Absatz sollten Sie das Problem umreißen und den Lösungsansatz des Unternehmens kurz beschreiben. Es ist entscheidend, dass Sie das Interesse des Lesers wecken und diesen zum Weiterlesen motivieren. Im restlichen Teil der Pressemitteilung beschreiben Sie den Ansatz im Detail und gehen speziell auch darauf ein, wie IT das Unternehmen befähigt, einen signifikanten Beitrag zum gewählten Ziel der SDGs zu leisten.

## Form
Die Pressemeldung sollte inkl. Überschrift 750 Wörter und darf eine DIN A4 Seite nicht überschreiten.

Formatieren Sie Ihren Text wie folgt: 

- Schriftgröße Arial 10 Pt
- Überschrift fett
- Fließtext Blocksatz
- 12 Pt Zeilenabstand und 2-spaltig gesetzt
- Seitenränder rundum 2 cm
- Keine Leerzeile zwischen den Absätzen (wohl aber Absätze).

Nach dem letzten Absatz fügen Sie Ihren vollständigen Namen und Ihre Matrikelnummer ein. Speichern Sie ein PDF und laden Sie dieses vor der Deadline in Moodle hoch.

Bei Abgabe der Prüfungsleistung versichern Sie, dass Sie die eingereichte Prüfungsleistung ohne fremde Hilfe verfasst haben. Ihnen ist bewusst, dass bereits der Versuch, das Ergebnis der Arbeit durch Täuschung (z.B. durch Mithilfe Dritter, auch Kommilitonen) zu beeinflussen, zur Bewertung 5,0 („nicht ausreichend“) bzw. „nicht bestanden“ führen kann.

## Bewertungskriterien

- Deutlicher Bezug zu einem spezifischen Ziel der SDGs (10%)
-	Nachvollziehbare Beschreibung des Ansatzes (20%)
-	Potenzial der Technologie zur Problemlösung (20%)
-	Einzigartigkeit der Idee (20%)
-	Aufbau und Struktur der Argumentation (20%)
-	Form (10%) 