---
title: "Administrivia 🧐"  
subtitle: "🧑‍🔬 DI in Industry (DIiI)"

format: 
  html:
    output-file: index.html
  revealjs:
    output-file: slides.html 
    include-after-body: ../assets/footer.html
---

# Top{visibility="hidden" .slide-link-hidden .unlisted}
[Slides](slides.html)

__Printing/export__

If you want to print or export the slides, open the slides, press `e` on your keyboard and then print (to pdf).

# General remarks

This course will be taught using traditional synchronous lectures. The focus of the live sessions is on discussing real world cases and developing theoretically-based explanations. In addition, you will do an original research on a digital innovation case on your own (see [assignment](../assignment/)).

It is of really important that you prepare yourself for every session. You either need to work through teaching materials in advance or prepare to present the deliverables of your own case (see @tbl-schedule).

# Contents

This course offers you the possibility to learn about industry-specific challenges and how this influences the way of organizing, managing and communicating digital innovations, in particular:

:::{.incremental}
- __Specifics of industries__ (context, products, markets, obstacles, enablers)
- Industry-specific applicability and adaptations of __innovation strategies__
- __Methods__ for discovering need finding, ideation and prototyping of digital innovations
- __Case studies__ of digital innovation in industries
- __Theories__ that explain the mechanisms of digital innovations
:::

# Learning objectives

During this course, you should advance your skills in the following areas:

::: {.incremental}
- Enhanced __knowledge of various industries__ and their special characteristics 
- Understanding of _specifics of managing digital innovations_ in these industries 
- Knowledge of __theoretical models__ that help to explain and manage these innovations
- Ability to analyze specificities and complexities of different industries 
- Capacity to __adapt digital innovation management methods__ and tools accordingly
- Ability to __clearly communicate conclusions__ and the underlying rationale
- Ability to evaluate new information and to question existing assumptions
- Expertise to __develop independent contributions__ to practical and theoretical discourse
:::

# Effort

You will gain 5 ECTS for this course. This equals approx. __150 hours workload__, of which you need most to pass the course.

::: {.incremental}
-	Live sessions (approx. 40 hours)
-	Preparation of the live sessions (approx. 20 hours)
-	Case research and writing (approx. 90 hours)
:::

::: {.fragment}
Please prepare your schedule accordingly.
:::

# Grading

The grade is based on the evaluation of the written case study (see [assignment](../assignment/)).

The presentations are mandatory but will not be graded individually.

# Schedule {.scrollable .smaller}

::: {.notes}
It is of importance that you prepare yourself for the sessions and work on the case study continually. Please prepare your schedule accordingly.
:::

::: {.column-page}

|Date        |Topic                                                                                   |Preparation      |
|:-----------|:---------------------------------------------------------------------------------------|:----------------|
|`03/15/2022`|Administrivia, introduction & patterns of innovation                                    |-
|`03/16/2022`|Washington Post — digital transformation in media (BM & Lean UX canvas)                 |Reading
|`03/17/2022`|Threadless.com — creating value through online communities (crowdsourcing)              |Reading
|`03/24/2022`|__Interim presentation & coaching__: ideas                                              |Presentation
|`03/31/2022`|Wieland — virtualizing product development; *guest speech* (digital twin)               |-
|`04/07/2022`|BVB — innovation in retail; *guest speech* (signaling theory) __ZOOM__                  |-
|`04/14/2022`|__Interim presentation & coaching__: problem & solution                                 |Presentation
|`04/21/2022`|SCHOTT — a two sided approach for DI (path constitution theory)                         |Reading
|`04/28/2022`|__Interim presentation & coaching__: industry & company                                 |Presentation
|`05/05/2022`|Deutsche Bank - innovation in finance, a safe bank? *guest speech* (ambidexterity)      |-
|`05/12/2022`|__Interim presentation & coaching__: approach                                           |Presentation
|`05/19/2022`|Springest —  IT-enabled holacratic organizations (self-managing organizations)          |Reading
|`06/02/2022`|__Interim presentation & coaching__: discussion                                         |Presentation
|`06/23/2022`|Final presentations                                                                     |Presentation
|`07/07/2022`|__Deadline case study__                                                                 |Assignment

: Schedule summer term 2022 (may be subjected to changes) {#tbl-schedule}

:::