---
title: "Assignment 📑"  
subtitle: "`SIM_1` Technology & Application Management (TAM)"
lang: en-US

bibliography: ../assets/literature.bib

format: 
  html:
    output-file: index.html
  presentation-revealjs:
    date: "Winter Term 2022/23"
    output-file: slides.html 
    include-before-body: ../assets/footer.html  
---


# Task

Imagine you are part of the __young leadership development program__ at ACME Inc., a large, multinational company with multiple business lines. 

. . .

Your task is to create a __management concept__ that tackles the challenges and, once implemented, improves the way technology and application is managed within the company within two years and, thus, its output significantly (i.e., IT management).

. . .

You will develop the concept in a __sprint-based approach__ (approx 10 weeks, focused, multiple feedback-loops) and then present it to the board. You will also hand-in a comprehensive documentation of your proposal (i.e., seminar paper).

. . .

The winner will become a position in the IT mangement team and placed on the succession track for the existing CIO.

## Company

ACME Inc and its IT unit can—in a nutshell—be characterized as follows:

::: {.incremental}
- Approx. 8,000 employees worldwide; approx. 120 within global IT
- Three business units; two operating in process production, one forward-integrated (discrete production)
- Centralized IT, most parts located in the HQ, local staff to ensure operation 
- Monolithic core technology for the legacy business in Europe (approx. 50%)
- Operation of core technologies and infrastructures in two large data centers
- 24 million IT budget (approx. 70 % staff, 10 % infrastructure, 20 % applications)
- Approx 50% of IT capacity planned for projects (mostly run the business); covers only 20% of business demands
:::

## Challenges

The company has difficulties to realize the value they expect from their IT, among others due to

:::{.incremental}
- Corporate IT struggles with responding fast to changing business demands
- Both shadow IT and legacy technologies and applications pose major continuity and security risks
- Due to many (large) acquisitions, the company uses many redundant core systems (ERP, MES, CRM) and presumably countless systems on the periphery
- IT resources are mainly dedicated for running the business
- Runaway technology projects paralyze both operational efficiency and growth
- The company has repeatedly relied on inferior technologies and applications that are now costly and difficult to replace
- As IT governs only its own spending and performance, the company struggles a lot with (unsupported) shadow IT
:::

## Approach

You will adopt an agile approach to create the management concept. Andy Weeger, the CEO of ACME Inc. will act as a product owner and help you to understand and analyze the problem thoroughly. You just have to ask the right questions during the PO Q&As (as often in life ;-)

. . .

Your work will be structured in three phases (i.e., sprints)

. . .

:::{.html-hidden .incremental}
- __Sprint 1:__ problem understanding and approach to tackle the main problems
- __Sprint 2:__ detailed description of the selected tools/methods incl. application
- __Sprint 3:__ finishing up the tools, summary of the approach, and discussion
:::

. . .

In addition, you need to create lessons learned of the learning process.

. . .

:::{.notes}
- The __first phase__ is focused on problem understanding, the development of an overarching framework that tackles the main problems as well as selecting and interrelating efficient tools
- The __second phase__ is focused on elaborating the selected tools/methods, describing them and applying them exemplarily. Best case, you also develop an artefact that supports application (e.g., an Excel tool)
- The __third phase__ is focused on the refinement and wrap-up. You work out the relationship of the methods to the problems and goals in detail. In addition, you give an outlook on how the management concept can be extended or improved in the future.

Last not least, I expect you to extract your lessons learned and briefly discuss them.
:::

The management concept should help the organization to manage technologies and application efficiently, i.e. to align organization and technology, reduce friction, and chart future transformation journeys

# Deliverables {.vertical-center background-color=grey background-image="images/bg.jpeg"}

## Paper

The final artefact/product (i.e., seminar paper) needs to include following elements:

. . .

:::{.incremental}
- Management summary
- Comprehensive problem statement and goals
- Overview of framework (areas, tools, interrelations)
- Detailed presentation of the management tools
- Summary and discussion
- Appendix: Glossary (definitions of main terms/concepts, establishes a common language), lessons learned
:::

:::{.notes}

#### Framework

Your management concept will not solve all problems at once. However, a comprehensive management approach that cleverly links the processes and outcomes of the proposed tools will accelerate ACME Inc.'s journey toward strong IT business value realization. 

The framework answers questions concerned with what ACME Inc. needs to focus on to improve the value of technologies and applications deployed.

It is your task to create such a framework, which effectiveness is easily understandable by the CEO and connects technology and applications and the business.

The framework should describe the overarching goal(s) and/or goal cascade, the principles, focus areas (i.e., the sociotechnical elements your approach tackles to achieve the goals), and the management tools that you propose.

To create your management framework, you need

- a __comprehensive understanding of the core problem__ (these might differ from group to group, there is no single correct problem statement). This requires you to cut the elephant into pieces.
- a good __overview of exiting frameworks__ and management methods to synthesize a lean model that tackles your problem statement

#### Management tools

In the management tool section the methods that you propose are presented in greater detail. 

As your framework provides answers about **what needs to be done**, the tool section outlines **how management of technologies and applications should be organized**.

As to that you introduce the method that ACME should use in a way that both business and IT managers can comprehend. You also show by means of a (fictional) example that relates to ACME (ask the CEO for details and what assumptions can be made) how the method is being applied (e.g., the specific tools used, the roles required, the outcomes achieved). You also reflect about the strenghts and weeknesses of the method.

For instance, it could be reasonable that you suggest implementing an approach to improve enterprise architecture. Then you should explain what enterprise architecture management is and how you suggest ACME Inc. should implement it. Depending on the problem statement, you will find different aspects of EAM useful. It's up to you to recommend and describe the right ones.

:::

## Status reports

There are three review sessions during the semester where you will present your interim results to all students and get feedback from me and the others (status review meetings). 

. . .

Prepare for a **casual but focused meeting** to take stock of the situation, including an informal document suitable to present the current state of your management approach and any outstanding issues on which you need input.

. . .

If needed, we can schedule brief, individual stand-up meetings after the P&O Q&A.

. . .

For dates please see the [schedule](../0/index.html#schedule)

# Evaluation criteria

An __excellent management concept__ has the following characteristics 

::: {.incremental .smaller}

- The management summary gives a good overview and makes the reader want to read further
- The concept establishes a language that is understandable by business and IT executives
- The problem is worked out well and comprehensibly presented
- The goals are comprehensible and reachable within two to three years
- The framework clearly shows what needs to be done and how the fields and methods are interrelated
- The presentation of the methods shows why these are proposed and how problem-solving is accelerated
- It is totally clear how the methods should be implemented
- The tools can realisticly become effective within two years
- Lessons learned and outlook is comprehensible
- There are very few errors, the writing is clear, and easy to read and engaging
- The concept is not plagiarism (e.g., strong own contribution and citations where applicable)
:::

# Formal requirements

__Seminar paper__

::: {.incremental}
- Use the template offered [here](assets/TAM_ManagementConcept_Template.docx) 
- The seminar paper should be at least 8 pages, but not exceed 14 pages (excl. title, indexes and appendix)
- The paper must be uploaded as PDF (Moodle)
:::

. . .

__Final presentations__

Imagine it is a competitive pitch and you want to convince the board with your concept.

:::{.incremental}
- Presentation of the concept in front of the board (10 minutes max.)
- Q&A (3 minutes)
- No formal requirements on the slides
:::

# Q&A {.html-hidden .unlisted .vertical-center  background-color=grey background-image="images/bg.jpeg"}