---
title: "Topics"
subtitle: "IT as a Service Enabler (ITSE)"

bibliography: ../assets/literature.bib

date: 02.29.2024

format: 
  html:
    output-file: index.html
    margin-header: | 
      [Slides](slides.html){.btn .btn-primary target="blank"}
    format-links: false
  presentation-revealjs:
    output-file: slides.html 
    include-before-body: ../assets/footer.html  
---


# Overview

**General remark:** When you work on the topics, your ambition should be to produce a solid scientific paper (good way to prepare for the bachelor thesis)

. . .

Topics:

:::{.incremental}
- Cyber security for industrial IoT (IIoT) *(structured literature review)*
- Gamification as a strategy to promote sustainable behavior *(structured literature review)*
- Models of human-AI collaboration in decision-making *(structured literature review)*
:::

## Cyber security for industrial IoT (IIoT) — Threats and countermeasures

IT/OT convergence is manifested in and driven by the industrial IoT (IIoT). This convergence leads to the emergence of specific and evolving cyber security threats which appear to be challenging to address.

To provide an overview of the academic knowledge on these emerging threats, you will conduct a structured literature review in form of a "narrative review" following @webster2002analyzing and @xiao2019guidance.

You will synthesize the knowledge on specific and evolving threats as well as countermeasures to these (theoretical contribution) and develop management recommendations that help practitioners to mitigate risks (practical contribution).

Use the *Web of Science* and this [query](https://www-webofscience-com.ezproxy.hnu.de/wos/woscc/summary/75992ba7-644d-4138-8108-250bf2fe9b36-a55737c1/relevance/1) to identify the initial set of papers.

## Gamification as a strategy to promote sustainable behavior

Today, our lives resemble games more than ever. Games are everywhere, and many activities, systems, and services have adopted gamification. Gamification refers to designing information systems to afford similar experiences and motivations as games do, and consequently, attempting to affect user behavior [@koivisto2019rise].

To provide an overview on what is known about the effects of gamification on sustainability, you will conduct a structured literature review in form of a "narrative review" following @webster2002analyzing and @xiao2019guidance.

You will analyze existing literature, provide an overview of the academic knowledge on the potential of gamification to influence awareness and intentions to perform sustainable behavior and synthesize the findings into guidelines that inform the development of gamified information systems to promote sustainability.

Use the *Web of Science* and this [query](https://www-webofscience-com.ezproxy.hnu.de/wos/woscc/summary/62f3659f-72f9-4e39-9a36-c60aae4eade2-a557b802/relevance/1) to identify the initial set of papers.

## Models of human-AI collaboration in decision-making

Organizations and individuals are increasingly facilitating human-AI collaboration. Still empirical and anecdotal evidence shows that many attempts of human-AI collaboration are not yet realizing their full potential, e.g., low trust or limited understanding reduce compliance with recommendations provided by  AI systems [@westphal2023decision].

To provide an overview on what is known about human-AI collaboration in decision-making, you will conduct a structured literature review in form of a "narrative review" following @webster2002analyzing and @xiao2019guidance.

You will analyze existing literature, provide an overview of different modes of human-AI collaboration in decision-making and synthesize factors that effect the realization of the potential of the collaboration.

Use the *Web of Science* and this [query](https://www-webofscience-com.ezproxy.hnu.de/wos/woscc/summary/ba15234c-42ca-4bba-b992-6013303c08c3-a558eda9/relevance/1) to identify the initial set of papers.


# References
::: {#refs}
:::