---
title: "Elevator Pitch"
subtitle: "Was ist das nächste große Ding?"
lang: de-DE

bibliography: ../assets/literature.bib

format: 
  html:
    output-file: index.html
  revealjs:
    output-file: slides.html 
    include-after-body: ../assets/footer.html
---

# Top {visibility="hidden" .slide-link-hidden .unlisted .unnumbered}

<!-- LTeX: language=de-DE -->

[Präsentation](slides.html)[^print]

{{< include ../assets/_version.qmd >}}

# Elevator Pitch {.vertical-center background-color=blue background-image="images/bg.jpeg"}

Sie erbringen eine Kurzpräsentation in Form eines __Elevator Pitches__[^1] zu einem aktuellen und relevanten Thema im Kontext des digitalen Unternehmens.

## Setting {visibility="hidden"}

[^1]:Der Begriff Elevator Pitch bezeichnet eine Methode, mit der eine Idee innerhalb kürzester Zeit überzeugend präsentieret wird. Es geht darum einer Person im Aufzug (auf Englisch: elevator) während der gemeinsamen Fahrt für die Idee zu gewinnen. Angesichts der Kürze der Zeit ist es wichtig, relevante Informationen so komprimiert und überzeugend zu vermitteln, dass das Gegenüber begeistert wird. [@denning2012myth]

:::{.notes}
Stellen Sie sich vor, Sie arbeiten in einem größeren Unternehmen Ihrer Wahl und treffen Ihren CEO im Fahrstuhl. Sie nutzen die Gelegenheit, „Ihr Thema“ dem CEO zu präsentieren und ihn davon zu überzeugen, dass sein Unternehmen in Ihr Thema (Zeit) investieren sollte.

Bis der Fahrstuhl in der Vorstandsetage angekommen ist, haben Sie max. 7 Minuten Zeit. In dieser Zeit müssen Sie den CEO von der Relevanz des Themas überzeugen. Das machen Sie am besten, indem Sie kurz in Ihr Thema einführen und dann möglichst konkret zeigen, wie Ihr Thema zum Unternehmenserfolg nachvollziehbar beitragen könnte.

[Hier](https://blog.hubspot.de/sales/elevator-pitch) finden Sie weitere Tipps zur Vorbereitung Ihres Elevator Pitches.
:::

## Rahmenbedingungen 

:::{.incremental}
- Länge mindestens 4 Minuten, maximal 5 Minuten
- Überzeugende Vorstellung des Themas
  - allgemeinverständliche Einführung in das Thema   
    *("was ist es und weshalb ist es wichtig?")*
  - Vorschlag *eines* Anwendungsfalls zur Thematik  
    *(wie können wir damit erfolgreich sein?)*
- Die Termine entnehmen Sie dem [Zeitplan](../0/#tbl-schedule)
:::

:::{.notes}
Mit Ablegen der Präsentationsprüfung versichern Sie, dass Sie die Prüfungsleistung ohne fremde Hilfe vorbereitet haben. Bereits der Versuch, das Ergebnis der Arbeit durch Täuschung (z.B. durch Mithilfe Dritter, auch Kommilitonen) zu beeinflussen kann zum Nicht-Bestehen der Leistung führen.
:::

## Themenwahl

Sie suchen sich ein Thema aus einer Liste an möglichen Themen aus (siehe [Moodle](https://elearning.hnu.de/mod/choice/view.php?id=557838), verfügbar am Tag der Themenausgabe).

:::{.incremental}
- Jedes Thema kann nur einmal vergeben werden
- Die Vergabe erfolgt nach dem Prinzip „First come, first serve“
- Die Wahl ist fix, kann nicht geändert werden
:::

## Präsentation

Den Termin zur Präsentationsprüfung entnehmen Sie dem [Zeitplan](../admin/#tbl-schedule).

:::{.incremental}
- Während der Präsentationsprüfung sprechen Sie frei
- Andere Hilfsmittel wie bspw. Notizen sind nicht erlaubt
- Die Zeit ist fix, die Präsentation dauert min 5, maximal 7 Minuten.   
  *Verschwenden Sie keine Zeit. Üben sie vorher.*
- Der CEO kann am Ende der Präsentation Fragen stellen.
:::

# Q&A {.vertical-center background-color=blue background-image="images/question.jpeg" .unlisted .html-hidden}