---
title: "Administratives 🧐"
subtitle: "`DEM_1` DE1: Digitalisierung und Informationssysteme"
lang: de-DE

bibliography: ../assets/literature.bib

format: 
  html:
    output-file: index.html
    margin-header: | 
            [Slides](slides.html){.btn .btn-primary}
    format-links: false     
  presentation-revealjs:
    output-file: slides.html 
    include-before-body: ../assets/footer.html
---

# Allgemeines

Im Modul Digital Enterprise 1 erhalten Sie eine Einführung in viele wichtige Konzepte der Wirtschaftsinformatik (WI). 

Wenn Sie die Inhalte der Vorlesung wiederholen möchten, dann besuchen Sie die Vorlesung [Grundzüge Informationsmanagement (IMUK)](/lectures/GIM/23ST/admin).

## Prüfungsleistung

Die Vorlesung wird anhand einer __Portfolio-Prüfung__ bewertet

:::{.incremental}
- Die Portfolio-Prüfung besteht aus vier unterschiedlichen Teilen:
  - __10 Quizze__ (variierende Bearbeitungszeit, 20 Punkte)[^2]
  - __Übungsblatt__ (ca. 2 Tage Bearbeitungszeit, 25 Punkte)
  - __Klausur__ (45 Minuten Bearbeitungszeit, 45 Punkte)
- Die Gesamtzahl der in diesem Kurs erreichbaren Punkte beträgt 90. Sie benötigen __45 Punkte zum Bestehen__.
:::

[^2]: Baut auf den Inhalten der Vorlesung [Grundzüge Informationsmanagement (IMUK)](/lectures/GIM/23ST/admin) auf. Bitte beachten Sie, dass die Quizze nur innerhalb eines definierten Zeitraums (variiert pro Quiz, siehe Moodle) absolviert werden können.

## Zeitplan {.scrollable .smaller}

| Datum        | Prüfungsteil                            |
|:-------------|:----------------------------------------|
| `27.04.2023` | Quizze K1-K6
| `04.05.2023` | Quiz K7
| `11.05.2023` | Deadline Quiz K8
| `25.05.2023` | Übungsblatt (online, ca. 13 Uhr)
| `26.05.2023` | Deadline Übungsblatt 
| `15.06.2023` | Quiz K9
| `22.06.2023` | Quiz K10
| `29.06.2023` | Quiz K11
| `06.07.2023` | Quiz K12

: Zeitplan Sommersemester 2023 (Änderungen vorbehalten) {#tbl-schedule}

# Literatur 📚
::: {#refs}
:::