---
title: "Architecture"  
subtitle: "How to get a holistic view and approach of technologies and applications across an entire enterprise?"
lang: en-US

bibliography: ../assets/literature.bib

format: 
  html:
    output-file: index.html
  revealjs:
    date: "Winter Term 2022/23"
    output-file: slides.html 
    include-after-body: ../assets/footer.html
---

# Top {visibility="hidden" .slide-link-hidden .unlisted .unnumbered}

{{< include ../assets/_top.qmd >}}

# Motivation {.vertical-center background-color=blue background-image="../assets/bg.jpg"}

> The Enterprise Architecture (EA) function is a core element of the foundation that both enables and accelerates the tech transformation that companies need in order to compete in a digital-first world. *KcKinsey & Company*

# Introduction {.vertical-center background-color=blue background-image="../assets/bg.jpg"}

## Definition

> Enterprise Architecture is a discipline that manages the fundamental organization of an enterprise, which is embodied in its components, their relationships to one another and the
environment, and the principles that govern its design and evolution. *ISO/IEC/IEEE 42010:2011*


## Need

> XY *XY*

## Definition

## Benefits of EA

## Let's discuss {.html-hidden .unlisted .unnumbered .vertical-center background-color=blue background-image="../assets//bg.jpg"}

# Example: TOGAF {.vertical-center background-color=blue background-image="../assets/bg.jpg"}

## Introduction

# Q&A {.html-hidden .unlisted .vertical-center background-color=blue background-image="../assets/bg.jpg"}


# Literature

:::{.refs}
:::