---
title: "Administratives 🧐"
subtitle: "`DEM_1` DE1: Digitalisierung und Informationssysteme"
lang: de-DE

format: 
  html:
    output-file: index.html
---

# Aufgabenstellung 🧐 {visibility="hidden"}

Bearbeiten Sie __selbstständig__ (ohne Abstimmung in der Gruppe und ohne die Verwendung generativer AI) folgende Aufgaben.

## Aufgabe 1 (6 Punkte)

Beschreiben Sie das Unternehmen [Uber](https://uber.com) anhand des Business Engineering Modells. Nutzen Sie zur Unterstützung Ihrer textlichen Erläuterungen die grafische Darstellung des Business Engineering Modells und erweitern Sie diese um die Spezifika des Unternmehmens.

## Aufgabe 2 (4 Punkte)

Erläutern Sie anhand des Beispiels aus Aufgabe 1, was man im Allgemeinen unter Modellierung versteht und welchen Nutzen dieses Vorgehen bietet.

## Aufgabe 3 (5 Punkte)

Erläutern anhand des Beispiels von [Uber](https://uber.com) zwei der fünf [Stufen der digitalen Transformation](/lectures/DE1/22WT/2/#Stufen).

## Aufgabe 4 (5 Punkte)

Ein Online-Shop möchte den Bestellprozess verbessern und hat Sie als Digital Enterprise Manager:In damit beauftragt, den aktuellen Bestellprozess zu modellieren und mögliche Verbesserungen zu identifizieren. Der aktuelle Bestellprozess besteht aus den folgenden Schritten:

1. Der Kunde wählt die Produkte aus und legt sie in den Warenkorb.
2. Der Kunde gibt seine Rechnungs- und Lieferadresse ein.
3. Der Kunde wählt die Zahlungsmethode aus.
4. Der Kunde bestätigt die Bestellung.
5. Das System sendet eine Bestellbestätigung an den Kunden.

Erstellen Sie ein eEPK-Diagramm (erweiterte Ereignisgesteuerte Prozesskette) für den aktuellen Bestellprozess. Verwenden Sie mindestens ein AND-Verknüpfung, mindestens ein XOR-Verknüpfung, mindestens ein OR-Verknüpfung sowie mindestens zwei Objekte der eEPK.

#### Hinweise 

- Sie können Annahmen treffen. Dokumentieren Sie die Annahmen.
- Die Annahmen sollten es Ihnen ermöglichen, die Anforderungen dieser Aufgabe zu erfüllen UND Aufgabe 2 vorzubereiten.
- Achten Sie darauf, Ereignisse, Funktionen und Verbindungen in Ihrem EPK-Diagramm korrekt zu benennen und zu beschriften.
- Betrachten Sie den Bestellprozess aus der Perspektive des Kunden 
- Stellen Sie sicher, dass alle relevanten Schritte und Aktionen in Ihrem Diagramm abgebildet sind.

## Aufgabe 5 (5 Punkte)

Identifizieren Sie nun mögliche Verbesserungen für den Bestellprozess. Zeigen Sie, wie sie den Bestellprozess optimieren können und begründen Sie die Vorteile der vorgeschlagenen Änderungen.

#### Hinweise:

- Verwenden Sie bitte die konventionelle Notation.
- Bei Bedarf können Sie Annahmen treffen. Dokumentieren diese in Ihrem ERM und erläutern Sie diese separat.

### Hinweise

- Das Relationenmodell soll in Form von Tabellen mit Spaltennamen dargestellt werden.

# Abgabe

Legen Sie für jede Aufgabe eine DIN A4 Seite an. Ergänzen Sie im Kopfbereich aller drei Seiten folgende Informationen: „DEM1 DE1, Sommersemester 23, Prüfungsleistung Übungsblatt“, Ihren vollständigen Namen, Ihre Matrikel-Nummer und die Bezeichnung der Aufgabe. Wenn Sie handschriftlich gearbeitet haben, fotografieren Sie alle Seiten und erstellen ein PDF. Wenn Sie am PC gearbeitet haben, erstellen Sie direkt ein PDF. Das PDF mit den Lösungen zu allen Aufgaben laden Sie als Ergebnis in Moodle hoch. Abgabefrist siehe Hinweise im Moodle-Kurs.

Bei Abgabe der Prüfungsleistung versichern Sie, dass Sie die eingereichte Prüfungsleistung ohne fremde Hilfe verfasst haben (inkl. generativer AI). Ihnen ist bewusst, dass bereits der Versuch, das Ergebnis der Arbeit durch Täuschung (z.B. durch Mithilfe Dritter, auch Kommilitonen) zu beeinflussen, zur Bewertung 5,0 („nicht ausreichend“) bzw. „nicht bestanden“ führen kann“.