---
title: "Kurzpräsentation"
subtitle: "`DEM_1` DE1: Digitalisierung und Informationssysteme"
lang: de-DE

bibliography: ../assets/literature.bib

date: "10.24.2023"
format: 
  html:
    output-file: index.html
---

# Zielsetzung {visibility="hidden"}

Durch die Vorbereitung und Präsentation einer Präsentation zu einem Thema, mit dem sich digitale Unternehmen heute beschäftigen müssen, zeigen Sie, dass Sie in der Lage sind,

::: incremental
-   **Grundkonzepte der WI** zum Digitalen Enterprise und der Umwelt benennen und anhand eines Beispiels zu erläutern,
-   interne und externe Treiber sowie die Potenziale der **Digitalisierung von Unternehmen und Märkten** benennen und deren Zusammenhänge erklären und
-   Zusammenhänge zu erfassen, auf den Punkt zu bringen und für andere verständlich zu erklären
:::

# Prüfungsleistung

Sie erstellen in einer Kleingruppe eine **Kurzpräsentation** zu einem aktuellen Thema und zeichnen diese auf Video auf.

Die Präsentation hat zum Ziel, das Thema kurz, prägnant und inhaltlich richtig zu erläutern. Zudem müssen Sie das Konzept mit den Lernzielen der Vorlesung verknüpfen und diese anhand des Beispiels zu vertiefen. Jedes Thema ist deshalb einem Kapitel der Vorlesung zugeordnet.

::: small
Beispiel: Sie entscheiden sich für das Thema *Crowdsourcing*. Das Thema ist dem Kapitel Geschäftsmodelle zugeordnet. Dann könnten Sie anhand eines Crowdsourcing-Anbieters dessen Geschäftsmodell analysieren und vorstellen und somit das Wissen zu den Dimensionen von Geschäftsmodellen vertiefen.
:::

**Weitere Rahmenbedingungen**

-   Sie wählen das Thema per Moodle aus, jedes Thema kann von **bis zu 3 Studierenden** gewählt werden. Alle Studierenden, die dasselbe Thema gewählt haben, bilden eine Gruppe und **arbeiten gemeinsam an einer Präsentation**. Sind alle Themen vollständig vergeben, können ausgewählte Themen auch von bis zu 4 Studierenden bearbeitet werden. Die Vergabe erfolgt dann durch den Dozenten.
-   Sie organisieren sich in den Gruppen selbst und tragen Sorge dafür, dass jedes Gruppenmitglied gleich zur Prüfungsleistung beiträgt.
-   Die Kurzpräsentation muss **zwischen 6 und maximal 8 Minuten** lang sein.
-   Die Vorbereitungszeit beträgt ca. 2,5 Wochen. Sie können maximal 25 Punkte erzielen.
-   Das Video muss nicht geschnitten sein. Wenn Sie möchten, können Sie auch einen One-Shot per Handy aufzeichnen.
-   Das Video muss in einem lesbaren Format (Codec) rechtzeitig via Moodle hochgeladen werden (Deadline siehe [Zeitplan](../admin/#zeitplan)).
-   Die Videos werden in der Vorlesung gezeigt und inhaltlich besprochen.

# Themen

| **Kapitel**         | **Themen**                |                        |                      |     |
|---------------------|--------------------------|------------------------|----------------------|-----|
| `K1` Einführung          | Bullwhip-Effekt          | Data Lake              |                      |     |
| `K2` Digitalisierung     | Location-based Services  | Metaverse              | Mixed Reality        |     |
| `K3` Technologie         | Edge Computing           | 5G                     | Serverless Computing |     |
| `K4` Informationssysteme | Cyber-Physical-Systems   | Digital Twin           | IoT                  |     |
| `K5` Prozesse            | Process Mining           |                        |                      |     |
| `K6` Integration         | RPA                      | Enterprise Service Bus |                      |     |
| `K7` Anwendungssysteme   | Automatisierungs-Pyramide |                        |                      |     |
| `K9` Implementierung     | LCDP                     | SAFe                   |                      |     |

# Evaluationskriterien

-   **Inhalt:** das Thema wurde sachlich richtig vorgestellt
-   **Zusammenhänge:** die Verknüpfung zu den Lernzielen ist gut herausgearbeitet
-   **Lerneffekt:** die Präsentation erhöht das Verständnis des Vorlesungsstoffs
-   **Struktur:** ein roter Faden ist klar erkennbar und dient dem Verständnis
-   **Visualisierung:** die visuelle Darstellung ist aussagekräftig und zweckdienlich
-   **Kreativität:** die Präsentation überträgt den Inhalt in einer geschickten Form
-   **Sprache/Haltung:** die Vortragenden sind verständlich, sprechen angemessen, unterstreichen die Inhalte durch geeignete Stilmittel sowie Gestik und Mimik und wecken Interesse am Thema

# Q&A {.unlisted .html-hidden background-color="lightgrey" background-image="images/question.jpeg"}
