---
title: "Handwerkskammer Ulm"  
subtitle: "Business Challenge 01 — Learning Journey"
lang: en

author: "Andy Weeger"

date: "03.05.2024"

bibliography: ../assets/literature.bib

format: 
  html:
    output-file: hwk.html
---


# General Briefing

Handwerkskammern (Chambers of Skilled Crafts, HWKs) are corporations under public law that represent the interests of the skilled crafts sector in Germany. They are organized in all 16 federal states and have a total of around 530,000 member companies.

The main tasks of the HWKs are (1) to regulate admission to the skilled trades, training (e.g., inter-company vocational training) and further education (e.g., "Handwerksmeister"), (2) to represent the interests of the skilled trades towards politicians and authorities, and (3) to offer their member companies a wide range of services, e.g. advice on business management and legal issues, support in the search for skilled workers and further training opportunities.

Digitalization is a major challenge, but also a great opportunity for the chambers of skilled crafts. The chambers that successfully digitalize themselves will be better positioned in the future to represent the interests of the skilled trades and support skilled trades businesses in overcoming the challenges of digitalization. Summarizing it well, Dr. Tobias Mehlich, the managing director of the HWK Ulm, expects digitalization to generate a higher  "Glücksrendite" (happiness yield) for skilled crafts businesses.

#### Advantages of digitalization for the chambers of skilled crafts:

- Increased efficiency
- Improvement in service quality
- Strengthening competitiveness

#### Challenges of digitalization for the chambers of skilled crafts:

- Need for investment
- Qualification of employees
- Changing the corporate culture
- Data protection and IT security

# Challenge

Regarding training and further education (e.g., management or specialist technical courses), the HWKs expect increasing competition from private providers, particularly online providers offering a wide range of training courses in the field of vocational training. These offerings can range from short webinars to comprehensive online courses. 

To date, the HWKs still have competitive advantages like strong practical relevance (practical training that is tailored to the needs of skilled crafts companies), broad experience (particularly regarding vocational training), and reputation, that need to be further expanded and exploited by means of digital technology. Likewise, the challenges of digitialization need to be addressed.

To achieve that, the HWK Ulm is looking for **innovative solutions to improve the learning experience of apprentices and professionals** so that they can offer first-class training in the field of vocational education and further strengthen our competitiveness in this area. The key question therefore is:

> How can the vocational training for apprentices and professionals through innovative digital services and solutions be improved?

By tackling specific unmet needs of the relevant stakeholders such as learners,  craft businesses, instructors, product developers and customers of the craftsmen with innovative, data-driven digital solutions, significant progress towards improving vocational education can be made. To achieve this, the HWK Ulm has identified the following critical opportunity areas for innovation:

- **Learning journey** of apprentices and professionals (e.g., providing personalized learning paths, utilizing virtual environments)
- **Quality management** (e.g., utilizing real-time feedback to enhance the efficiency and quality of training and learning contents)
- **Product development process** (e.g., seizing market trends and learner preferences)
- **Marketing strategies** for educational products (e.g., enhanced understanding of the target audience, utilization of new channels)

If you have different ideas and directions that you want to pursue, either check-in with the professors and the contact persons of the HWK.

## Mandatory questions

Following questions should definitely be answered as part of your concept and addressed by your MVP

- What unmet need(s) for the involved stakeholders have you identified in the field of vocational training?
- How does your solution address the identified unmet need(s)? 
- What is the potential impact (i.e., business value) of your solution on the "happiness yield" of skilled crafts businesses?
- How does the MVP proof your concept, particularly value creation and feasibility?
- What should the go-to-market strategy/implementation approach be for your solution?

## Requirements

Measure of impact
: It is essential to introduce a measure of how the solution will enhance the competitiveness of the HWK Ulm.

Target key stakeholders
: The solution should take into account the most important needs and concerns of the key stakeholders.

Not just technology
: Participants should not only focus on technological solutions but also show how the solution integrates with existing processes and resources to create maximum value. 

Technology
: The proposed solution should be mostly based on open source technology (low investment)

Privacy
: The proposed solution needs to meet data protection requirements and provide users with a secure and trusted environment.


## Goals and outcome

The aim is to propose an innovative digital solution that can be implemented at the HWK Ulm within a few months and to proof the concept by means of a MVP. If the proof of concept is successful, there is the opportunity to present the concept at the Chamber of Skilled Crafts and, ideally, to continue the development after completion of the module.

# Knowledge base

Details about the HWK Ulm an their services can be found online ([https://www.hwk-ulm.de/](https://www.hwk-ulm.de/)). Unfortunately, the website is only available in German, please use a translator like Google translate.

In addition, Ralf Rotzek, head of training academies division and member of the board, will be happy to answer specific questions. Dates will be announced asap.