---
title: "Wilken Software Group"  
subtitle: "Business Challenge 03 — Psychological Help"
lang: en

author: "Andy Weeger"

date: "03.11.2024"

bibliography: ../assets/literature.bib

format: 
  html:
    output-file: wilken.html
---


# General Briefing

Mental health problems are a widespread issue in Germany. According to the Robert Koch Institute's Mental Health Surveillance Report, the mental health status of Germans is deteriorating considerably. In 2022, around 20% reported a noticeable burden of depressive symptoms. This means that this proportion has almost doubled compared to 2019. The deterioration in mental health is evident in all gender, age and education groups. education groups.

This trend also impacts the economy. In 2023, absences due to mental illness reached a new high in Germany. In a ten-year comparison, employee absences increased by 54 percent. On average, sick leave due to mental illness lasted 32.2 days.

The most common mental illnesses in Germany are:

- **Anxiety disorders:** Around 7.3 percent of adults in Germany experience an anxiety disorder.
- **Depression:** Approximately 5.3 percent of adults in Germany have depression.
- **Substance use disorders:** An estimated 4.5 percent of adults in Germany struggle with a substance use disorder.

Mental health conditions can significantly impact the quality of life for those affected. They can lead to difficulties in family life, work, and social interactions. In some cases, they can even contribute to suicide.

The good news is that mental health problems are usually treatable. Various therapies can help alleviate symptoms and improve the quality of life for those struggling. However, people should seek professional treatment at an early stage. 

For this reason, there are facilities that offer professional support to people in difficult life situations, so called  social psychiatric service ("Sozialpyschatrischer Dienst") and psychological counseling centers ("Psychologische Beratungszentren"), operated by various social economy organizations. In addition, psychiatric and psychosomatic outpatient clinics, specialized counseling centers (e.g., KEINE MACHT DEN DROGEN Gemeinnütziger Förderverein e. V.) as well as specialists and psychotherapists offer personal crisis talks and refer to further support services if necessary. Last not least, online offers are increasing (e.g., [HelloBetter](https://hellobetter.de/))

The counseling is usually confidential. The cost of counseling can vary. Some counseling centers offer free counseling, while others charge fees, which may be based on the income.

# Challenge

Wilken Software Group is a Ulm-based software company that develops and sells ERP systems and related solutions based on their P/5 platform. Wilken is specialized on utilities, health & insurance, social economy, churches and tourism. Wilken is aiming extending their portfolio by innovative digital solutions for their customers, particularly within the social economy.  They motivate their people to think outside the box and to come up with clever and unconventional ideas that solve real problems.

Wilken has identified a general problem in the social and healthcare sector, namely the difficulty of finding a provider of social or healthcare services that is perfectly matched to the individual's needs in a simple and low-threshold manner. 

This problem crystallizes in a special way in psychological counselling. For those seeking help, it is difficult to find the ideal provider quickly and easily with low-threshold. There are just to many different providers (e.g., Caritas, Diakonie, large employers) of psychological counseling in Germany, offering different counseling services at different conditions and often focusing on specific mental health problems or illnesses (e.g. addiction, sexuality) or on a specific population group (e.g. psychological counseling for students). 

The key question therefore is:
 
> How can digital technology be used to facilitate the process of finding a perfect match psychological counseling provider? 

Wilken seeks for innovative digital solutions that, on the one hand, it enables the many offers to be displayed quickly and cost-effectively and, on the other hand, it enables those seeking help to find and contact a suitable provider quickly and easily. In addition, this platform could use other innovative approaches to lower the contact threshold and offer assistance that is not classified as therapy. The solution should also, if possible, not fall under the Medical Devices Act.

## Mandatory questions

Following questions should definitely be answered as part of your concept and adressed by your MVP

- What are unmet needs of parties involved in the process?
- How does your solution address the key requirements and unmet needs? 
- What are key characteristics of psychological problems and related counseling services?
- What data is available and can be used?
- How can the data be maintained?
- How can the challenges identified be addressed by means of digital technology?
- How can Wilken monetize the solution?
- What should the go-to-market strategy/implementation approach be for your solution?

## Requirements

Target key parties involved
: The proposed solution should take into account the most important needs and concerns of the key parties involved.

Value
: The solution needs to create value for all parties involved (e.g., people in need, providers, payers, Wilken)

Regulations
: The proposed solution need to comply with the relevant rules and regulations in the field (e.g., the Medical Devices Act)

Scalability
: The proposed solution should be scalable to other social and/or health services.

Data protection and security
: The proposed solution needs also to consider the security of the AI models and data used.

Technology
: The proposed solution should be mostly based on open source technology.


## Goals and outcome

The aim is to propose an innovative digital solution for facilitate the process of finding a perfect match psychological counseling provider that can be implemented within a few months and to proof the concept by means of a MVP. If the proof of concept is successful, there is the opportunity to present the concept at Wilken. This is also a great chance to show case yourself for a job after finishing the master program.

# Knowledge base

Details about Wilken an their services can be found online on their [Corporate Website](https://www.wilken.de).

Details about the help and treatment services for people with mental health problems can be found on  

- [Stiftung Gesundheitswissen](https://www.stiftung-gesundheitswissen.de/) (German only, pelase use a translator)
- [psychnet](https://www.psychenet.de/de/hilfe-finden/hilfesystem-im-ueberblick.html) (German only, pelase use a translator)
- On the websites of health insurances, e.g.. [Die Techniker](https://www.tk.de/techniker/gesundheit-und-medizin/behandlungen-und-medizin/psychische-erkrankungen-2019136?tkcm=ab) (German only, pelase use a translator)

In addition, Dennis Lettner are happy to answer specific questions. Dates will be announced asap.