---
title: "Assignments 📑"  
subtitle: "`MISC` Academic Writing (AW)"
lang: en-US

bibliography: ../assets/literature.bib

format: 
  html:
    output-file: index.html
  revealjs:
    output-file: slides.html 
    include-after-body: ../assets/footer.html  
---

# Top{visibility="hidden" .slide-link-hidden .unlisted .unnumbered}

{{< include ../assets/_top.qmd >}}

# Task

You will prepare a __proposal for your master's thesis__, thereby going through __a complete process of writing and publishing an academic paper__ (topic, strategy, narrative, review, revision, presentation).

. . .

You need to apply what you have leanred and create __multiple deliverables__. The deliverables are usually created during a writing and publication cycle. In addition, you get feedback from both, your peer students as well as the Professors.

. . .

The deliverables reflect your learning progress and are graded individually.


# Deliverables

You need to deliver following parts via Moodle:

:::{.incremental}
- __Extended proposal__ for your master thesis (details see [template](assets/AW_Proposal_Template.docx))
- __Review__ of a fellow student's proposal (details see [template](assets/AW_Review_Template.docx))
- __Revision__ of your proposal incl. __response letter__ (details see [template](assets/AW_ResponseLetter_Template.docx))
- __Presentation__ of the proposal (8 minutes topic, 2 minutes lessons learned)
:::

. . .

For deadlines, pelase see the [schedule](../admin/#schedule)

# Q&A {.html-hidden .unlisted .vertical-center  background-color=blue background-image="../assets/bg.jpg"}