---
title: "Topic choice"  
subtitle: "How to find a topic that creates momentum"
lang: en-US

bibliography: ../assets/literature.bib

format: 
  html:
    output-file: index.html
  revealjs:
    date: "Winter Term 2022"
    output-file: slides.html 
    include-after-body: ../assets/footer.html  
---

# Top {.slide-link-hidden .unlisted .unnumbered visibility="hidden"}

{{< include ../assets/_top.qmd >}}

# Motivation {.vertical-center background-color=blue background-image="...assets/images/bg.jpg"}

> I believe that the choice of research problem---choosing the phenomena we wish to explain or predict---is the most important decision we make as a researcher. We can learn research method. Albeit with greater difficulty, we can also learn theory-building skills. With some tutoring and experience, we can also learn to carve out large numbers of problems that we might research. Unfortunately, teasing out deep, substantive research problems is another matter. It remains a dark art. *@weber2003problem*

# Opening exercise {.vertical-center background-color=blue background-image="...assets/images/bg.jpg"}

Read the [MISQ editorial](assets/MISQ-Editorial_2003_ProblemOfTheProblem.pdf) of @weber2003problem and summarize what you have learned about the challenge of choosing a topic for your research (approx. 20 minutes).

# Introduction

@weber2003problem characterizes doing research in terms of three activities:

::: incremental
1)  Describing some **phenomena** that we perceive in the world
2)  articulating a **theory** to account for the phenomena; and
3)  **testing** how well the theory accounts for the phenomena.
:::

. . .

In this course, we will not focus on the skills required for good research design or theory-building, rather we focus on __telling a relevant story__.

. . .

How relevant the story is, is defined in the __first phase of research__, which is about describing those phenomena that you perceive in the world that you wish to explain or predict.

:::{.notes}
We will discuss some criteria and tools that may help you to find and chose a phenomena that creates momentum and is worth to devote your scarce resources.
:::

# Effective topics

To select a topic you need to find an (1) *important problem domain* with (2) an *important phenomenon* that deserves attention from the research community and that relates to (3) an *important problem with the available knowledge*
about this type of phenomenon [@recker2021scientific, p. 36].

. . .

But what is the anatomy of a topic in information systems and management studies that creates momentum?

. . .

In an attempt to answer that question, @colquitt2011publishing put furth five distinct criteria for effective topics:

:::{.incremental}
- significance,
- novelty,
- curiosity,
- scope, and
- actionability
:::

##	Significance

__Taking on “grand challenges”__

:::{.incremental}
- Identify and confront or contribute to a “grand challenge”[^1]
- Tackle such problems in a particular literature or area if inquiry (i.e., slicing the elephant)
- Aim at a contribution that has theoretical usefulness and from which individual and societal benefit may accrue
- Take a bold and unconventional way that leaps beyond existing explanations (e.g., going behind conventional explanations)
- Articulate clearly how the study __solves a piece of a larger puzzle__ and how it moves the field
:::

. . .

*Example: @ferlie2005nonspread took on a grand challenge in asking why evidence-based innovations failed to spread in the health care industry*

[^1]:The grand challenges are large, important unsolved problem. Current grand challenges might be reflected by the United Nations Millennium Development Goals to eradicate global poverty, disease, and hunger.

## Think! {.vertical-center background-color=blue background-image="...assets/images/bg.jpg" .unlisted .unnumbered .html-hidden}

What "grand challenges" do you see?

In which area if inquiry could (your) research contribute to it?

## Novelty 

__Changing the conversation__

:::{.incremental}
- Consider whether your study changes the conversation that is already taking place in a given literature[^2]
- Aim at either adding momentum to a conversation or giving it a new direction
- Think of how you can generate new and creative solutions by exploring new domains and not to prefer the familiar, the mature and perspectives that are near to existing approaches (i.e., avoid the familiarity, maturity, and nearness traps)
:::

. . .

*Example: @agarwal2004knowledge focused on a new, under researched by investigating how knowledge capabilities of industry incumbents affected the generation, development, and performance of “spin-outs”*


:::{.notes}
:::{.callout-note}
#### Familiarity, maturity, and nearness traps
Familiarity trap
: Picking a topic that is too familiar and, thus, might only offer marginal extension of an existing conversation. ("familiarity trap")

Maturity trap
: Selecting a topic that is too mature and, thus, might only offer redundant contributions.
 
Nearness trap
: Choosing a topic that is too close to the existing literature and, thus, may only offer contributions that are not sufficiently different from existing perspectives.
:::
:::

[^2]:Adding to a conversation requires to know the conversation. Research topics (and research questions), thus, do not come out of the air, you need to read a lot.

## Think! {.vertical-center background-color=blue background-image="...assets/images/bg.jpg" .unlisted .unnumbered .html-hidden}

What strategies can you apply to identify a topic that that avoids the familiarity, maturity, and nearness traps?

## Curiosity

__Catching and holding attention__

:::{.incremental}
- Topics are interesting when their propositions counter a reader’s taken-for-granted assumptions (e.g., showing a seemingly good phenomenon to be bad)
- Try to identify and use surprising findings that cannot be explained by methodological issues or existing explanations (i.e., "breakdowns" that signal the potential existence of a mystery such as inconsistent findings)[^4]
- Try to reframe, reformulate or solve the "mystery"
:::

. . .

*Example: @van2009searing strived to solve the mistery of contradictory findings about the effects of leader displays of emotion. They studied whether team performance would be facilitated by leaders displaying happiness or by leaders displaying anger.*

[^4]: According to @colquitt2011publishing such topics arouse more interest than the more typical “gap-spotting” approach to generating research questions

## Think! {.vertical-center background-color=blue background-image="...assets/images/bg.jpg" .unlisted .unnumbered .html-hidden}

What are "mysteries" you have identified in your literature work?

##	Scope

__Casting a wider net__

:::{.incremental}
- Even the best topic ideas can be undermined if the resulting study is too small
- Studies cannot tackle grand challenges if they are not ambitious in scope
- Aim to fully and comprehensively sample the landscape in a given domain (i.e., relevant constructs, mechanisms, and perspectives) 
- You may may even include constructs and mechanisms derived by using multiple lenses
:::

. . .

*Example: @seibert2001social examine the effect of social capital on career success. They include all three theoretical perspectives on social capital that can explain why and how the characteristics of a personal social network can impact career success*

## Think! {.vertical-center background-color=blue background-image="...assets/images/bg.jpg" .unlisted .unnumbered .html-hidden}

What would be a relevant perspectives for your study?

## Actionability

__Offer insights for managerial or organizatoinal practice__

@mcgahan2007academic outline five major ways that management studies can be actionable:

:::{.incremental}
- Offering counter-intuitive insights
- Highlighting the effect of new and important practices
- Showing inconsistencies in and consequences of practices
- Suggesting a specific theory to explain an interesting and current situation
- Identifying an iconic phenomenon that opens new areas of inquiry and practice
:::

## Think! {.vertical-center background-color=blue background-image="...assets/images/bg.jpg" .unlisted .unnumbered .html-hidden}

What insights for practice do you expect from your study?

## Conclusion

An effective topic ...

:::{.incremental}
- allows researchers to tackle a __grand challenge__ in a literature,
- pursue a __novel direction__ that arouses,
- maintains __curiosity__,
- builds a study with __ambitious scope__, and
- uncovers __actionable insights__.
:::

# Research question

Once you have identified an *important problem domain* with an *important phenomenom* that deservices attention and relates to an *important problem* (i.e., an effective topic), you need to formulate and develop your own *research questions* and propose a plan to address them. 

. . .

This challenge is much more difficult than learning methods and theories, largely because it is not as structured but is undefined and highly contextual [@recker2021scientific].

. . .

However, the research question(s) is/are the __fundamental cornerstone__ that around which your whole research project revolves and evolves.


## Four problem indications

The "monologuing" problem
: You cannot tell what research question your are tackling unless you engage in a five-minute monologue—you have not grasped the essence of the problem yet.

. . .

The "so what" problem
: You cannot tell why answering the research question matters to anyone.

. . .

The "solving the world" problem
: Your question has value, but cannot be answered given your resource constraints.

. . .

The “multitude” 
: You ask (too) many questions instead of one.

:::{.notes}
Other categories of inappropriate research questions [@recker2021scientific]:

Obvious questions
: “Are there challenges in using information technology?” Of course there are. Obvious questions have answers to which everyone would agree.
Irrelevant questions
: “What is the influence of weather on the salaries of technology professionals?” There is no reason to believe that there is any influence whatsoever.
Absurd questions
: “Is the earth flat after all?” Absurd questions have answers to which everyone would agree, although I read that almost two percent of people still believe the earth is flat.
Definitional questions
: “Is technology conflict characterised by disagreement?” The answer is simply a matter of creating a concept that says it does. A definition is a form of description, not research.
Affirmation questions
: “Can a decision-support tool be developed to facilitate decision-making for senior retail executives?” Yes.

Use the problem statements to check your researh questions and the above categories as an exclusion list to ensure that your proposed research questions do not fit any of these problems, and if they do, go back and revise them.
:::

## Guiding questions

@recker2021scientific [p. 35-36] proposes a number of guiding questions can help you find a good research question, e.g.:

:::{.incremental}
- Do you know in which field of research your research questions reside?
- Do you have a firm understanding of the body of knowledge (the domain’s literature) in that field?
- What are important open research questions or unsolved problems in the field that scientists agree on?
- What areas need further exploration?
- Could your study fill an important gap in knowledge? 
- Has your proposed study been done before? If so, is there room for improvement or expansion?
- Is the timing right for the question to be answered?
- Who would care about obtaining an answer to the question? 
:::

## Think! {.vertical-center background-color=blue background-image="...assets/images/bg.jpg" .unlisted .unnumbered .html-hidden}

Test your ideas about a possible research question.    
Does it meet the criteria presented?

## Example {visibility="hidden"}

@recker2021scientific [p. 36 ff] uses following example on the motivation of a research question: 

"*Organisations invest heavily in new information technology to seek benefits from these investments.*
    
In this statement, we learn about a problem domain: investments into IT and benefit realisation from IT. This is an important problem domain for businesses because it involves money. As a tip, motivating research problems by citing data that confirm the quantifiable value associated with the problem (dollars spent, money lost, for example) might be valuable. Within this domain, we then learn about one important phenomenon:

*Many of these benefits never materialise because employees do not use the technologies.*

Here we drill down to a particularly important phenomenon of interest, individuals’ rejection of IT (i.e., their unwillingness to use IT), which narrows the problem domain down and will be useful in focussing the research later on. Finally, we learn about an important problem in the available knowledge that relates to this phenomenon:

*The literature to date has studied only why individuals accept new technologies but not why they reject them.*
  
Here we make a statement about the current body of knowledge. The problem with the body of knowledge we have (i.e., the literature available to date) is that it has a gap—that is, we do not know enough yet to address the specific phenomenon in the problem domain. For example, as the Covid-19 pandemic spread across the globe in 2020, at the beginning we had very little knowledge about the virus, its infection rates, and its possible cures or vaccinations. The problem then was a gap of knowledge.

A “gap” in knowledge is a typical problem with the available knowledge, but it is not necessarily the best or only problem [@alvesson2011generating]. For example, we could develop a set of arguments to strengthen the proposition that our theories on technology acceptance [e.g., @venkatesh2003user] fail to predict the opposite, rejection of technology, conclusively. Other typical problems with the knowledge could be that they have yielded inconsistent results: study A suggests one thing and study B suggests an opposite thing, so which is correct? That is a problem. Another problem might be that the knowledge to date rests on assumptions that are no longer current or realistic, such as when studies assume that findings for a sample of men must also apply to women.

Having introduced an important problem domain with a specific phenomenon and a substantial problem with the knowledge to date allows us to formulate a research question as the logical conclusion to these arguments:

*Why do people reject new information technology?*"

# Q&A {.vertical-center background-color=blue background-image="...assets/images/bg.jpg" .html-hidden .unlisted}

# Literature

::: {#refs}
:::
