---
title: "Assignment 📑"  
subtitle: "🧭 Digital Leadership (DL)"
lang: en

bibliography: ../assets/literature.bib

format: 
  html:
    output-file: index.html
  letterbox-revealjs:
    output-file: slides.html 
    date: "Summer Term 2023"
    include-before-body: ../assets/footer.html
---

# Top{visibility="hidden" .slide-link-hidden .unlisted .unnumbered}

{{< include ../assets/_top.qmd >}}

# Assignment 

Introduce and explain a theory, relate it to leadership issues, present recent empirical findings and discuss the value of the theory for leadership (approx. 20 minutes + 5 minutes Q&A).

Moreover, you need to prepare a group exercise for your fellow students. The exercise should help your fellow students to deepen their understanding of the theory and how it helps them to make sense of leadership in the digital age (approx 10 minutes).

## Topics

- Job demands-resources theory
- Organizational identity
- Professional identity
- Identity threats and identity work
- Social capital theory
- Emotional intelligence
- Psychological safety
- Transformational leadership theory
- Digital mindset

# Q&A {.html-hidden .unlisted background-color=blue}

# Literature
::: {#refs}
:::