---
title: "Ethics"
subtitle: "🧠 Introduction to AI — I2AI_8"
lang: en

bibliography: ../assets/literature.bib

format: 
  html:
    output-file: index.html
  letterbox-revealjs:
    output-file: slides.html 
    date: "Summer Term 2023"
    include-before-body: ../assets/footer.html
---

# Top{visibility="hidden" .slide-link-hidden .unlisted .unnumbered}

{{< include ../assets/_top.qmd >}}

# Intro {.vertical-center background-color=blue background-image="images/bg.jpeg"}

Fairspeech — Race Gap in Speech Recognition Technology


## Tasks

Have a look at the [fairspeech website](https://fairspeech.stanford.edu/) (and at the [research paper](https://www.pnas.org/doi/full/10.1073/pnas.1915768117)).

. . .

Think about the following questions and prepare answers.

:::{.incremental}
- What is the issue with current __automated speech recognition (ASR) systems __?
- Which ethical issues do they cause?
- What should be done to mitigate the risks?
:::

# Case Study {.vertical-center background-color=blue background-image="images/bg.jpeg"}

Ethical Implications of Artificial Intelligence, Machine Learning, and Big Data

## Tasks

Revisit the case study and work on following questions.

:::{.incremental}
- How do the problems described in the case study relate to what you have learned in this course about AI and how it works?
- Are there statements in the paper that you disagree with and/or that are counterintuitive in light of current developments?
- Regarding the AI services you use, where do you see the conditions of a informed consent as outlined in the case study fulfilled?
- What are explainable models and why are  they important from an ethical perspective?
- What are problems concerning explainable models and deep neural networks?
- Do you think we need more regulations to address AI and its impacts in the same way that we already do with climate change and biotechnology?
:::

# Research {.vertical-center background-color=blue background-image="images/bg.jpeg"}

Learn about government and private sector-driven approaches to moving toward responsible AI

## Group 1

Research about the __Proposal for a Regulation on Artificial Intelligence__ of the European Union (the "AI act").

. . .

Try to understand the purpose and content of the act.

. . .

Particularly, give answers to following questions:

:::{.incremental}
- What are general types of requirements on AI?
- What are high risk AI systems?
- Which requirements sould be mandatory requirements for these?
- Are government regulation as proposed here appropriate? 
:::

## Group 2

Research about __Microsoft Responsible AI Standard__ (v2)

. . . 

Try to understand the purpose of this standard.

. . .

Particularly, give answers to following questions:

:::{.incremental}
- What are goals Microsoft want to achieve?
- What are the principles described by the standard?
- How does Microsoft propose to assess the impact of AI?
- How does the standard affect Microsofts own operations and services?
:::

## Group 3

Research about __Googles Viewpoint on AI__

. . . 

Try to understand Google's approach to develop artificial intelligence responsibly in order to benefit people and society.

. . .

Particularly, give answers to following questions:

:::{.incremental}
- What are google's principels to responsible AI?
- What kind of AI applications does Google not develop on principle? Are the statements credible?
- Which practices do they recommend when developing AI?
- How do Google's principal and practices affect their organization and operations?
:::

## Summary

What are similarities and differences of these approaches to responsible AI?

Which principles and practices would you make yours?