---
title: "Kick-off 🧐"
subtitle: "🧠 IT as a Service Enabler (ITSE)"

bibliography: ../assets/literature.bib

format: 
  html:
    output-file: index.html
  revealjs:
    output-file: slides.html 
    include-after-body: ../assets/footer.html    
---

# Top{visibility="hidden" .slide-link-hidden .unlisted}
[Slides](slides.html)

__Printing/export__

If you want to print or export the slides, open the slides, press `e` on your keyboard and then print (to pdf).

# General remarks

Welcome to the team `zimmermann/weeger`[^Z]!

[^Z]: For contact details of Sina Zimmermann, please click [here](https://www.hnu.de/sina-zimmermann)

. . .

Aspiration: solid scientific work (good chance to prepare for the BA)

. . .

Important notes:

:::{.incremental}
- __Effort__: 5 ECTS (approx. 120 h)
- __Language__ of the paper: English
- __Structure__ of the final paper: see [Moodle](https://elearning.hnu.de/mod/resource/view.php?id=518345) [^S]
- __Deadline:__ 4. Juli 2022
:::

[^S]: No need to create a ToC, it is already fixed

. . . 

For detailed requirements and evaluation criteria see [Moodle](https://elearning.hnu.de/mod/resource/view.php?id=518346)


## Topics #1

For more details on the topic and literature starting points, please see [Moodle](https://elearning.hnu.de/mod/resource/view.php?id=518344)

:::{.fragment .fade-in-then-semi-out}
- __Smart Parking__ — A step towards ecological sustainability? *(Schaupp, Hauck)*
  - Analysis of user ratings; method similar to @schulz2021value
  - Business model analysis; desk research, morphological box see @hein2018towards
:::
:::{.fragment .fade-in-then-semi-out}
- Use of __mobility apps__ for sustainable behavior change *(A. Bratrich, Derya)*
  - Structured literature review; details see on Moodle
  - Analysis of mobility apps; morphological box that classifies the apps
:::
:::{.fragment .fade-in-then-semi-out}
- __Public transport__ in the new normal and the next normal *(Deinzer, Haßler)*
  - Analysis of business models; morphological box, see @hein2018towards
  - Impact of automonous vehicles; structured literature review; details see Moodle
:::

## Topics #2

:::{.fragment .fade-in-then-semi-out}
- Similarities and differences of __digital nudging and gamification__ *(M. Batrich, Kühnl)*
  - Structured literature review; details see on Moodle
  - Structured review and analysis of cases; details see on Moodle
:::
:::{.fragment .fade-in-then-semi-out}
- __Process Mining__ Case Studies in SMEs *(Wojcik)*
  - Structured literature review; details see on Moodle 
:::

# Literature

Your first task: __get to know the literature__ (what is already known)

. . .

Focus on __scientific literature__ (peer-reviewed, high quality)

. . .

:::{.incremental}
- Only scientific papers that are peer-reviewed
- Concering the theoretical part: no practitioner papers (e.g., white papers from consulting firms), no books, not web-sources, etc. [^1]
- Recommendation is to restrict the search on high-quality IS journals, either
	- [Senior Scholars' Basket of Journals](https://aisnet.org/page/SeniorScholarBasket)
	- [A-ranked Journals in the VHB-JOURQUAL3 ranking](https://vhbonline.org/fileadmin/user_upload/JQ3_WI.pdf)
:::

[^1]: Practitioner papers and web-sources are only valid for empirical papers using secondary sources (e.g., desk research)

. . .

Use the __journal's archives__ to search for literature

. . .

Use __EndNote__ to organize your literature

# Next steps

:::{.incremental}
- Decide on your __topic__
- Work through the __literature review materials__ on Moodle
- __Read the recommended papers__; extract definitions for the main concepts
- Start your (structured) __literature search__ (e.g., with two to three journals)
- Get the full-texts of the identified articles
- __Organize the literature__ in EndNote
- Start __reading articles__, begin with the two that are cited mostly
- Write down what you have learned for your study (e.g., definitions, concepts, mechanisms)
- Write down your __questions__ for our next session
- Book an appointment
:::

# Literature
::: {#refs}
:::