---
title: "Administrivia"  
subtitle: "Business Value Creation by IT (BVC)"
lang: en
categories: ["Admin"]

author: "Andy Weeger"

date: "09.14.2026"

bibliography: ../assets/literature.bib

format: 
  html:
    output-file: index.html
    margin-header: | 
      [Slides](slides.html){.btn .btn-primary target="blank"}
    format-links: false  
  presentation-revealjs:
    output-file: slides.html
    include-before-body: ../assets/footer.html
---

# General remarks

:::medium
In this course [you will **develop a technological artifact**]{.fragment .fade-in} [that has the potential **to create value** for a specific organisation]{.fragment .fadein} [[(e.g. prototyping a new product, improving a process, supporting a decision).]{.smaller}]{.fragment .fade-in} 
:::

As to that, you

- will apply your learning from your undergraduate degree as well as from the first semester of your Masters program; and you
- will also be introduced to current methodological and theoretical knowledge. This will help you to carry out the real-world problem and to reflect on the process and the results. 

It is very important that you prepare yourself for the classes (see @tbl-schedule for details).

# Contents

There will be no teaching sessions this semester. To support understanding and transfer of topics, please refer to the lecture notes from last semester covering, e.g.,:

:::incremental
- Essential aspects of IT/digital resources
- Turning digital resources into value
- Challenges in implementing digital resources (changing, adopting & using)
- Current approaches of AI-enabled value creation (i.e., Agentic AI)
- Identification of (customer) needs (e.g. Design Thinking)
:::

# Learning objectives

During this course, you should advance your skills in the following areas:

:::incremental
- Understand the **mechanisms of value contribution by IT**
- How to **design and implement IT solutions** that create value in a specific context.
- How to apply and contextualise existing knowledge and understanding of disruptive technologies in the context of a specific organisational environment
- **Problem-solving skills** to analyze the particularities and complexities of different project contexts
- Reflecting on social and ethical responsibilities and making responsible decisions with incomplete or limited information 
:::

# Examination

During the semester you will be required to work **within a group** on a **business challenge** posed by practitioners. The examination will be based on following performances:

- A **presentation** of your approach to the challenge and the value contribution of your solution.
- A **seminar paper** that details your approach and solution.

Details regarding the assignment can be found [here](../assignment/).


# Effort

You will gain 5 ECTS for this course.      
This corresponds to approx. **150 hours of workload** for *average students* required to pass the module.

# Schedule {.smaller}

:::notes
It is important that you work on the challenges in a self-organised and continuous manner.
:::

| Date             | Topic                                        | Preparation       |
|:-----------------|:---------------------------------------------|:------------------| 
| 28.10.2026, eod  | **Briefing:** Assignment (via Email)         | -            
| 12.01.2027, eod  | **Deadline:** Submit Pitch Deck (via Email)  | Slides            
| 13.01.2027, 3 pm | **Final Presentation & Feedback** (Room tbd) | Pitch             
| 25.01.2027       | **Deadline:** Submit Paper (via Email)       | Paper             

: Schedule winter term 2026 (may be subjected to changes) {#tbl-schedule}