---
title: "Administratives 🧐"
subtitle: "`DEM_1` DE1: Digitalisierung und Informationssysteme"
lang: de-DE

bibliography: ../assets/literature.bib

date: "09.17.2024"

format: 
  html:
    output-file: index.html
    margin-header: | 
            [Slides](slides.html){.btn .btn-primary target="blank"}
    format-links: false    
  presentation-revealjs:
    output-file: slides.html 
    include-before-body: ../assets/footer.html
---

# Allgemeines {visibility="hidden"}

Im Modul Digital Enterprise 1 erhalten Sie eine **Einführung in viele wichtige Konzepte der Wirtschaftsinformatik (WI)**. 

Der Kurs basiert auf einem Blended Learning Konzept (Flipped Classroom). Das bedeutet, dass Sie zu Hause die Inhalte der Vorlesung vorbereiten. Hierzu sollten Sie min. das Skript zum Thema durcharbeiten.

In den gemeinsamen Veranstaltungen reflektieren und vertiefen wir dann die Inhalte anhand von Übungen (oft in Kleingruppen). Manche Übungen sollten Sie nach den Sessions eigenständig bearbeiten.

# Ihre Ziele {.html-hidden .unlisted .no-headline background-color=black background-iframe="https://www.mentimeter.com/app/presentation/algngnb7p2mgtfopk3pspxv3oy5fqcna/embed"}

# Lernziele

Nach der Veranstaltung sollten Sie unter anderem[^1] in der Lage sein,

:::{.incremental}
-	__Grundkonzepte der WI__ zum Digitalen Enterprise und der Umwelt benennen und anhand von Beispielen erläutern,
-	interne und externe Treiber sowie die Potenziale der __Digitalisierung von Unternehmen und Märkten__ benennen und deren Zusammenhänge erklären,
-	wesentliche __Komponenten des Digital Enterprise__ beschreiben und klassifizieren (Technologie, Informationssysteme, Strategie) und
-	ausgewählte Methoden zum __Management des Digital Enterprise__ und zugehörige digitale Werkzeuge anwenden (bspw. Auswahl von Anwendungssystemen und Betriebsmodellen)
:::

[^1]: Vollständige Liste der Lernziele siehe Modulbeschreibung 

# Struktur der Vorlesung {.vertical-center background-color="#0333ff"}

## Einheiten

Die Vorlesung ist in 11 Kapitel (`K`) gegliedert

:::{.incremental .smaller}
- `K1` __Einführung__ — Was sind Grundkonzepte des Informationsmanagements?
- `K2` __Digitalisierung__ — Was ist das besondere an unserer Zeit?
- `K3` __Technologie__ — Was ist die Basis von Informationssystemen?
- `K4` __Informationssysteme__ — Wie prägen Informationssysteme die Wertschöpfung?
- `K5` __Prozesse__ — Wie werden Abläufe im Unternehmen gesteuert?
- `K6` __Integration__ — Was ist integrierte Informationsverarbeitung? 
- `K7` __Anwendungssysteme__ — Welches sind die wichtige Anwendungssysteme?
- `K8` __Scale-Up__ - Wie spielen die Elemente zusammen?
- `K9` __Implementierung__ — Wie entstehen Informationssysteme?
- `K10` __IT-Management__ — Wie werden Informationssysteme gesteuert?
- `K11` __Geschäftsmodelle__ — Wie verändert sich die Logik von Unternehmen, Wert zu erzeugen??
:::

## Lernmaterialien

Jedes Kapitel enthält folgende Lernmaterialien: 

:::{.incremental}
-	__Vorlesungsskript__ *(Wiki)*
- __Big Picture__ *(Visuelle Zusammenfassung der Kapitel)*
-	__Übungen__ *(Wiederholung, Reflektion und Vertiefung)*
- Referenz zu weiterführender __Literatur__ *(insbesondere @mertens2016grundzuge, @lemke2017einfuhrung und @bachle2021einfuhrung, alle als E-Books verfügbar)*
-	__Moodle-Quizze__
:::

:::{.fragment}
Alle Inhalte sind prüfungsrelevant.
:::

## Ablauf und Aufwände

Der Kurs basiert auf einem Blended Learning Konzept („Flipped Classroom“)

:::{.incremental}
- Sie erarbeiten sich die Inhalte im __Selbststudium__ *(10 x ca. 2,5 h)*
- Wir wiederholen und vertiefen in der __Veranstaltung__ *(13 x ca. 2,5 h)*
  - Zusammenfassung der Inhalte (Big Picture)
  - Antwort auf Ihre Fragen (Q&A)
  - Übungen (oft in Kleingruppen)
- Sie bereiten sich auf die __Portfolio-Prüfung__ vor *(restliche Zeit)*
:::

:::notes



Der Kurs ist mit 5 ECTS gewichtet. Rechnen Sie deshalb mit einem Arbeitsaufwand von ca. 125 h. 

Die ungefähre Verteilung des Arbeitsaufwands entnehmen Sie bitte obiger Auflistung. Die restliche Zeit ist für das Selbststudium, insbesondere die Vorbereitung auf die Abschlussprüfung vorgesehen.

Die Erfahrung aus vorangegangen Kursen lehrt, dass ohne die Teilnahme an den Veranstaltungen und die Bearbeitung der Übungen das Bestehen des Kurses mit einer ordentlichen Note kaum möglich ist.

Dieses __Lern-Set-Up__ soll Sie dazu befähigen

-	eigenverantwortlich mit Lernangeboten umzugehen und wirksame Lernstrategien zu entwickeln,
-	den Einsatz von digitalen Werkzeugen in Unternehmen gesellschaftskritisch zu reflektieren,
-	Zusammenhänge zu erfassen, auf den Punkt zu bringen und für andere verständlich zu erklären
:::

## Prüfungsleistung

Die Vorlesung wird anhand einer __Portfolio-Prüfung__ bewertet.

:::{.incremental}
- Die Portfolio-Prüfung besteht aus vier unterschiedlichen Teilen:
  - __10 Quizze__ (je ca. 1 Woche Bearbeitungszeit, 15 Punkte)[^Q]
  - __Eine Kurzpräsentation__ zum Prüfungsstoff (ca. 3 Wochen Bearbeitungszeit, 20 Punkte)
  - __Abschlussprüfung__ (50 Minuten Bearbeitungszeit, 55 Punkte)
- Die Gesamtzahl der in diesem Kurs erreichbaren Punkte beträgt 90. Sie benötigen __45 Punkte zum Bestehen__.
- Für Übungen, die in der Vorlesung bearbeitet und im Plenum vorgestellt werden, gibt es **Bonuspunkte,** die zu einer Verbesserung der Note um bis zu .7 Notenpunkte führen können (vorausgesetzt, die Bestehensgrenze wurde erreicht).
:::

. . .

:::html-hidden
:::smaller
*Easy Enrollment Key* für den [Exam Moodle](https://exam.hnu.de/course/view.php?id=573): **adu35v**
:::
:::

[^Q]: Bitte beachten Sie, dass die Quizze **nur** innerhalb eines definierten Zeitraums (variiert pro Quiz, siehe Moodle) absolviert werden können.

## Zeitplan {.scrollable .smaller}

::: {.notes}
Es ist wichtig, dass Sie sich auf die Veranstaltung vorbereiten, die Inhalte kontinuierlich reflektieren, die Übungen durchführen und Fragen stellen.
:::

|Datum        | Thema                                                  | Prüfungsteil    |
|:------------|:-------------------------------------------------------|:----------------|
|`10.10.2024` | Kick-off und `K1` Einführung                           | -
|`17.10.2024` | `K2` Digitalisierung                                   | -
|`24.10.2024` | `K3` Technologie                                       | -
|`31.10.2024` | `K4` Informationssysteme                               | Quiz K1-K4
|`07.11.2024` | `K5` Prozesse                                          | Quiz K5
|`14.11.2024` | Selbststudium (Übungen, Verständnisfragen)             | -
|`21.11.2024` | `K6` Integration und Ausgabe Präsentationsthemen       | Quiz K6
|`28.11.2024` | `K7` Anwendungssysteme                                 | Quiz K7
|`05.12.2024` | `K8` ScaleUp!                                          | -
|`12.12.2024` | `K9` Implementierung                                   | Quiz K9
|`13.12.2024` | **Deadline** Abgabe Kurz-Präsentationen                | Video
|`19.12.2024` | Review Kurz-Präsentationen                             | -
|`09.01.2025` | `K10` IT-Management                                    | Quiz K10
|`16.01.2025` | `K11` Geschäftsmodelle                                 | Quiz K11
|`23.01.2025` | Wrap-Up & Prüfungsvorbereitung                         | Fragen

: Zeitplan Wintersemester 2024/25 (Änderungen vorbehalten) {#tbl-schedule}


# Q&A {background-color=lightgrey background-image="images/question.jpeg" .unlisted .html-hidden}

# Wrap-up {.html-hidden .unlisted .no-headline background-color=black background-iframe="https://www.mentimeter.com/app/presentation/algngnb7p2mgtfopk3pspxv3oy5fqcna/embed"}

# Bonus {background-color=black .unlisted .html-hidden .no-headline}

<div style="max-width:854px"><div style="position:relative;height:0;padding-bottom:56.25%"><iframe src="https://embed.ted.com/talks/lang/en/tim_urban_inside_the_mind_of_a_master_procrastinator" style="position:absolute;left:0;top:0;width:100%;height:100%" frameborder="0" scrolling="no" allowfullscreen></iframe></div></div>

# Literatur 📚
::: {#refs}
:::