---
title: "Kick-off"
subtitle: "IT as a Service Enabler (ITSE)"

bibliography: ../assets/literature.bib

format: 
  html:
    output-file: index.html
  revealjs:
    date: "Winter Term 2022"
    output-file: slides.html 
    include-after-body: ../assets/footer.html  
---

# Top{visibility="hidden" .slide-link-hidden .unlisted .unnumbered}

{{< include ../assets/_top.qmd >}}

# General remarks

Welcome to the team `weeger`!

. . .

Aspiration: solid scientific work (good chance to prepare for the BA)

. . .

Important notes:

:::{.incremental}
- __Effort__: 5 ECTS (approx. 120 h)
- __Language__ of the paper: English
- __Structure__ of the final paper: see [Moodle](https://elearning.hnu.de/mod/resource/view.php?id=518345) [^S]
- __Deadline:__ 4. July 2022
:::

[^S]: No need to create a ToC, it is already fixed

. . . 

For detailed requirements and evaluation criteria see [evaluation criteria](../evaluation/)


## Topics

For more details on the topics, please see [topic](../topic/)

:::{.incremental .fade-in-then-semi-out}
- Mobility behavior change *(design science, group-work 3 students)*
- EV charging network apps *(empirical paper, 1 student)*
- Smart carpooling platforms *(empirical paper, 1 student)*
- Private car-sharing *(structured literature review, 1 student)*
- Gamification for sustainable innovation *(structured literature review, 1 student)*
:::


## Literature

Your first task: __get to know the literature__ (what is already known)

. . .

Focus on __scientific literature__ (peer-reviewed, high quality)

. . .

:::{.incremental}
- Only scientific papers that are peer-reviewed
- Concerning the theoretical part: no practitioner papers (e.g., white papers from consulting firms), no books, not web-sources, etc. [^1]
- Recommendation is to focus the search on high-quality IS journals, either
	- [Senior Scholars' Basket of Journals](https://aisnet.org/page/SeniorScholarBasket)
	- [A-ranked Journals in the VHB-JOURQUAL3 ranking](https://vhbonline.org/fileadmin/user_upload/JQ3_WI.pdf)
:::

[^1]: Practitioner papers and web-sources are only valid for empirical papers using secondary sources (e.g., desk research)

. . .

Use __Web of Science__ or the __journals' archives__ to search for literature

. . .

Use __EndNote__ to organize your literature

# Next steps

:::{.incremental}
- Decide on your __topic__
- Work through the __literature review materials__ on Moodle
- __Read the recommended papers__; extract definitions for the main concepts
- Start your (structured) __literature search__ (e.g., with two to three journals)
- Get the full-texts of the identified articles
- __Organize the literature__ in EndNote
- Start __reading articles__, begin with the two that are cited mostly
- Write down what you have learned for your study (e.g., definitions, concepts, mechanisms)
- Write down your __questions__ for our next session
- Book an [appointment](https://calendly.com/awe-hnu/office)
:::

# References
::: {#refs}
:::