---
title: "`K8` Scale-Up"
subtitle: "Wie spielen die Elemente zusammen?"
lang: de-DE

bibliography: ../assets/literature.bib

format: 
  html:
    output-file: index.html
  presentation-revealjs:
    date: "Wintersemester 2022"
    output-file: slides.html 
    include-before-body: ../assets/footer.html
---

# Motivation {.vertical-center background-color="#0333ff"}

> Spiel ist die früheste Form der geistigen Bildung. Durch das Spiel wird die Welt entdeckt und erobert. *Friedrich Fröbel (1782-1852), deutscher Reformpädagoge, Begründer des Kindergartens*‚

# Lernergebnisse 🎯

Nach dieser Einheit

::: incremental
- haben Sie ein vertieftes Verständnis der in den vorherigen Kapiteln eingeführten Konzepten (insbesondere Digitalisierung, Informationssystem, Anwendungssystem),
- haben Sie ein besseres Verständnis wichtiger Geschäftsprozesse von Unternehmen und der Rolle von Informationssystemen,
- haben erste Erfahrungen in der Konfiguration und Nutzung integrierter Anwendungssysteme gesammelt und
- können die Eigenschaften von Cloud-Computing, Open Source Software und integrierter Informationsverarbeitung an einem spezifischen Beispiel erläutern.
:::

# Kontext

Stellen Sie sich vor, Sie hätten vor drei Monaten Ihren gute bezahlten Job in der Unternehmenskommunikation gekündigt. Mit 50.000 Dollar Startkapital in der Tasche möchten Sie nun ein neues Abenteuer beginnen und gründen ein Möbelgeschäft.

Einen Monat später haben Sie *MyOffice, Inc.* offiziell gegründet. Außerdem haben Sie die ersten drei Mitarbeiter angestellt: Sophia für den Vertrieb, Marc für den Einkauf und Paul als persönlichen Assistenten.

Sie erinnern sich an Ihre Vorlesung *Digital Enterprise 1* und die Bedeutung von effizientem Informationsmanagment mittels integrierter Anwendungssysteme. Deshalb entschließen Sie sich, ein solches System einzuführen. Die Entscheidung fällt auf die Open Source Software [Odooo](https://www.odoo.com).

Jetzt wird es Zeit, Geld zu verdienen.

# Vorbereitung

Bilden Sie eine Gruppe mit drei bis vier Kommilitonen. 

- Erstellen Sie [hier](https://www.odoo.com/de_DE/trial) eine Demo-Datenbank in der Cloud-basierten open-source Software Odoo (kostenlose, 15-Tage Testversion). Wählen Sie zum Start die Apps *Vertrieb*, *Buchhaltung*, *Lager* und *Einkauf*. Es ist ausreichend, wenn einer aus Ihrer Gruppe die Datenbank erstellt.
- Laden Sie [hier](https://www.odoo.com/de_DE/education/scale-up-business-game) die *Scale-up Spielkarten* herunter.
- Wiederholen Sie die bisherigen Kapitel.

# Spielregeln

Das Spiel besteht aus 7 Business Cases. Jeder Case umfasst 8 bis 10 Karten. Wir spielen die Business Cases in folgender Reihenfolge durch:

1. *Buy & Sell* 
2. *Manufacture*
3. *Run a Store*
4. *Sell Online*
5. *Sell Services*
6. *Create your App*

Versuchen Sie die Business Cases anhand der Anleitungen auf der Vorderseite zu lösen. Prüfen Sie im Anschluss Ihre Lösung mit der auf der Rückseite beschriebenen Lösung. Schauen Sie nur auf die Rückseite, wenn Sie nicht mehr weiterkommen.

Versuchen Sie zudem die Wiederholungsfragen zu beantworten. Bereiten Sie sich darauf vor, Ihre Antworten im Plenum vorzustellen.

# Wiederholungsfragen

## Allgemein

Odoo ist eine **Open Source Software**, die über [Odoo.com](https://www.odoo.com/de_DE/pricing-plan) als **SaaS** bezogen werden kann.

Beantworten Sie folgende Fragen:

1. Nennen Sie drei Eigenschaften, die *Open Source Software* von *Closed Source Software* unterscheidet.
2. Erläutern Sie am Beispiel Odoo was SaaS bedeutet und zeigen Sie die wesentlichen Eigenschaften von SaaS.
3. Worin unterscheidet sich die SaaS-Lösung von PaaS (siehe bspw. [Odoo.sh](https://www.odoo.sh))?
4. Was wäre die Alternative zur Nutzung von Odoo als Cloud-Lösung? Welche Vor- und Nachteile sind damit verbunden?

## Buy & Sell

In Kapitel 1 haben Sie gelernt, dass (a) **Information** analog zu den anderen **Produktionsfaktoren** gesteuert werden müssen und, dass (b) Information die Steuerung der anderen Produktsionfaktoren unterstützt.

1. Erläutern Sie diese beiden Punkte anhand dieses Business Cases.
2. Wie hilft das Managementsystem Odoo die Ziele des Informationsmanagments zu erreichen?
3. "Odoo macht aus Daten Informationen" — erläutern Sie dieses Statement.

## Manufacture

Informationssysteme unterstützen sowohl die **horizontale Integration** als auch die **vertikale Integration**.

1. Erläutern Sie diese beiden Konzepte anhand des *Manufacture* Business Case.
2. Was sind Vorteile der integrierten Informationsverarbeitung? Gibt es auch Nachteile? 
3. Welche Rolle spielen Stammdaten bei der Integration?
4. Welche Stammdaten werden in diesem Business Case verwendet?

## Run a Store

Der Verkauf von Produkten im Store ist ein **Kernprozess** von MyOffice, Inc.

1. Erläutern Sie was ein **Geschäftsprozess** ausmacht (Eigenschaften und Komponenten).
2. Wodurch grenzen sich Kernprozesse von Unterstützungsprozesse ab?
3. Was ist **Geschäftsprozessmanagement**?
4. Weshalb ist es sinnvoll Geschäftsprozesse im Rahmen des Geschäftsprozessmanagements zu modellieren?
5. Welche Elemente der **EPK-Basisnotation** benötigen Sie, um im Geschäftsprozesse die Bezahlmöglichkeiten "Rechnung" und "Barkauf" zu modellieren? Welche **Modellierungsregeln** müssen Sie dabei beachten?

## Sell Online

Dass Menschen Produkte online kaufen und verkaufen wird bzw. ist im **digitalen Zeitalter** Standard.

1. Erkläutern Sie anhand des Online-Shoppings (a) zwei wesentliche Eigenschaften und (b) zwei wesentliche Konsequenzen des digitalen Zeitalters. 
2. Digitalisierung im technischen Sinne ist Grundvoraussetzung dafür, dass Produkte über Internet verkauft werden können. Erläutern Sie diese Aussage.

## Sell Services

**Informationssysteme** werden entwickelt, betrieben und genutzt, um spezifische Aufgaben zu erfüllen und die notwendigen Informationen zu bereitzustellen und zu verarbeiten.

1. Im Business Case wird das Informationssystem der MyOffice, Inc. zum Verkauf von Dienstleistungen beschrieben. Beschreiben Sie dessen Komponenten.
2. Erläutern Sie anhand der in (1) genannten Komponenten, was ein *sozio-technisches System* ist.
3. Dem Business Engineering Modell folgend, wovon ist die Gestaltung von Informationssystemen abhängig und wozu dienen Informationssysteme im Allgemeinen?
4. Zeigen Sie anhand des Beispiels drei spezifische Ziele des Einsatz von Informationssystemen.

## Create your App

Bei **Anwendungssystemen** wird zwischen **Standardssoftware** und **Individualsoftware** unterschieden.

1. Grenzen Sie die beiden Begriffe voneinander ab.
2. In welchem Zusammenhang stehen Anwendungssysteme und Informationssysteme?
3. Nennen und erläutern Sie jeweils einen Vor- und Nachteil von Indvidualsoftware am Beispiel der Office Rental App.
4. Handelt es sich bei der Office Rental App um ein **operatives Anwendungssystem** oder ein **analytisches Anwendungssystem**? Begründen Sie Ihre Antwort.