---
title: "Administratives 🧐"
subtitle: "`DEM_1` DE1: Digitalisierung und Informationssysteme"
lang: de-DE

bibliography: ../assets/literature.bib

date: "08.15.2025"

format: 
  html:
    output-file: index.html
    margin-header: | 
            [Slides](slides.html){.btn .btn-primary target="blank"}
    format-links: false    
  presentation-revealjs:
    output-file: slides.html 
    include-before-body: ../assets/footer.html
---

# Allgemeines {visibility="hidden"}

Im Modul Digital Enterprise 1 erhalten Sie eine **Einführung in viele wichtige Konzepte der Wirtschaftsinformatik (WI)**.

Der Kurs basiert auf einem Blended Learning Konzept (Flipped Classroom). Das bedeutet, dass Sie zu Hause die Inhalte der Vorlesung vorbereiten. Hierzu sollten Sie min. das Skript zum Thema durcharbeiten.

In den gemeinsamen Veranstaltungen reflektieren und vertiefen wir dann die Inhalte anhand von Übungen (oft in Kleingruppen). Manche Übungen sollten Sie nach den Sessions eigenständig bearbeiten.

# Ihre Ziele {.html-hidden .unlisted .no-headline background-color="black" background-iframe="https://www.mentimeter.com/app/presentation/alidpmdmf3yn48fbqi2boyg3tbzn34r2/embed"}

# Lernziele

Nach der Veranstaltung sollten Sie unter anderem[^1] in der Lage sein,

[^1]: Vollständige Liste der Lernziele siehe Modulbeschreibung

::: incremental
-   **Grundkonzepte der WI** zum Digitalen Enterprise und der Umwelt benennen und anhand von Beispielen erläutern,
-   interne und externe Treiber sowie die Potenziale der **Digitalisierung von Unternehmen und Märkten** benennen und deren Zusammenhänge erklären,
-   wesentliche **Komponenten des Digital Enterprise** beschreiben und klassifizieren (Technologie, Informationssysteme, Strategie) und
-   ausgewählte Methoden zum **Management des Digital Enterprise** und zugehörige digitale Werkzeuge anwenden (bspw. Auswahl von Anwendungssystemen und Betriebsmodellen)
:::

# Struktur der Vorlesung {.headline-only}

## Einheiten

Die Vorlesung ist in 11 Einheiten gegliedert:

::: {.incremental .smaller}
-   **Einführung** (E1) — Was sind Grundkonzepte des Informationsmanagements?
-   **Digitalisierung** (E2) — Wie verändert die digitale Transformation Unternehmen und Gesellschaft?
-   **Technologie** (E3) — Was ist die Basis von Informationssystemen?
-   **Informationssysteme** (E4) — Wie prägen Informationssysteme die Wertschöpfung?
-   **Prozesse** (E5) — Wie werden Abläufe im Unternehmen gesteuert?
-   **Integration** (E6) — Was ist integrierte Informationsverarbeitung?
-   **Anwendungssysteme** (E7) — Welches sind die wichtige Anwendungssysteme?
-   **Scale-Up** (E8) - Wie spielen die Elemente zusammen?
-   **Implementierung** (E9) — Wie entstehen Informationssysteme?
-   **IT-Management** (E10) — Wie werden Informationssysteme gesteuert?
-   **Geschäftsmodelle** (E11) — Wie verändert sich die Logik von Unternehmen, Wert zu erzeugen?
:::

## Lernmaterialien

Jede Einheit umfasst folgende Lernmaterialien:

::: incremental
-   **Vorlesungsskript** *(Website und Folien)*
-   **Big Picture** *(visuelle Zusammenfassung der Einheit)*
-   **Übungen** *(Wiederholung, Reflektion und Vertiefung)*
-   Referenz zu weiterführender **Literatur** *(insbesondere @mertens2016grundzuge, @lemke2017einfuhrung und @bachle2021einfuhrung, alle als E-Books verfügbar)*
-   **Kurztests in Moodle**
:::

::: fragment
Alle Inhalte sind prüfungsrelevant.
:::

## Ablauf und Aufwände

Der Kurs basiert auf einem Blended Learning Konzept („Flipped Classroom“)

::: incremental
-   Sie erarbeiten sich die Inhalte im **Selbststudium** *(10 x ca. 2,5 h)*
-   Wir wiederholen und vertiefen in der **Veranstaltung** *(13 x ca. 2,5 h)*
    -   Zusammenfassung der Inhalte (Big Picture)
    -   Antwort auf Ihre Fragen (Q&A)
    -   Übungen (oft in Kleingruppen)
-   Sie bereiten sich auf die **Portfolio-Prüfung** vor *(restliche Zeit)*
:::

::: notes
Der Kurs ist mit 5 ECTS gewichtet. Rechnen Sie deshalb mit einem Arbeitsaufwand von ca. 125 h.

Die ungefähre Verteilung des Arbeitsaufwands entnehmen Sie bitte obiger Auflistung. Die restliche Zeit ist für das Selbststudium, insbesondere die Vorbereitung auf die Abschlussprüfung vorgesehen.

Die Erfahrung aus vorangegangen Kursen lehrt, dass ohne die Teilnahme an den Veranstaltungen und die Bearbeitung der Übungen das Bestehen des Kurses mit einer ordentlichen Note kaum möglich ist.

Dieses **Lern-Set-Up** soll Sie dazu befähigen

-   eigenverantwortlich mit Lernangeboten umzugehen und wirksame Lernstrategien zu entwickeln,
-   den Einsatz von digitalen Werkzeugen in Unternehmen gesellschaftskritisch zu reflektieren,
-   Zusammenhänge zu erfassen, auf den Punkt zu bringen und für andere verständlich zu erklären
:::

## Prüfungsleistung

Die Vorlesung wird anhand einer **Portfolio-Prüfung** bewertet.

::: incremental
-   Die Portfolio-Prüfung besteht aus drei unterschiedlichen Teilen:
    -   **10 Kurztests** (je ca. 1 Woche Bearbeitungszeit, 15 Punkte)[^2]
    -   **Eine Präsentation** (Video) zum Prüfungsstoff (ca. 3 Wochen Bearbeitungszeit, 20 Punkte)
    -   **Abschlussprüfung** (50 Minuten Bearbeitungszeit, 55 Punkte)
-   Die Gesamtzahl der in diesem Kurs erreichbaren Punkte beträgt 90. Sie benötigen **45 Punkte zum Bestehen**.
-   Für Übungen, die in der Vorlesung bearbeitet und im Plenum vorgestellt werden, gibt es **Bonuspunkte,** die zu einer Verbesserung der Note um bis zu .7 Notenpunkte führen können (vorausgesetzt, die Bestehensgrenze wurde erreicht).
:::

[^2]: Bitte beachten Sie, dass die Kurztests **nur** innerhalb eines definierten Zeitraums (in der Woche vor der Vorlesung, exakte Zeiträume siehe Moodle) absolviert werden können.

. . .

:::: html-hidden
::: smaller
*Easy Enrollment Key* für den [Exam Moodle](https://exam.hnu.de/course/view.php?id=573): **adu35v**
:::
::::

## Zeitplan {.scrollable .smaller}

::: notes
Es ist wichtig, dass Sie sich auf die Veranstaltung vorbereiten, die Inhalte kontinuierlich reflektieren, die Übungen durchführen und Fragen stellen.
:::

| Datum      | Thema                                                                                                  | Abgabe      |
|:-----------|:-------------------------------------------------------------------------------------------------------|:------------|
| 09.10.2025 | Kick-off und **Einführung** (E1)                                                                       | \-          |
| 16.10.2025 | **Digitalisierung** (E2)                                                                               | \-          |
| 23.10.2025 | **Technologie** (E3)                                                                                   | \-          |
| 30.10.2025 | **Informationssysteme** (E4) und Vorstellung Präsentationsprüfung                                      | Tests E1-E4 |
| 05.11.2025 | **Deadline** [Wahl Präsentationsthema](https://elearning.hnu.de/mod/ratingallocate/view.php?id=737678) | Themenwahl  |
| 06.11.2025 | **Prozesse** (E5, Selbststudium)                                                                       | Test E5     |
| 13.11.2025 | **IT-Kongress** (alternativ Selbststudium)                                                             | \-          |
| 20.11.2025 | **Integration** (E6)                                                                                   | Test E6     |
| 27.11.2025 | **Anwendungssysteme** (E7)                                                                             | Test E7     |
| 04.12.2025 | **ScaleUp!** (E8)                                                                                      | \-          |
| 11.12.2025 | **Implementierung** (E9)                                                                               | Test E9     |
| 11.12.2025 | **Deadline** [Abgabe Präsentationen](https://exam.hnu.de/mod/assign/view.php?id=8600)                  | Video       |
| 18.12.2025 | **IT-Management** (E10)                                                                                | Test E10    |
| 08.01.2026 | Besprechung Kurz-Präsentationen                                                                        | \-          |
| 15.01.2026 | **Geschäftsmodelle** (E11)                                                                             | Test E11    |
| 22.01.2026 | Wrap-Up & Prüfungsvorbereitung                                                                         | Fragen      |

: Zeitplan Wintersemester 2025/26 (Änderungen vorbehalten) {#tbl-schedule}

# Q&A {.headline-only .unlisted .html-hidden}

# Bonus {.unlisted .html-hidden .no-headline background-color="black"}

:::: {style="max-width:854px"}
::: {style="position:relative;height:0;padding-bottom:56.25%"}
<iframe src="https://embed.ted.com/talks/lang/en/tim_urban_inside_the_mind_of_a_master_procrastinator" style="position:absolute;left:0;top:0;width:100%;height:100%" frameborder="0" scrolling="no" allowfullscreen>

</iframe>
:::
::::

# Literatur 📚

::: {#refs}
:::