---
title: "Review & revision"  
subtitle: "..."
lang: en-US

bibliography: ../assets/literature.bib

format: 
  html:
    output-file: index.html
  revealjs:
    date: "Winter Term 2022"
    output-file: slides.html 
    include-after-body: ../assets/footer.html  
---

# Top {.slide-link-hidden .unlisted .unnumbered visibility="hidden"}

{{< include ../assets/_top.qmd >}}

# Motivation {.vertical-center background-color=blue background-image="../assets/bg.jpg"}

> XY *@weber2003problem*

# Evaluating research (papers) {visibility="hidden"}

When evaluating research as told in a paper or thesis, I recommend to pose following questions:

**Introduction**

- Is there a clear research question, is it justified, and addresses it a relevant and hitherto unresolved challenge?
- After reading the introduction, do you have the feeling that the paper is well structured, well grounded in theory, and follows a structured approach?
:::

**Theory**

- Does the paper/thesis contain a well-developed and articulated theoretical framework?
- Are the core concepts (technical terms) of the paper clearly defined?
- Is the argumentation logically persuasive?
- Is extant literature appropriately reflected in the paper, or are critical references missing?

**Method (for empirical papers)**

- Are the sample and variables appropriate?
- Is the data collection and data analysis method appropriate?
- Is internal and external validity sufficiently adressed?

**Results (for empirical papers)**

- Are the results reported in an understandable way?
- Are the results connected with the theory? 

**Contribution**

- Does the paper answer the research question?
- Is there a value-add (what do we learn more)?
- Are limitations critically reflected?
- Do the authors discuss the implications of the work for the scientific and practice community?

# Q&A {.vertical-center background-color=blue background-image="../assets/bg.jpg" .html-hidden .unlisted}

# Literature

::: {#refs}
:::
