---
title: "Administrivia 🧐"  
subtitle: "🧑‍🔬 DI in Industry (DIiI)"

format: 
  html:
    output-file: index.html
    include-after-body: ../assests/footer.html
  revealjs:
    output-file: slides.html
---

# Top{visibility="hidden" .slide-link-hidden .unlisted .unnumbered}

{{< include ../assets/_top.qmd >}}

__Printing/export:__ If you want to print or export the slides, open the slides, press `e` on your keyboard and then print (to pdf).

# General remarks

This course will be taught using traditional synchronous lectures. The focus of the live sessions is on discussing real world cases and developing theoretically-based explanations. In addition, you will do an original research on a digital innovation case on your own (see [assignment](../assignment/)).

It is very important that you prepare yourself for every session. You either need to work through teaching materials in advance or prepare to present the deliverables of your own case (see @tbl-schedule).

# Contents

This course offers you the possibility to learn about industry-specific challenges and how this influences the way of organizing, managing and communicating digital innovations, in particular:

:::{.incremental}
- __Specifics of industries__ (context, products, markets, obstacles, enablers)
- Industry-specific applicability and adaptations of __innovation strategies__
- __Methods__ for discovering need finding, ideation and prototyping of digital innovations
- __Case studies__ of digital innovation in industries
- __Theories__ that explain the mechanisms of digital innovations
:::

# Learning objectives

During this course, you should advance your skills in the following areas:

::: {.incremental}
- __Knowledge of various industries__ and their special characteristics 
- Understanding of the __specifics of managing digital innovations__ in these industries 
- Knowledge of __theoretical models__ that help to explain and manage these innovations
- Ability to analyze specificities and complexities of different industries 
- Capacity to __adapt digital innovation management methods__ and tools accordingly
- Ability to __clearly communicate conclusions__ and the underlying rationale
- Ability to evaluate new information and to question existing assumptions
- Expertise to __develop independent contributions__ to practical and theoretical discourse
:::

# Effort

You will gain 5 ECTS for this course. This equals approx. __150 hours workload__, of which you need most to pass the course.

::: {.incremental}
-	Live sessions (approx. 40 hours)
-	Preparation of the live sessions (approx. 20 hours)
-	Case research and writing (approx. 90 hours)
:::

::: {.fragment}
Please prepare your schedule accordingly.
:::

# Grading

The grade is based on the evaluation of the written case study (see [assignment](../assignment/)).

The presentations are mandatory but will not be graded individually.

# Schedule {.scrollable .smaller}

::: {.notes}
It is of importance that you prepare yourself for the sessions and work on the case study continually. Please prepare your schedule accordingly.
:::

::: {.column-page-right}

|Date        |Topic                                                                                   |Preparation      |
|:-----------|:---------------------------------------------------------------------------------------|:----------------|
|`03/23/2023`|Administrivia & introduction                                                            |-
|`03/30/2023`|Washington Post — digital transformation in media (BM & Lean UX canvas)                 |Reading
|`04/06/2023`|Threadless.com — creating value through online communities (crowdsourcing)              |Reading
|`04/13/2023`|__Interim presentation & coaching__: ideas                                              |Presentation
|`04/20/2023`|GEA — digital twin of a customer *guest speech* (digital twin)                          |-
|`04/27/2023`|__Interim presentation & coaching__: problem & solution                                 |Presentation
|`05/04/2023`|Deutsche Bank — innovation in finance, a safe bank? *guest speech* (agility)            |-
|`05/11/2023`|Excursion week (no lecture)                                                             |-
|`05/18/2023`|__Interim presentation & coaching__: industry & company                                 |Presentation
|`05/25/2023`|Springest —  IT-enabled holacratic organizations (self-managing organizations)          |Reading
|`05/25/2023`|*guest speech* (ambidexterity)                               
|`06/15/2023`|__Interim presentation & coaching__: approach & discussion                              |Presentation
|`06/22/2023`|Bricks block and flower pots — the future of construction *guest speech* (ambidexterity)|-
|`06/29/2023`|__Interim presentation & coaching__: discussion                                         |Presentation
|`07/06/2023`|SCHOTT — a two sided approach for DI (path constitution)                                |Presentation
|`07/06/2023`|__Deadline case study__                                                                 |Assignment

: Schedule summer term 2023 (may be subjected to changes) {#tbl-schedule}

:::

# Literature
::: {#refs}
:::