---
title: "K4 Datenbanken #1"
subtitle: "Grundzüge Informationsmanagement (GIM)"
lang: de-DE

format: 
  html:
    output-file: index.html
  revealjs:
    output-file: slides.html 
    include-after-body: ../assets/footer.html
---

# Top {visibility="hidden" .slide-link-hidden .unlisted}
[Folien](slides.html) / 
[Podcast](https://videoportal.hs-neu-ulm.de/Mediasite/Play/5e815720982f4d7c91d61ace65eb87dc1d)

# Motivation {.vertical-center background-color=blue}

---

>The world's most valuable resource is no longer oil, but data. *Steve Jobs (1997)*

. . .

Damit Daten Wert haben, müssen diese so gespeichert werden, dass sie effizient abgerufen und verwendet werden können. Die Grundkonzepte hierzu lernen Sie in diesem und im nächsten Kapitel kennen.

# Lernergebnisse

Nach dieser Einheit  

::: {.incremental}
- können Sie das Konzept der Datenintegration zur Vermeidung von Redundanzen und Inkonsistenzen erläutern und den Zusammenhang zu Datenbanksystemen (DBS) herstellen,
- können Sie das Vorgehen der Datenmodellierung beschreiben,
- verstehen Sie die Begriffe „Entity-Typ“, „Entity“, „Attribut“, „Schlüsselattribut“, „Relationship“ und „Kardinalität“ und können diese im Kontext der Datenmodellierung erläutern und 
- sind Sie in der Lage, ein einfaches Entity-Relationship-Diagramm (ERM) zu entwerfen und daraus Relationen abzuleiten.
:::

# Daten {.vertical-center background-color=blue}

## Begriffsbestimmung (Wiederholung)

__Daten__ sind Zeichen und Symbole, die einer bestimmten Syntax folgen. __Informationen__ sind Daten, die in einen sachlichen Kontext gesetzt sind. __Wissen__ entsteht, wenn Informationen interpretiert und bewertet werden. 

Ob aus Zeichen Daten, aus Daten Informationen und aus Informationen Wissen wird, ist abhängig vom Empfänger.

Expliziertes Wissen ist codiertes Wissen (bspw. in einem Buch). Impliziertes Wissen ist an die Person gebunden.


# ✏️ Aufgaben {.vertical-center background-color=blue}

## A1: Grundbegriffe

Erläutern Sie in der Kleingruppe reihum die Bedeutung der folgenden Begriffe.

# Literatur
::: {#refs}
:::