---
title: "Defense"  
subtitle: "How to present your work?"
lang: en-US

bibliography: ../assets/literature.bib

format: 
  html:
    output-file: index.html
  letterbox-revealjs:
    date: "Winter Term 2022"
    output-file: slides.html 
    include-before-body: ../assets/footer.html  
---

# Top {.slide-link-hidden .unlisted .unnumbered visibility="hidden"}

{{< include ../assets/_top.qmd >}}

# Motivation {.vertical-center background-color="#0333ff" background-image="../assets/bg.jpg"}

> Never let the facts get in the way of a good story. *Unknown, often attributed to Mark Twain*

# Introduction

If your paper is accepted to be presented at an conference, you need to deliver an **oral presentation of your work**.

. . .

If you want to obtain a university degree, you have to **defend your thesis**, usually in front of two or more examiners and possibly the interested public.

. . .

Both run very similarly:

:::{.incremental}
- You give your presentation (usually with slides)
- The committee and/or the public will ask questions about your research after you finished your presentation
:::

# Tipps to prepare

Here are a few tips on how to prepare for your thesis defense.

**Tell a convincing story**

:::{.notes}
- You can't present all you have done—**tell a convincing story** that portraits your research well and leave room for questions
- Do not plan for more then **1 slide per 2 minutes**, rather less
- It's a scientific presentation, so don't forget good practices (e.g., references)
- **Prepare properly**, practice your talk and make sure it fits the time limitations, you know your slides and you have opening and closing statements prepared
:::

**Design high-quality slides** [@hytonSlides]

:::{.notes}
- Do not plan for ideal conditions, make sure that everyone can see and read the contents
- Avoid fancy backgrounds on your slides
- Use readable typography (sans-serif, appropriate weight)
- Don't overload your slides (e.g., use only the upper two thirds of the slides, try to use not text at all)
- Put page numbers on your slides
:::

**Anticipate questions and prepare for them**

:::{.notes}
- **Sit at other defenses** of your supervisors to get a feeling for how and what they ask
- Do a **dry-run** in front of a friendly audience to spot topics that trigger questions
- Create a list of possible questions and prepare answers
- Prepare for questions you don't know the answer ("I don't know, but I would think [...]")
:::

**Have a backup plan**

Technology is unpredictable. Life is too. 

:::{.notes}
- Ask a trusted person to be ready to help you out
- Put your slides on a cloud storage
- Prepare handouts if technology fails
- If its a public presentation, I would bring an extra shirt ;-) 
:::


# Q&A {.vertical-center background-color="#0333ff" background-image="../assets/bg.jpg" .html-hidden .unlisted}

# Literature

::: {#refs}
:::
