---
title: "Administrivia  🧐"
subtitle: "IT as a Service Enabler (ITSE)"

bibliography: ../assets/literature.bib

date: 09.20.2023

format: 
  html:
    output-file: index.html
    margin-header: | 
      [Slides](slides.html){.btn .btn-primary target="blank"}
    format-links: false
  presentation-revealjs:
    output-file: slides.html 
    include-before-body: ../assets/footer.html  

---


# General remarks

Welcome to the `team weeger`!

. . .

Aspiration: solid scientific work (good chance to prepare for the bachelor thesis)

. . .

Important notes:

:::incremental
- __Effort__: 5 ECTS (approx. 120 h)
- __Language__ of the paper: English
- __Template__ for the final paper: see [here](../assets/template.docx)
- __Deadline:__ see @tbl-schedule
:::


# Topics

For more details on the topics, please see [topics](../topics/)

:::{.incremental .fade-in-then-semi-out}
- IT vs. OT — key differences *(structured literature review, 1-2 students)*
- Key challenges of IT/OT convergence *(structured literature review, 1-2 students)*
- Cyber security for industrial IoT (IIoT) *(structured literature review, 1-2 students)*
- Gamification as a strategy to promote sustainable behavior *(structured literature review, 1-2 students)*
- Models of human-AI collaboration in decision-making *(structured literature review, 1-2 students)*
:::

. . . 

For detailed requirements and evaluation criteria see [evaluation criteria](#evaluation)

# Formalities {.vertical-center background-color="#0333ff"}

## Seminar paper

Please use this [template](../assets/template.docx)

:::incremental
- The paper should be at least 10 pages long and must not exceed 15 pages (per student, excluding references)
- The paper must be uploaded as PDF in Moodle (deadline announced on moodle)
:::

## Meetings

You must attend at least the following meetings

:::incremental
- Kick-off (for date see @tbl-schedule)
- Review #1 (literature set, data analysis approach)
- Review #2 (findings)
- Interim presentation (for date see @tbl-schedule)
- Review #3 (paper draft)
:::

. . .

You are responsible for arranging the meetings (except the kick-off and the interim presentation) via [calendly](https://calendly.com/awe-hnu/office).

## Paper structure

Please follow this generic structure (level 1), sub-sections can be defined individually.


:::notes
You do neither need to add a table of contents nor a list of figures.
:::

**Introduction**

:::notes
-	Motivation (relevance, research gap)
-	Research question
:::

. . .

**Theoretical Background**

:::notes
-	Substantiation of the research gap
-	Introduction of the main theoretical concepts
:::

. . .

**Method**

:::notes
-	Presentation of the approach to data collection and analysis (how did you proceed, e.g., how the structured literature review was conducted or how the cases have been selected, data has been gained and analyzed) 
:::

**Findings**

:::notes
Descriptive results of the data analysis (“this is what we found out”).
(for literature reviews: concept-centric presentation, not author-based) 

- It only contains a description of findings (factual result reporting, past tense)
- It does not include a discussion or interpretation of the findings
:::

. . .

**Discussion**

:::notes
-	The answers to the research questions are presented and discussed
-	Evaluation of the findings considering existing literature (usually the literature discussed in the background section) 
-	Elaboration of theoretical and practical contributions of your work (e.g., what can be learned from your work on a theoretical and practical level)
-	Limitations and further research
:::

## Evaluation

The final paper is graded based on following criteria

Originality (passing criterion)
: The paper complies with the rules of good scientific practice, plagiarism will not be accepted.

. . .

Logic & consistency (80%)
: The red thread of the paper and the scientific approach is clearly recognizable and logically comprehensible.

:::notes
-	The topic is clearly outlined and motivated in the introduction
-	The research question is explicitly stated 
- All core terms are introduced and clearly defined 
-	The background/state of research is sufficiently substantiated
-	Data collection and analysis methods are clearly outlined and correctly applied
-	The results are comprehensible and offer novel answers to the research question 
-	The findings are critically discussed (contributions, implications for practice, own thoughts; literature is used)
:::

. . .

Composition and formalities (20%) 
: The paper follows scientific standards concering literature use, structure and language.

:::notes
-	A sufficient amount of predominantly scientific literature is used (peer-reviewed articles)
-	Literature is correctly and consistently cited 
-	Works is well structured (length and balance of chapters) and formal requirements are fulfilled (grammar, spelling, formatting)
-	The argumentation is well comprehensible (linguistic stylistics)
:::

# Jump start

Your first task: __get to know the literature__ (what is already known)

. . .

Focus on __scientific literature__ (peer-reviewed, high quality)

. . .

:::incremental
- Only scientific papers that are peer-reviewed
- Concerning the theoretical part: no practitioner papers (e.g., white papers from consulting firms), no books, not web-sources, etc. [^1]
- Recommendation is to focus the search on high-quality IS journals, such as
	- [Senior Scholars' Basket of Journals](https://aisnet.org/page/SeniorScholarBasket)
	- [A-ranked Journals in the VHB-JOURQUAL3 ranking](https://vhbonline.org/fileadmin/user_upload/JQ3_WI.pdf)
- Use __Web of Science__ or the __journals' archives__ to search for literature
- Use __EndNote__ to organize your literature
:::

[^1]: Practitioner papers and web-sources are only valid for empirical papers using secondary sources (e.g., desk research)

## Next steps

:::incremental
- Decide on your __topic__
- Work through the __literature review materials__ on Moodle
- __Read the recommended papers__; extract definitions for the main concepts
- Start your (structured) __literature search__ (i.e., use my queries)
- Get the full-texts of the identified articles
- __Organize the literature__ in EndNote
- Start __reading articles__, begin with the two that are cited mostly
- Write down what you have learned for your study (e.g., definitions, concepts, mechanisms)
- Write down your __questions__ for our next session
- Arrange an appointment to discuss your literature and/or approach
:::

# Schedule

| When             | What                      | Where   |
| ---------------- | ------------------------- | ------- |
| `23.10.23, 1 pm` | Kick-off meeting          | Zoom    |
| `20.12.23, 2 pm` | Interim presentations     | E7.1.01 |
| `26.01.24, 8 pm` | Deadline paper submission | Moodle  |

: Schedule winter term 2023/2024 (may be subjected to changes) {#tbl-schedule}

# References
::: {#refs}
:::