---
title: "Administrivia  🧐"
subtitle: "IT as a Service Enabler (ITSE)"

bibliography: ../assets/literature.bib

format: 
  html:
    output-file: index.html
  letterbox-revealjs:
    date: "Summer Term 2023"
    output-file: slides.html 
    include-before-body: ../assets/footer.html  
---

# Top{visibility="hidden" .slide-link-hidden .unlisted .unnumbered}

{{< include ../assets/_top.qmd >}}

# General remarks

Welcome to the `team weeger`!

. . .

Aspiration: solid scientific work (good chance to prepare for the BA)

. . .

Important notes:

:::{.incremental}
- __Effort__: 5 ECTS (approx. 120 h)
- __Language__ of the paper: English
- __Template__ for the final paper: see [here](../assets/template.docx)[^S]
- __Deadline:__ July 5 2023
:::

[^S]: No need to create a ToC, it is already fixed

# Topics

For more details on the topics, please see [topics](../topics/)

:::{.incremental .fade-in-then-semi-out}
- Analysis of the smart city app Ulm/Neu-Ulm *(theory-based evaluation, group-work Franz, Zeller, Geiger)*
- Analysis of Gamification Elements in a Smart City App *(theory-based analysis, tbd)*
- Use of secondary material and IS *(structured literature review, Langer)*
- Resource efficiency and IS *(structured literature review, Tausend)*
- Digitalization and sustainability in DAX 40 companies  *(empirical study, Zivalioglu, Tölke)*
:::

. . . 

For detailed requirements and evaluation criteria see [evaluation criteria](#evaluation)

# Formalities {.vertical-center background-color="#0333ff"}

## Seminar paper

Please use this [template](../assets/template.docx)

:::{.incremental}
- The paper should be at least 10 pages long and must not exceed 15 pages (per student, excluding references)
- The paper must be uploaded as PDF in Moodle (deadline announced on moodle)
:::

## Meetings

You must attend at least the following meetings

:::{.incremental}
- Kick-off (**March 31, 11:30 am**; invitation will follow after the topic selection deadline)
- Review #1 (literature, approach)
- Review #2 (findings)
- Review #3 (paper draft)
:::

. . .

You are responsible for arranging the meetings (except the kick-off) via [calendly](https://calendly.com/awe-hnu/office).

## Paper structure

Please follow this generic structure (level 1), sub-sections can be defined individually.


:::{.notes}
You do neither need to add a table of contents nor a list of figures.
:::

**Introduction**

:::{.notes}
-	Motivation (relevance, research gap)
-	Research question
:::

. . .

**Theoretical Background**

:::{.notes}
-	State of research (what is known, what is not yet known)
-	Introduction of the main theoretical concepts
:::

. . .

**Method**

:::{.notes}
-	Presentation of the approach to data collection and analysis (how did you proceed, e.g., how the structured literature review was conducted or how the cases have been selected, data has been gained and analyzed) 
Findings
-	Description of the results (what have you found out?)
(for literature reviews: concept-centric presentation, not author-based) 
:::

**Findings**

:::{.notes}
Descriptive results of the data analysis (“this is what we found out”).

- It only contains a description of findings (factual result reporting, past tense)
- It does not include a discussion or interpretation of the findings
:::

. . .

**Discussion**

:::{.notes}
-	The answers to the research questions are presented and discussed
-	Evaluation of the findings considering existing literature (usually the literature discussed in the background section) 
-	Elaboration of theoretical and practical contributions of your work (e.g., what can be learned from your work on a theoretical and practical level)
-	Limitations and further research
:::

## Evaluation

The final paper is graded based on following criteria

Originality (passing criterion)
: The paper complies with the rules of good scientific practice, plagiarism will not be accepted.

. . .

Logic & consistency (80%)
: The red thread of the paper and the scientific approach is clearly recognizable and logically comprehensible.

:::{.notes}
-	The topic is clearly outlined and motivated in the introduction
-	The research question is explicitly stated 
- All core terms are introduced and clearly defined 
-	The background/state of research is sufficiently substantiated
-	Data collection and analysis methods are clearly outlined and correctly applied
-	The results are comprehensible and offer novel answers to the research question 
-	The findings are critically discussed (contributions, implications for practice, own thoughts; literature is used)
:::

. . .

Composition and formalities (20%) 
: The paper follows scientific standards concering literature use, structure and language.

:::{.notes}
-	A sufficient amount of predominantly scientific literature is used (peer-reviewed articles)
-	Literature is correctly and consistently cited 
-	Works is well structured (length and balance of chapters) and formal requirements are fulfilled (grammar, spelling, formatting)
-	The argumentation is well comprehensible (linguistic stylistics)
:::

# Jump start

Your first task: __get to know the literature__ (what is already known)

. . .

Focus on __scientific literature__ (peer-reviewed, high quality)

. . .

:::{.incremental}
- Only scientific papers that are peer-reviewed
- Concerning the theoretical part: no practitioner papers (e.g., white papers from consulting firms), no books, not web-sources, etc. [^1]
- Recommendation is to focus the search on high-quality IS journals, either
	- [Senior Scholars' Basket of Journals](https://aisnet.org/page/SeniorScholarBasket)
	- [A-ranked Journals in the VHB-JOURQUAL3 ranking](https://vhbonline.org/fileadmin/user_upload/JQ3_WI.pdf)
:::

[^1]: Practitioner papers and web-sources are only valid for empirical papers using secondary sources (e.g., desk research)

. . .

Use __Web of Science__ or the __journals' archives__ to search for literature

. . .

Use __EndNote__ to organize your literature

## Next steps

:::{.incremental}
- Decide on your __topic__
- Work through the __literature review materials__ on Moodle
- __Read the recommended papers__; extract definitions for the main concepts
- Start your (structured) __literature search__ (e.g., with two to three journals)
- Get the full-texts of the identified articles
- __Organize the literature__ in EndNote
- Start __reading articles__, begin with the two that are cited mostly
- Write down what you have learned for your study (e.g., definitions, concepts, mechanisms)
- Write down your __questions__ for our next session
- Arrange an appointment to discuss your literature and/or approach
:::

# References
::: {#refs}
:::