---
title: "Administrivia 🧐"  
subtitle: "💎 Business Value Creation with IT (BVC)"
lang: en

author: "Andy Weeger & Arne Buchwald"
date: "03.04.2024"

bibliography: ../assets/literature.bib

format: 
  html:
    output-file: index.html
    margin-header: | 
      [Slides](slides.html){.btn .btn-primary target="blank"}
    format-links: false       
  presentation-revealjs:
    output-file: slides.html
    include-before-body: ../assets/footer.html
---



## Discussion {.html-hidden .unlisted .discussion-slide background-color=black}

:::{.large}
What to you **expect** from this course?
:::

# General remarks

In this course you will **develop a technological artifact** that has the potential **to create value** for a specific organisation (e.g. prototyping a new product, improving a process, supporting a decision). 

. . .

As to that, you

:::{.incremental}
- will apply your learning from your undergraduate degree as well as from the first semester of your Masters program; and you
- will also be introduced to current methodological and theoretical knowledge. This will help you to carry out the real-world problem and to reflect on the process and the results. 
:::

. . .

It is very important that you prepare yourself for the classes (see @tbl-schedule for details).

# Contents

To support understanding and transfer of topics, additional knowledge of core concepts and related methods will be tought, e.g.:

:::{.incremental}
- Business value sources and characteristics
- Essential aspects of IT/digital resources
- Identification of (customer) needs (e.g. Design Thinking)
- The generation and development of ideas
- Challenges in implementing digital innovations (changing, adopting & using)
- Capture and measurement of value from IT/digital innovations
:::

# Learning objectives

During this course, you should advance your skills in the following areas:

::: {.incremental}
- Understand __the mechanisms by which IT creates business value__
- __How to conceptualise, design and implement IT solutions__ that create value in a specific context.
- How to __apply and contextualise existing knowledge and understanding__ of disruptive technologies in the context of a specific organisational environment
- __Problem-solving skills__ to analyze the particularities and complexities of different project contexts
- __Reflecting on social and ethical responsibilities__ and making responsible decisions with incomplete or limited information 
:::

# Effort

You will gain 5 ECTS for this course. This equals approx. __150 hours workload__, of which you need most to pass the course.

::: {.incremental}
-	Live sessions (approx. 20 hours)
- Preparation of the live sessions (approx. 10 hours)
- Project work and documentation (remaining time)
:::

::: {.fragment}
Please prepare your schedule accordingly.
:::

# Grading

During the semester you will be required to work **within a group** on a **business challenge** posed by company partners.

. . .

You present your approach to the challenge and to create value by means of IT in a **presentation**.

. . .

You detail your approach and solution in a **seminar paper**.

. . .

Details regarding the assignment can be found [here](../assignment/).

. . .

:::{.smaller}
The grade is the weighted average of the group score (60%) and the individual contributions (40%); the individual contributions must be indicated.
:::

# Schedule {.scrollable .smaller}

::: {.notes}
It is of importance that you prepare yourself for the sessions and work on the case study continually. Please prepare your schedule accordingly.
:::

| Date         | Topic                             | Preparation                   |
|:-------------|:----------------------------------|:------------------------------|
| `18.03.2024` | Administrivia & introduction      | -
| `25.03.2024` | Challenges & hybrid intelligence  | -
| `01.04.2024` | *Easter Monday (no lecture)*      | -
| `05.04.2024` | Design thinking workshop^[Room: Innovation Space, Creative 2]| -
| `08.04.2024` | Value spaces framework            | Reading^[@henfridsson2018recombination]
| `15.04.2024` | Input (tbd) & team coaching       | Interim results, questions
| `22.04.2024` | Lightweight IT & team coaching    | Interim results, questions
| `29.04.2024` | Team coaching (optional)          | Interim results, questions
| `13.05.2024` | Communication input & coaching    | Interim results, questions
| `03.06.2024` | __Presentation__ & Feedback       | Presentation
| `01.07.2024` | __Deadline__: Paper               | Paper

: Schedule summer term 2024 (may be subjected to changes) {#tbl-schedule}

# Literature
::: {#refs}
:::