---
title: "Kurzpräsentation"
subtitle: "`DEM_1` DE1: Digitalisierung und Informationssysteme"
lang: de-DE

bibliography: ../assets/literature.bib

date: "08.15.2025"

format: 
  html:
    output-file: index.html
---

# Zielsetzung {visibility="hidden"}

Durch die Beschäftigung und Vorstellung eines Themas, mit dem sich digitale Unternehmen heute beschäftigen müssen, zeigen Sie, dass Sie in der Lage sind,

::: incremental
-   ein relevantes Konzept in der Gruppe selbständig zu erschließen,
-   **Grundkonzepte** anhand eines Beispiels zu erläutern,
-   **Treiber sowie die Potenziale der Digitalisierung** an einem Thema zu erkennen und zu beschreiben,
-   Zusammenhänge zu erfassen, auf den Punkt zu bringen und für andere verständlich zu erklären
:::

# Prüfungsleistung

Sie erstellen in einer Kleingruppe eine **Präsentation** zu einem definierten Konzept und zeichnen diese auf Video auf.

Die Präsentation hat zum Ziel, das Konzept kurz, prägnant und inhaltlich richtig zu erläutern. Zudem müssen Sie das Konzept mit den Lernzielen der Vorlesung verknüpfen und die relevanten Inhalte anhand des Beispiels vertiefen. Jedes Thema ist deshalb einer Einheit der Vorlesung zugeordnet.

::: small
Beispiel: Sie entscheiden sich für das Thema *Crowdsourcing*. Das Thema ist der Einheit Geschäftsmodelle zugeordnet. Dann könnten Sie anhand eines Crowdsourcing-Anbieters dessen Geschäftsmodell analysieren und vorstellen und somit das Wissen zu den Dimensionen von Geschäftsmodellen vertiefen.
:::

**Weitere Rahmenbedingungen**

-   Sie wählen die Themen per Moodle aus, die Sie bearbeiten möchten.
-   Aufgrund Ihrer Auswahl bilde ich Gruppen von **bis zu 2 Studierenden** per Thema.
-   Jede Gruppe **arbeitet gemeinsam an einer Präsentation**.
-   Sie organisieren sich in den Gruppen selbst und tragen Sorge dafür, dass jedes Gruppenmitglied gleich zur Prüfungsleistung beiträgt.
-   Die Kurzpräsentation muss **zwischen 6 und maximal 8 Minuten** lang sein.
-   Die Vorbereitungszeit beträgt ca. 4 Wochen. Sie können maximal 25 Punkte erzielen.
-   Das Video muss nicht geschnitten sein. Wenn Sie möchten, können Sie auch einen One-Shot per Handy aufzeichnen.
-   Das Video muss in einem lesbaren Format (Codec) rechtzeitig via Moodle hochgeladen werden (Deadline siehe [Zeitplan](../admin/#zeitplan)).
-   Zu dem Video laden Sie bitte ein Dokument hoch, aus dem Ihre Quellen hervorgehen. Es muss erkenntlich sein, welche Inhalte aus welcher Quelle stammen (entweder per textlicher Beschreibung oder Zeitangabe). Sie sind verantwortlich für die Richtigkeit der Inhalte und die Belege der Quellen.
-   Die Videos werden in der Vorlesung gezeigt und inhaltlich besprochen.

# Themen

::: column-page-right
| **Einheit** | **Themen**                 |                              |
|-------------|----------------------------|------------------------------|
| E1          | Digitale Patientenakte     | Datenschutzgrundverordnung   |
| E2          | Mixed Reality              | Metaverse                    |
| E3          | Edge Computing             | Hyperscaler                  |
| E4          | Internet of Things (IoT)   | Digitaler Zwilling           |
| E5          | Process Mining             | BPMN                         |
| E6          | Robotic Process Automation | Enterprise Service Bus (ESB) |
| E7          | KI Agenten                 | Data Lake                    |
:::

# Evaluationskriterien

-   **Inhalt:** das Thema wurde sachlich richtig vorgestellt
-   **Zusammenhänge:** die Verknüpfung zu den Lernzielen ist gut herausgearbeitet
-   **Lerneffekt:** die Präsentation erhöht das Verständnis des Vorlesungsstoffs
-   **Struktur:** ein roter Faden ist klar erkennbar und dient dem Verständnis
-   **Visualisierung:** die visuelle Darstellung ist aussagekräftig und zweckdienlich
-   **Kreativität:** die Präsentation überträgt den Inhalt in einer geschickten Form
-   **Sprache/Haltung:** die Vortragenden sind verständlich, sprechen angemessen, unterstreichen die Inhalte durch geeignete Stilmittel sowie Gestik und Mimik und wecken Interesse am Thema
-   **Quellen:** die Quellen der Inhalte sind deutilch erkennbar

# Q&A {.unlisted .html-hidden background-color="lightgrey" background-image="images/question.jpeg"}