---
title: "Assignment 📑"  
subtitle: "`MISC` Interpersonal Skills (IPS)"
lang: en-US

bibliography: ../assets/literature.bib

format: 
  html:
    output-file: index.html
  presentation-revealjs:
    author: "Antje Wild & Andy Weeger"
    output-file: slides.html
    include-before-body: ../assets/footer.html
---


# Task

You need to choose at least two topics in which you want to improve your interpersonal skills.

. . .

During the semester you will deeply reflect on these topics (based on the lectures and your own readings), take challenges that we present during the lectures, and try to improve.

. . .

At the end of the semester you will present a reflection on your personal “learning journey” with a focus on the challenges and theories presented and discussed during the lectures and/or with which you have been engaged.

. . .

You will chose one topic during the kick-off and another during the course of the module.

# Presentation

The presentation must reflect the contents of this course, extended literature and cover answers to following questions:

:::incremental
-	Which topics did you choose for your personal development and why?
-	What was your level of maturity in the chosen fields before the course? 
-	What challenges did you choose to grow in the field?
-	How can you explain the mode of action and effect(s) of the challenge(s)?[^1]
-	What changed during the 12 weeks?
-	What did you learn that you would recommend to others?
:::

[^1]: Why has it (not) worked; what are boundary conditions, what are the results of studies that have employed similar interventions, etc.; Please use further literature and reference peer reviewed studies wherever applicable.

 . . .

The presentation should take min. 8 minutes, max. 9 minutes; a short Q&A follows (approx. 4 minutes).

# Grading

The grading is not based on the total amount of challenges you completed or how many of them were on level 3. 

. . .

We take into account your learning journey, your development over the course and the reflection with regard to the scientific literature.

. . .

If you decide to only complete challenges on level 1, however, it might be hard to gather enough material for a good or excellent presentation at the end. 

. . .

We strongly recommend maintaining a learning dictionary and documenting your progress. Taking pictures throughout your journey can also be helpful when preparing your final presentation. 

# Q&A {.html-hidden .unlisted .vertical-center  background-color="#0333ff" background-image="images/bg.jpg"}