---
title: "Standards"  
subtitle: "What (common) frameworks are used in industry?"
lang: en-US

bibliography: ../assets/literature.bib

format: 
#  html:
#    output-file: index.html
  revealjs:
    date: "Winter Term 2022/23"
    output-file: slides.html 
    include-after-body: ../assets/footer.html
---

# Top{visibility="hidden" .slide-link-hidden .unlisted .unnumbered}

{{< include ../assets/_top.qmd >}}

# Motivation {.vertical-center background-color=blue background-image="../assets/bg.jpg"}

> IT organizations can draw on a variety of IT management frameworks to structure and optimize different aspects. Often, one framework is singled out and hailed as a panacea in any context. But caution is advised: Not every framework is suitable for every problem. *Peter Ratzer, Deloitte Partner*

# Introduction

Many different **frameworks** can be followed for organizing the management of information technology and applications. However, these often only cover a specific aspect of value creation by IT, such as strategy planning, delivery, sourcing, etc.

. . .

In this section, we will have a brief look at some frameworks or reference models, considered as **industry standards**, their foci and coverage of IT value creation.

. . .

Organizations often use more than one of these frameworks (or their proposed **methods** or best **practices**) to achieve their business goals.

## Discuss! {.html-hidden .unlisted .unnumbered .vertical-center background-color=blue background-image="../assets//bg.jpg"}

The terms *standard*, *framework*, *reference models*, *method*, and *best practices* are frequently used. How would you define them? How are they interrelated?

## Clarification of terms

### Standard

. . .

According to design science [@vom2020accumulation], a **standard** is an agreed artifact that results from a design process and describes a desired state of an area in reality. 

. . .

Standards can be regarded as “socio-economic constructs reflecting a balance of perspective between stakeholders” [@ahlemann2009project, p. 293].

----

### Frameworks and reference models

. . .

The artifact intended to become a standard is often called a **framework**, defined as “a construct of interlinked concepts […] in which each concept plays an integral role” [@jabareen2009framework, p. 51].

. . .

Management frameworks are often also labelled as **reference models** which are “abstract representations of domain knowledge […] useful for capturing prescriptive and descriptive design knowledge for sociotechnical problems” [@legner2020accumulating, p. 736].

----

### Methods and good practices

**Management methods** “guide choices within the ‘plan-act-control’ solution space of an organization in order to achieve certain (management) goals” [@winter2012construction, p. 68] and are often constituting components of management frameworks.

. . .

ISO describes **good practices** (or recommended practices) as “the best way” of doing something [@iso2009standardizationPractices, p. 3], thus, describes the attribute of a method (its normative or prescriptive character).

## Current state

As already discussed, the role of the IT function changes significantly due do the requirements posed by digital transformation.

. . .

>  “IT functions are required to cooperateproactively and early on with business departments to be able to develop and implement […] innovations jointly” [@urbach2019impact, p. 123]. 

. . .

However, due to the consensual nature of standards, contemporary ITM standards seem to offer few guidance for responding to new requirements, e.g.,

:::{.incremental}
- ITIL was updated with only minimal changes [@auth2021evolution]
- Many frameworks emphasize top-down alignment as well as high service quality at low cost and with low risk, resulting in lengthy planning cycles [@urbach2019impact]
:::

:::{.notes}
However, as pressure on IT to meet the challenges of digital transformation increased, so did the demand for new guidance on successful practices, spurring efforts by standards bodies and professional associations to improve existing standards and create additional ones  [@auth2021evolution].
:::

# Types

@auth2021evolution proposes to categorize the standards regarding the stages of evolution related to digital transformation:

. . .

Traditional IT management standards
: Standards established before digital transformation got momentum; mainly focus on improving efficiency, cost effectiveness, and service quality.

. . .

Related standards
: Standards that exist independently of IT management but are used there.

. . .

Digital technology management standards
: Standards that address digital transformation management or deal with related concepts (e.g., agile and lean).

. . .

Emerging standards
: Established concepts, frameworks, or practices that are not yet standardized.

## Reflect! {.html-hidden .unlisted .unnumbered .vertical-center background-color=blue background-image="../assets//bg.jpg"}

Which IT management standards, frameworks and concepts do you know? Which category would you assign them to? Why?

## Traditional IT management standards

ITIL, Cobit and CMMI are probably the most popular and best-known traditional IT management standards.

. . .

:::{.smaller}

| Short name | Long name/topic                   | Publ. year | Cur. year | Stand. org.  |
|------------|-----------------------------------|------------|-----------|--------------|
| CMMI       | Capability Maturity Model Integr. | 2001       | 2018      | CMMI Inst.   |
| COBIT      | Govern. of information & technol. | 1996       | 2018      | ISACA[^ISACA]|
| ITIL       | IT service management             | 1989       | 2019      | AXELOS       |
| ISO20000   | IT service management             | 2005       | 2018      | ISO/IEC      |
| ISO270xy   | Information security              | 2009       | 2020      | ISO/IEC      |
| ISO3850x   | IT governance                     | 2008       | 2015      | ISO/IEC      |
| TOGAF      | Enterprise architecture mgmt.     | 1995       | 2018      | Open Group   |
| ZeroOut    | Zero Outage (IT)                  | 2016       | 2020      | ZOIS[^ZOIS]  |

: Selection of traditional IT management standards according to @auth2021evolution [p. 8]

:::

[^ISACA]: Consortium for Service Innovation
[^ZOIS]: Zero Outage Industry Standard Ltd.

## Related standards

IT management related standards are related to project management, as well as quality, risk, organizational change, knowledge, and innovation management.

:::{.smaller}

| Short name | Long name/topic                  | Publ. year | Cur. year | Stand. org.  |
|------------|----------------------------------|------------|-----------|--------------|
| ACMP10     | Change management                | 2014       | 2014      | ACMP[^ACMP]  |
| ISO21500   | Project management               | 2005       | 2020      | ISO          |
| ISO22301   | Business continuity              | 2012       | 2019      | ISO          |
| ISO30401   | Knowledge management             | 2018       | 2018      | ISO          |
| ISO31000   | Risk management                  | 2009       | 2018      | ISO          |
| ISO56002   | Innovation management            | 2019       | 2019      | ISO          |
| ISO900x    | Quality management               | 1987       | 2018      | ISO          |
| PMBoK      | Project Mgmt. Body of Knowl.     | 1996       | 2017      | PMI[^PMI]    |
| PRINCE2    | Project management               | 1989       | 2017      | AXELOS       |

: Selection of IT management related standards according to @auth2021evolution [p. 8]

:::

[^ACMP]: Association of Change Management Professionals
[^PMI]: Project Management Institute

## Digital tech. management standards

:::{.smaller}

| Short name | Long name/topic                    | Publ. year | Cur. year | Stand. org.      |
|------------|------------------------------------|------------|-----------|------------------|
| AgileSHIFT | Scaling Agile                      | 2018       | 2018      | AXELOS           |
| DA         | Disciplined Agile (hybrid)         | 2015       | 2018      | PMI              |
| DPBoK      | Digital Practitioner Body of Know. | 2019       | 2019      | Open Group       |
| FitSM      | Lean IT service management         | 2015       | 2015      | ITEMO            |
| IT4IT      | IT reference architecture          | 2015       | 2017      | Open Group       |
| LeSS       | Large-Scale Scrum                  | 2013       | 2015      | The Less Co.     |
| Nexus      | Scaling Scrum                      | 2015       | 2018      | Scrum.org        |
| P2Agile    | PRINCE2 Agile (hybrid)             | 2015       | 2015      | AXELOS           |
| Resilia    | IT ("cyber") resilience            | 2015       | 2015      | AXELOS           |
| SAFe       | Scaled Agile Framework             | 2011       | 2020      | Scal. Ag., Inc.  |
| Scrum      | Agile product development          | 1995       | 2017      | Scrum.org        |
| TBM        | Technology Business Management     | 2016       | 2016      | TBM Council      |
| VeriSM     | IT service management              | 2017       | 2017      | IFDC[^IFDC]      |

: Selection of digital technology management standards according to @auth2021evolution [p. 8]

:::

[^IFDC]: International Foundation for Digital Competences

## Emerging standards

:::{.smaller}

| Short name | Long name/topic                  | Publ. year | Cur. year | Stand. org.       |
|------------|----------------------------------|------------|-----------|-------------------|
| BMC        | Business Model Canvas            | 2005       | 2015      | -                 |
| CyBoK      | Cyber Security Body of Knowl.    | 2020       | 2020      | Univ. of Bristol  |
| DevOps     | Development & operations         | 2009       | n/a       | (DevOps Inst.)    |
| DesThink   | Design Thinking                  | 1991       | n/a       | (d.school)        |
| Flow       | Flow Framework (IT value stream) | 2018       | 2018      | Tasktop           |
| ITR24586   | Agile/DevOps                     | n/a        | n/a       | ISO/IEC           |
| Lean IT    | Lean IT                          | 2015       | n/a       | LITA16            |
| Spotify    | Scaling agile                    | 2014       | 2014      | Spotify           |
| SRE        | Site Reliability Engineering     | 2016       | n/a       | (DevOps Inst.)    |

: Selection of emerging standards according to @auth2021evolution [p. 8]

:::

. . .

Their further development to *formal standards* is still uncertain.

# Subject-based classification

@auth2021evolution analyzed the main topics of the standards and proposed following subject-based classification.

#### Governance

- Cobit
- TBM
- ISO31000
- ISO3850x

#### Security & privacy

- ISO270xy
- Resilia
- CyBoK

#### Quality Management

- ISO900x

#### Knowledge Management

- ISO30401

#### Enterprise Architecture Management

- IT4IT
- TOGAF

#### Service Management

- CMMI
- FitSM
- ITIL
- ISO20000
- VeriSM
- ZeroOut



# Q&A {.html-hidden .unlisted .vertical-center background-color=blue background-image="../assets/bg.jpg"}

# Literature

:::{.refs}
:::