---
title: "Administrivia 🧐"  
subtitle: "`MA` Interpersonal Skills (IPS)"
lang: en-US

bibliography: ../assets/literature.bib

format: 
  html:
    output-file: index.html
  revealjs:
    author: "Antje Wild & Andy Weeger"
    output-file: slides.html 
    include-after-body: ../assets/footer.html
---

# Top{visibility="hidden" .slide-link-hidden .unlisted .unnumbered}

<!-- LTeX: language=en-US -->

{{< include ../assets/_top.qmd >}}

__Printing/export:__ If you want to print or export the slides, open the slides, press `e` on your keyboard and then print (to pdf).

# Motivation {.vertical-center background-color=blue background-image="images/bg.jpg"}

> Your career success in the workplace of today—independent of technical expertise—depends on the quality of your people skills. *Max Messmer, American author*

:::{.notes}
This course is designed to prepare you for a future role in cross-functional functions and (leadership) positions by helping to lead yourselve and understand and efficiently shape interpersonal interactions and conflicts in organizations.
:::

# Learning outcomes

Upon successful completion of this course, you will have advanced knowledge and skills in following areas

:::{.incremental}
- theories explaining __interpersonal interaction__ in business contexts,
- __conflict in organizations__ and the strategies to resolve it,
- __self-leadership__ and __teamwork__ including the challenges of (virtual) collaboration within and between disciplines
- __emotional intelligence__ and resilience,
- __understanding of own and others' behavior__ in various settings, 
- __convincing communication__ of ideas within professional business settings, and 
- ethical dimensions of interpersonal ineraction.
:::

# Topics {.scrollable .smaller}

| Unit | Topic             | Title                                                        |
|------|-------------------|--------------------------------------------------------------|
| 1    | **Kick-off**      | How to get most out of this course?                          |
| 2    | **Career**        | How to get so good   they can't ignore you?                  |
| 3    | **Productivity**  | How can I get the most out of my time?                       |
| 4    |                   | How can I fight disctraction temptation and procrastination? |
| 5    | **Change**        | How to change things when change is hard?                    |
| 6    | **Resilience**    | How to cope with failure?                                    |
| 7    | **Communication** | How to give valuable feedback and handle conflict?           |
| 8    | **Collaboration** | How to measure what matters?                                 |
| 9    |                   | How to do it all online?                                     |
| 10   | **Culture**       | How can I get along with other cultures?                     |
| 11   | **Happiness**     | Ho can I become happier?                                     |

# Learning set-up

This course combines (virtual) __classroom teaching__ (approx on third of the time) and __self-learning components__ (challenges, personal studies) — engagement in both is required to achieve the learning outcomes.

. . .

The focus of the __teachiung sessions__ is on giving input to each topics including theoretical groundings, examples, cases, and exercises for reflection.


. . .

The will be a reading list for every topic, which serves as starting point for your __personal study.__

. . .

There are __challenges__ for each topic, which are designed to help you to get on and facilitate your learning journey.

. . .

The callenges and your personal study based are essential tools for preparing the final [presentation](../assignment/).


## Learning material

We will provide

:::{.incremental}
-	__lecture notes__ for each topic including theoretical groundings, examples, cases, questions for reflection, etc.;
-	three __challenges__ on three levels of difficulty for each topic;  
    * __level 1 challenges:__ impetus to reflection (reflect)
    * __level 2 challenges:__ getting into action (change)
    * __level 3 challenges:__ leaving the comfort zone (grow)
-	and __reading lists__ as starting points for your personal study
:::

:::{.notes}
:::{.callout-note}
### Challenges
The challenges are designed to help you to get on and facilitate your learning journey. Also, they are essential tools for preparing the final presentation. We strongly recommend to take up the challenges in the topics you chose at least up to level 2. However, ultimate growth and fun might only start with level 3 challenges. You are also allowed to create your own challenges. 
:::
:::


## Effort

You will gain 5 ECTS for this course. This equals approx. __125 hours workload__, which you need to pass the course.

::: {.incremental}
- Presence-teaching sessions: __approx. 35 hours__ (12 sessions)
- Challenges, reflection, research, presentation: __many hours ;-)__
:::

. . .

Please prepare your schedule accordingly.

## Grading { visibility = "hidden"}

The course will be graded by means of a [final presentation](../assignment/) at the end of the semester. 

. . .

The presentation is a reflection on your personal “learning journey” in at least two of the topics with a focus on the challenges and theories presented and discussed during the lecture. 

. . .

You will chose one topic during the kick-off and another during the course of the module.

# Schedule {.scrollable .smaller}

:::{.notes}
If not noted otherwise, the lecture starts on 2 pm and ends 5.15 pm.
:::

::: {.column-page-right}

|Date                  |Topic                          |Lecturer      | Location  |
|:---------------------|:------------------------------|:-------------|:----------|
|`Tu, 27/09/2022`      |Kick-off                       |Wild & Weeger |E5.1.08, Zoom
|`We, 29/09/2022`      |Career                         |Wild          |Zoom
|`Th, 06/10/2022`      |Productivity #1                |Wild          |Zoom
|`Th, 13/10/2022`      |Productivity #2                |Weeger        |A.1.58[^5]
|`We, 19/10/2022`[^1]  |Change                         |Weeger        |A.1.58[^5]
|`Th, 27/10/2022`      |Resilience                     |Weeger        |A.1.58[^5]
|`Th, 03/11/2022`      |Communication                  |Weeger        |A.1.58[^5]
|`Th, 10/11/2022`      |Collaboration #1               |Weeger        |A.1.58[^5]
|`Th, 11/11/2022`[^2]  |Culture                        |Rappl         |A.1.58[^5]
|`Th, 24/11/2022`      |Collaboration #2               |Wild          |Zoom
|`Th, 01/12/2022`      |Happiness                      |Wild          |Zoom
|`Fr, 16/12/2022`[^3]  |Final presentations            |Wild & Weeger |A.1.58


: Schedule winter term 2022 (may be subjected to changes) {#tbl-schedule}

:::

[^1]: Takes place from 1 to 3:30 pm
[^2]: Takes place from 9.45 am to 5:15 pm (all day)
[^3]: Takes place from 8 am to 6 pm (all day). We plan with 5 slots, 90 minutes each. In each slot, 6 students do their final presentation
[^4]: There will be an online option

# Q&A {.html-hidden .unlisted .vertical-center background-color=blue background-image="images/bg.jpg"}