project:
  output-dir: docs
  type: website
  resources: lib

website:
  title: "Intro to Artificial Intelligence 🧠"
  page-navigation: true
  search: false
  theme: clean
  site-url: https://awe-hnu.github.io
  repo-url: https://github.com/awe-hnu/awe-hnu.github.io

  sidebar:
    - id: nav
      title: Intro to AI
      style: docked
      collapse-level: 1
      align: left
      contents:
        - text: "Administrivia"
          file: administrivia.md

bibliography: bibliography/bibliography.bib

format:   
  html:
    mainfont: basier_squareregular
    monofont: basier_squarermono
    linkcolor: "#0333ff"
    fontcolor: black
    toc: true
    code-copy: true
    code-overflow: wrap
    theme:
      - theme/html.scss
  revealjs:
    theme: theme/slides.scss
    transition: slide
    menu: true
    disable-layout: true
    slide-number: c
    citations-hover: true
    include-after-body: assets/footer.html
    self-contained: false
    title-slide-attributes: 
      data-background-color: '#0333ff'     

filters:
  - quarto