---
title: "Topics"
subtitle: "IT as a Service Enabler (ITSE)"

bibliography: ../assets/literature.bib

format: 
  html:
    output-file: index.html
  letterbox-revealjs:

    output-file: slides.html 
    include-before-body: ../assets/footer.html  
---

# Top{visibility="hidden" .slide-link-hidden .unlisted .unnumbered}

{{< include ../assets/_top.qmd >}}

# Overview

**General remark:** When you work on the topics, your ambition should be to produce a solid scientific paper (good way to prepare for the BA)

. . .

Topics:

:::{.incremental}
- Analysis of the smart city app Ulm/Neu-Ulm *(theory-based evaluation, 3 students)*
- Analysis of Gamification Elements in a Smart City App *(theory-based analysis, 1 student)*
- Use of secondary material and IS *(structured literature review, 1 student)*
- Resource efficiency and IS *(structured literature review, 1 student)*
- Digitalization and sustainability in the DAX 40 companies  *(empiciral study, 2 students)*
:::

## Analysis of Smart City App 

Your task is to test and evaluate a prototype of a smart city app for Ulm/Neu-Ulm. The aim of the app is, among others, to promote sustainable mobility forms like public transportation or biking. As the prototype is in German, respective language skills are required. 
As to that you will adopt a design-science approach and:

-	Review the literature and summarize the knowledge on mobility apps and platforms that are used to induce behavioral change. 
-	Analyze the prototype app in regards to its design principles based on prior literature.
-	Test the app and its effects, e.g. among students.
-	Deduct learnings and update the design principles based on the evaluation.

The focus of this work should be on the test and evaluation phase.
You will report and discuss your findings in a joint paper.


:::{.notes}
#### Starting points for reading

- @hevner2008design
- @hevner2010design
- @hein2018towards
- @lieberoth2018selective
- @gunther2020behavioral

:::

## Analysis of Gamification Elements in a Smart City App

Your task is to analyze the gamification elements of a prototype of a smart city app for Ulm/Neu-Ulm. The aim of the app is, among others, to promote sustainable mobility forms like public transportation or biking. As the prototype is in German, respective language skills are required. 

In you analysis you are required to:

- Review the literature and summarize the knowledge on gamification elements in mobility apps and mobility platforms to promote more sustainable mobility behavior.
- Analyze the prototype app in regards to its gamification elements based on prior literature.
- Deduct potential starting points for an optimization and further development of the gamification elements in the app based on the extant literature.

You will report and discuss your findings in a research paper.

:::{.notes}
#### Starting points for reading

- @lieberoth2018selective
- @nakashima2017gamification
- @cellina2019large
:::


## Use of secondary material and IS

Your task is to review current literature to answer following research question: "How can IS help increase the use of secondary materials in
new product offerings?"

As to that, you will conduct a structured literature review following [@webster2002analyzing][^initialSearchQueryA] and analyze the included papers and synthesize the existing knowledge.

You will report and discuss your findings in a paper.

:::{.notes}

#### Starting points for reading

Please read following papers to get familiar with the overall topic

- @zeiss2021mobilising
- @van2023sustainable

:::

[^initialSearchQueryA]: Initial search query in [Web of Science](https://www-webofscience-com.ezproxy.hnu.de): ´TS = (("information systems" OR "information technology") AND ("circular economy"  OR "sustainability") AND "recycling")´

## Resource efficiency and IS

Your task is to review current literature to answer following research question: "How can the use of (innovative) IT improve resource efficiency?"

As to that, you will conduct a structured literature review following [@webster2002analyzing][^initialSearchQueryB] and analyze the included papers and synthesize the existing knowledge.

You will report and discuss your findings in a paper.

:::{.notes}

#### Starting points for reading

Please read following papers to get familiar with the overall topic

- @zeiss2021mobilising
- @van2023sustainable

:::

[^initialSearchQueryB]: Initial search query in [Web of Science](https://www-webofscience-com.ezproxy.hnu.de): ´TS = ("resource efficiency" AND ("information technology" OR "information system"))´

## Digitalization and sustainability in DAX 40 companies

Your task is to review the current practice of leading German companies to combine digitalization and sustainability to answer following research question: "How do leading companies use digitalization initiatives to improve sustainability?"

You will review IS literature to identify ways to improve sustainability by IT, analyze the annual (sustainability) reports of the leading 40 DAX companies within the last three years, press releases and newspaper articles and identify if the companies relate their digilization initiatives to sustainability efforts and how they use digitalization to improve social, economical, and environmental sustainability.

You will report and discuss your findings in **a joint paper**.

:::{.notes}

#### Starting points for reading

Please read following papers to get familiar with the overall topic and the method

- @zeiss2021mobilising
- @van2023sustainable

:::

# References
::: {#refs}
:::