---
title: "Administrivia"  
subtitle: "Digital Leadership (DL)"
lang: en

bibliography: ../assets/literature.bib

date: "02.21.2026"

title-slide-attributes:

  data-background-size: cover
  data-background-opacity: "1"
  data-background-color: '#0333ff'

format: 
  html:
    output-file: index.html
    margin-header: | 
      [Slides](slides.html){.btn .btn-primary target="blank"}
    format-links: false       
  presentation-revealjs:
    output-file: slides.html
    include-before-body: ../assets/footer.html
---

# Motivation

:::notes
Society often associates leaders with individuals that have grandiose titles, a large corner office, and make world-changing decisions. Thus, many people shy away from identifying themselves as a leader. However, real leadership can be seen most clearly in the small moments throughout the day. 

> Leadership is about behaving in a way that makes the life of another person better than before you arrived. *Drew Dudley*
:::

:::html-hidden
<div style="max-width:750px"><div style="position:relative;height:0;padding-bottom:56.25%"><iframe src="https://embed.ted.com/talks/drew_dudley_everyday_leadership" width="750px" height="380px" title="Everyday leadership" style="position:absolute;left:0;top:0;width:100%;height:100%"  frameborder="0" scrolling="no" allowfullscreen onload="window.parent.postMessage('iframeLoaded', 'https://embed.ted.com')"></iframe></div></div>
:::

# Discussion {.html-hidden .unlisted .discussion-slide}

:::large
What do you expect to learn in this course?
:::

# General remarks

:::html-hidden
:::medium
You will deepen your understanding of leadership in the digital age.
:::

You will

:::incremental
- read papers to get a theoretical foundation,
- apply findings in exercises,
- research and reflect on a leader, and
- present your findings
:::
:::

:::notes
This module helps you to deepen your understanding of the requirements of leadership in the digital age.

To this end, you will read a series of **scientific papers**, consolidate and deepen your knowledge in **exercises** as well as while working on your **assignment** and, in the best case, increase your leadershik skills. As a **graded exam assignment**, you will research on a (digital) leader and make sense on her/his behavior using a scientific theory related to leadership and present your findings in a presentation to your fellow students.

It is very important that you prepare yourself for the classes (see @tbl-schedule for details).
:::

# Contents

We touch base on following topics to increase understanding of challenges in different leadership roles and situations and to get to know tools to deal with these:

:::html-hidden
:::medium
[Specifics of leading in the digital age, ]{.fragment .fade-in-then-semi-out}
[basics of leadership, ]{.fragment .fade-in-then-semi-out}
[theories and theoretical concepts, ]{.fragment .fade-in-then-semi-out}
[and digital leadership tools]{.fragment .fade-in-then-semi-out}
:::
:::

:::notes
- __Specifics of leading in the digital age__ (e.g., VUCA, role of technology, etc.)
- __Basics of leadership__ (e.g., motivation, leadership characteristics, etc.)
- __Theories and theoretical concepts__ (e.g., psychological safety, social capital theory, etc.)
- __Digital leadership tools__ (e.g., storytelling and workshop tactics)
:::

# Learning objectives

During this course, you should improve your ability to consciously use, reflect on and further develop your leadership skills in your day-to-day work, in particular with regard to

::: incremental
- __leadership requirements__ in the context of digital transformation,
- identification of and reflection on __challenges and opportunities in your own leadership role__,
- understanding of the facets of different __personality types__,
- basic understanding of characteristics of __sustainable organizational systems__, and
- lead hierarchically and laterally using __digital leadership tools__.
:::

# Effort

You will gain 5 ECTS for this course. This equals approx. __150 hours workload__, of which you need most to pass the course.

::: incremental
-	Classes (approx. 30 hours)
- Preparation and follow-up (approx. 10 hours)
- Preparation of the presentation (remaining time)
:::

::: fragment
Please prepare your schedule accordingly.
:::

# Schedule {.scrollable .smaller}

::: notes
It is of importance that you prepare yourself for the sessions and work on the case study continually. Please prepare your schedule accordingly.
:::

| Date       | Topic                                                    | Preparation          |
|:-----------|:---------------------------------------------------------|:---------------------|
| 25.03.2026 | **Administrivia & Foundations**                          | —
| 01.04.2026 | **Leader**                                               | [Homework](../leader/index.qmd#homework)
| 07.04.2026 | **Deadline** Leader Shortlist                            | Shortlist
| 08.04.2026 | **Adaptive Behavior** & Assignmetn of Leaders            | [Homework](../adaptive-behavior/index.qmd#homework)
| 15.04.2026 | **Environments**                                         | [Homework](../environments/index.qmd#homework)
| 22.04.2026 | **Team**                                                 | [Homework](../team/index.qmd#homework)
| 29.04.2026 | **Conflict & Power**                                     | [Homework](../conflict-power/index.qmd#homework)
| 06.05.2026 | **Stakeholder**                                          | [Homework](../stakeholder/index.qmd#homework)
| 13.05.2026 | **Context**                                              | [Homework](../context/index.qmd#homework)
| 20.05.2026 | **Communication** (InnovationSpace, Creative 2)          | —
| 07.06.2026 | **Deadline:** Slides Upload                              | Slides
| 10.06.2026 | **Student Presentations** — Session #1                   | —
| 17.06.2026 | **Student Presentations** — Session #2                   | —
| 24.06.2026 | **Student Presentations** — Session #3                   | —
| 01.07.2026 | **Student Presentations** — Session #4                   | —
| 08.07.2026 | **Retrospective Workshop** (InnovationSpace, Creative 2) | —

: Schedule summer term 2026 (may be subjected to changes) {#tbl-schedule}

# {.html-hidden .unlisted background-color=black background-iframe="https://www.mentimeter.com/app/presentation/aly6sweyozwy1ke9ag9x7topk535qdno/zsy6drk9a3kq"}

# Literature

::: {#refs}
:::
