---
title: "Administratives 🧐"
subtitle: "`IMUK_1` Grundzüge Informationsmanagement (GIM)"
lang: de-DE

bibliography: ../assets/literature.bib

format: 
  html:
    output-file: index.html
    margin-header: | 
      [Slides](slides.html)
    format-links: false    
  presentation-revealjs:
    output-file: slides.html 
    include-before-body: ../assets/footer.html
---

# {.html-hidden .unlisted background-color=black background-iframe="https://www.mentimeter.com/app/presentation/aly6sweyozwy1ke9ag9x7topk535qdno/embed"}

# Allgemeines {visibility="hidden"}

Im Orientierungsmodul "Grundzüge Informationsmanagement" erhalten Sie einen Überblick über die IT-bezogenen Themenbereiche Ihres Studiums.

Der Kurs basiert auf einem Blended Learning Konzept (Flipped Classroom). Das bedeutet, dass Sie zu Hause die Inhalte der Vorlesung vorbereiten. Hierzu sollten Sie das Skript zum Thema durcharbeiten. Für fast alle Vorlesungen habe ich zudem kurze Videos mit weiteren Erläuterungen aufgezeichnet.

In den gemeinsamen Live-Sessions reflektieren und vertiefen wir dann die Inhalte anhand von Übungen (oft in Kleingruppen). Manche Übungen sollten Sie nach den Sessions eigenständig bearbeiten.

# {.html-hidden .unlisted background-color=black background-iframe="https://www.mentimeter.com/app/presentation/aly6sweyozwy1ke9ag9x7topk535qdno/embed"}

# Lernziele

Nach der Veranstaltung sollten Sie unter anderem[^1] in der Lage sein,

:::{.incremental}
- Grundbegriffe und wesentliche __Konzepte des Informationsmanagements__ zu benennen und anhand von Beispielen zu erläutern,
- wesentliche Eigenschaften des __digitalen Zeitalters__ und Komponenten des betrieblichen Informationsmanagements zu beschreiben und zu klassifizieren,
- Treiber und Potenziale der __Digitalisierung von Unternehmen und Märkten__ zu benennen und deren Zusammenhänge zu erläutern,
- ausgewählte __Methoden des Informationsmanagements__ und zugehörige digitale Werkzeuge anzuwenden,
- eigenverantwortlich mit Lernangeboten umzugehen und wirksame __Lernstrategien__ zu entwickeln und
- den __Einsatz von digitalen Werkzeugen__ in Unternehmen zu reflektieren.
:::

[^1]: Vollständige Liste der Lernziele siehe Modulbeschreibung 

# Struktur der Vorlesung {.vertical-center background-color="#0333ff"}

## Einheiten

Die Vorlesung ist in 12 Kapitel (`K`) gegliedert

:::{.incremental .smaller}
- `K1` __Einführung__ — Was sind Grundkonzepte des Informationsmanagements?
- `K2` __Digitale Transformation__ — Was verändert sich durch die Digitalisierung?
- `K3` __Technologie__ — Was ist die Basis von Informationssystemen?
- `K4` __Informationssysteme__ — Welche Rolle spielen betriebliche Informationssysteme?
- `K5` __Prozesse__ — Wie werden Abläufe im Unternehmen gesteuert?
- `K6` __Daten__ — Wie entstehen nützliche Informationen?
- `K7` __Integration__ — Was ist integrierte Informationsverarbeitung? 
- `K8` __Anwendungssysteme__ — Welches sind die wichtige Anwendungssysteme?
- `K9` __Scale-Up__ - Wie spielen die Elemente zusammen?
- `K10` __Implementierung__ — Wie entstehen Informationssysteme?
- `K11` __IT-Management__ — Wie werden Informationssysteme gesteuert?
- `K12` __Geschäftsmodelle__ — Wie verändern sich Märkte?
:::

## Lernmaterialien

Jedes Kapitel enthält folgende Lernmaterialien: 

:::{.incremental}
-	__Vorlesungsskript__ *(Wiki)*
-	__Videos__ *(Kommentare zu ausgewählten Inhalten)*
- __Big Picture__ *(Visuelle Zusammenfassung der Kapitel)*
-	__Übungen__ *(Wiederholung, Reflektion und Vertiefung)*
- Referenz zu weiterführender __Literatur__ *(insbesondere @mertens2016grundzuge, @lemke2017einfuhrung und @bachle2021einfuhrung, alle als E-Books verfügbar)*
-	__Moodle-Quizze__
:::

:::{.fragment}
Alle Inhalte sind prüfungsrelevant.
:::

## Ablauf und Aufwände

Der Kurs basiert auf einem Blended Learning Konzept („Flipped Classroom“)

:::{.incremental}
- Sie erarbeiten sich die Inhalte im __Selbststudium__ *(12 x ca. 2,5 h)*
- Wir wiederholen und vertiefen in der __Veranstaltung__ *(13 x ca. 2,5 h)*
  - Zusammenfassung der Inhalte (Big Picture)
  - Antwort auf Ihre Fragen (Q&A)
  - Übungen (oft in Kleingruppen)
- In der __Portfolio-Prüfung__ wenden Sie Ihr Wissen an
  - Bearbeitung von 10 Quizzen *(ca. 3 h)*
  - Bearbeitung Übungsblatts *(ca. 2 h)*
  - Prüfung *(restliche Zeit)*
:::

:::{.notes}
Der Kurs ist mit 4 ECTS gewichtet. Rechnen Sie deshalb mit einem Arbeitsaufwand von ca. 100 h. 

Die ungefähre Verteilung des Arbeitsaufwands entnehmen Sie bitte obiger Auflistung. Die restliche Zeit ist für das Selbststudium, insbesondere die Vorbereitung auf die Abschlussprüfung vorgesehen.

Die Erfahrung aus vorangegangen Kursen lehrt, dass ohne die Teilnahme an den Live-Sessions und die Bearbeitung der Übungen das Bestehen des Kurses mit einer ordentlichen Note kaum möglich ist.

Dieses __Lern-Set-Up__ soll Sie dazu befähigen

-	eigenverantwortlich mit Lernangeboten umzugehen und wirksame Lernstrategien zu entwickeln,
-	den Einsatz von digitalen Werkzeugen in Unternehmen gesellschaftskritisch zu reflektieren,
-	Zusammenhänge zu erfassen, auf den Punkt zu bringen und für andere verständlich zu erklären
:::

## Prüfungsleistung

Die Vorlesung wird anhand einer __Portfolio-Prüfung__ bewertet

:::{.incremental}
- Die Portfolio-Prüfung besteht aus vier unterschiedlichen Teilen:
  - __10 Quizze__ (variierende Bearbeitungszeit, 20 Punkte)[^2]
  - __Übungsblatt__ (ca. 2 Tage Bearbeitungszeit, 25 Punkte)
  - __Klausur__ (45 Minuten Bearbeitungszeit, 45 Punkte)
- Die Gesamtzahl der in diesem Kurs erreichbaren Punkte beträgt 90. Sie benötigen __45 Punkte zum Bestehen__.
:::

[^2]: Bitte beachten Sie, dass die Quizze nur innerhalb eines definierten Zeitraums (variiert pro Quiz, siehe Moodle) absolviert werden können.

## Zeitplan {.scrollable .smaller}

::: {.notes}
Es ist wichtig, dass Sie sich auf die Live-Sessions vorbereiten, die Inhalte kontinuierlich reflektieren, die Übungen durchführen und Fragen stellen.
:::

| Datum        | Thema                                                   | Prüfungsteil    |
|:-------------|:--------------------------------------------------------|:----------------|
| `23.03.2023` | `K1` Einführung                                         | -
| `30.03.2023` | `K2` Digitale Transformation                            | -
| `06.04.2023` | `K3` Technologie                                        | -
| `13.04.2023` | `K4` Informationssysteme                                | -
| `20.04.2023` | `K5` Prozesse                                           | -
| `27.04.2023` | `K6` Daten                                              | Quizze K1-K6
| `04.05.2023` | `K7` Integration                                        | Quiz K7
| `11.05.2023` | `K8` Anwendungssysteme                                  | Quiz K8
| `25.05.2023` | `K9` ScaleUp! & __Ausgabe Übungsblatt__                 | -
| `26.05.2023` | __Deadline Übungsblatt__                                | Übungsblatt
| `15.06.2023` | `K10` Implementierung                                   | Quiz K9
| `22.06.2023` | `K11` IT-Management                                     | Quiz K10
| `29.06.2023` | `K12` Geschäftsmodelle                                  | Quiz K11
| `06.07.2023` | Wrap-Up & Prüfungsvorbereitung                          | Quiz K12

: Zeitplan Sommersemester 2023 (Änderungen vorbehalten) {#tbl-schedule}

# {.html-hidden .unlisted background-color=black background-iframe="https://www.mentimeter.com/app/presentation/aly6sweyozwy1ke9ag9x7topk535qdno/zsy6drk9a3kq"}

## Nicht prograstinieren {background-color=black .unlisted .html-hidden}

<iframe src="https://embed.ted.com/talks/lang/en/tim_urban_inside_the_mind_of_a_master_procrastinator" width="854" height="400" frameborder="0" scrolling="no" allowfullscreen></iframe>

# Literatur 📚
::: {#refs}
:::
