---
title: "Introduction"  
subtitle: "Why should you bother with technology and application management?"
lang: en-US

bibliography: ../assets/literature.bib

format: 
  html:
    output-file: index.html
  revealjs:
    date: "Winter Term 2022/23"
    output-file: slides.html 
    include-after-body: ../assets/footer.html
---

# Top{visibility="hidden" .slide-link-hidden .unlisted .unnumbered}

{{< include ../assets/_top.qmd >}}

# Motivation {.vertical-center background-color=blue background-image="../assets/bg.jpg"}

> IT is reshaping global markets while reshaping itself as it becomes the business. *@luftman2015influential*

## Baseline

**Digital transformation**[^1] is the mega trend of our time, bringing countless changes to  with it and as many new challenges as opportunities. 

. . .

Though, IT has dealt with constant change for years, one major difference to earlier developments stands out—**pace and scope of change**.

. . .

Many new technologies are, at once, rapidly developing and transforming business models, products & services, customer expectations, organizational structures—to name just a few important.

. . .

That poses not only novel challenges on the way business is done, but also on how (transformative) technologies and applications are managed—*agility*, *flexibility* and *efficiency* is called. 

. . .

**IT management needs to adapt to the digital age.**

[^1]: Digital transformation is here defined as transformation ‘concerned with the changes digital technologies can bring about in a company’s business model, … products or organizational structures’ [@hess2016options].

## IT management

IT management is is concerned with **selecting, implementing, and maintaining technologies and applications** as socio-technical resources that are aligned with business strategy.

. . .

#### Essential tasks to remain up to date with technological changes

:::{.incremental}
- Understand the **new technologies**, assess their potential applications, and master them if necessary [@urbach2018management]
- **Simplify IT architectures** to achieve flexibility and manage growing complexity [@grebe2013simplifying]
- **Manage an increasing number of risks**, particularly in terms of technology availability, security, and data protection [@urbach2018management]
- **Recruit, train and retain employees** that are capable to implement digital change
:::

## Reflect! {.html-hidden .unlisted .unnumbered .vertical-center background-color=blue background-image="../assets//bg.jpg"}

What principles should IT (or technology and application) management adhere to in order to truly enable and drive digital transformation? And why?

# Principles

Digital transformation requires IT departments that **play a proactive role** in the innovation process, that **accompany or even drive the necessary changes**, and thus embraces following principles [@urbach2018management]:

. . .

:::{.incremental}
- No business without IT
- Development and operations
- Shadow IT as a lived practice
- Innovations through networks
- Focusing on the user
- Infrastructure as commodity
- Transformable IT landscapes
- Digitalization as a risk 
- Employees are a competitive factor
:::

## No business without IT

**IT is the central and indispensable driver of entrepreneurial value creation** [@urbach2018management]

. . .

:::{.incremental}
- IT no longer supports only to business processes, but increasingly enables products and services
- Time to market becomes even more critical to succeed in conquering markets and securing competitive positions.
:::

. . .

#### Implications for IT management

:::{.incremental}
- Cycles for transforming technologies and applications into value-add IT solutions need to be shortened significantly 
- Business-IT alignment needs to evolve into a fusion of business and IT
:::

## Development and operations

**IT management follows the “innovate-design-transform” paradigm** [@urbach2018management]

. . .

:::{.incremental}
- Innovating value creation is an essential task of digital transformation
- Importance of development and operation of internal and hitherto core application systems is decreasing
- Fixed IT structures and relative static *plan-build-run* paradigms pay for efficiency, but are limited when it comes to driving innovation
:::

. . .

#### Implications for IT management

:::{.incremental}
- New management paradigms are necessary (e.g., intelligent demand management [@grebe2013simplifying], DevOps [@ketterer2017leaner])
- Innovation capability needs to be facilitated through greater agility and flexibility as well as a focus on customer-oriented and transformative solutions
:::

## Shadow IT

**IT innovations need to be developed in interdisciplinary teams within the business departments** [@urbach2018management]

. . .

:::{.incremental}
- Reactive implementations of business unit demands is rather slow and the results are often not innovative or disruptive
- Business units increasingly bypass corporate IT and use new sourcing options like cloud computing 
:::


#### Implications for IT management

:::{.incremental}
- The traditional separation of IT and business must be challenged
- IT innovations should ideally be created where they will be used later on, involving all relevant experts
- 'Official shadow IT' will become a lived practice, without putting compliance, security, and architectural requirements on risk
:::

## Innovation networks

**Turning strategic suppliers into innovation partners** [@urbach2018management]

:::{.incremental}
- Cloud computing eases sourcing of non-strategic parts of corporate IT 
- New technology requires know-how that is often only available from specialized technology providers
- Internal acquisition of corresponding knowledge and skills is risky and time-consuming
:::

. . .

#### Implications for IT management

:::{.incremental}
- Complex relationships with innovation partners need to be developed, nurtured and systematically managed
- IT innovation partnerships require a new approach that goes far beyond purchasing processes (i.e., partner management)
:::

## User focus

**Development processes are agile, end-user centered, and merged with the operation** [@urbach2018management]

:::{.incremental}
- Today, development activities focus strongly on technology, products, and functions; user needs and acceptance receive little attention
- To fulfill the requirements of the digital age, development processes need to move close to the customer and be iterative
:::

. . .

#### Implications for IT management

:::{.incremental}
- Particularly for "lightweight IT" (front-end dominated, customer-oriented), agile approaches are required
- The user must become much more of a focus of development activities
- Software development and operation need continue to merge (e.g., DevOps)
:::


## Infrastructure

**IT infrastructure services are traded on free markets and purchased as required** [@urbach2018management]

:::{.incremental}
- Traditional outsourcing models are increasingly challenged by *public* cloud computing
- IT infrastructure services can be procured via exchange-type markets and dynamically consumed
:::

. . .

#### Implications for IT management

:::{.incremental}
- Technology and application management needs to push towards standard infrastructure (technically and functionally)
- IT infrastructure needs to be decoupled from specific applications [@grebe2013simplifying]
:::

## Architectures

**IT architectures are standardized, modular, flexible, ubiquitous, elastic, cost-effective, and secure** [@urbach2018management]

:::{.incremental}
- Most companies deal with evolved IT infrastructure and application landscapes 
- Growing complexity, fading transparency and increased risks and costs challenge the business and block new strategies
- Digital transformation demand IT landscape that are much easier to transform
:::

. . .

#### Implications for IT management

:::{.incremental}
- Standardization, advanced architecture concepts (e.g., service-oriented architectures and virtualization), and enterprise architecture management (EAM) need to be pushed further, also for data and business processes [@grebe2013simplifying]
- While advancing architectures, cost efficiency and security must be ensured
:::

## Risk

**Security and business continuity management are central cross-divisional functions of the company** [@urbach2018management]

:::{.incremental}
- Dependency on IT systems (processes, products, services) *and*, likewise, vulnarability of these systems increases
- Many companies still underestimate IT risks and therefore often do not have them under control
:::

. . .

#### Implications for IT management

:::{.incremental}
- IT security and business continuity management must enter the main stage (e.g., organized as a central, cross-divisional function)
- Increased focus on developing security competences within corporate IT and beyond
:::

## People 

**Employees become a strategic competitive factor** [@urbach2018management]

:::{.incremental}
- Digital transformation requires specific qualifications and skills of IT staff
- Due to demographic change, the labor market has fewer and fewer well-trained staff at its disposal, particular STEM[^STEM] experts
- Acquiring, developing and retaining talent is thus a key factor for the success of the digital transformation
:::

. . .

#### Implications for IT management

:::{.incremental}
- Increased focus on corporate culture, workplace design, and management to create an attractive working environment
- Targeted choice of location, competence-enhancing acquisitions, and strategic cooperation must to get into focus
:::

[^STEM]: Science, technology, engineering, and mathematics

## Reflect! {.html-hidden .unlisted .unnumbered .vertical-center background-color=blue background-image="../assets//bg.jpg"}

Are these principles the end of the IT department as we know it?

## Corporate IT 

**IT departments, as we know them today, will not survive.**  
Corporate IT will primarily take on strategic coordination functions as part of the digital transformation, work more intensively with the business units and, thereby, mainly assume following duties and responsibilities [@urbach2018management]:

:::{.incremental}
- Enterprise architecture management
- Coordination of demand and innovation management
- Central portfolio management
- Strategic supplier and provider management
- External monitoring of service provision
- Risk, compliance and security management, as well as IT governance[^ITGov].
:::

. . .

**IT management approaches should prepare for this development even of today**

[^ITGov]: Selection and use of organizational process to make decisions about how to obtain and deploy IT resources and competencies [@venkatraman1993continuous], sets the decision rights and accountability for the use of IT [@weill2004governance].

Specifying the decision right and accountability framework to encourage desirable behavior in the use of IT

# Q&A {.html-hidden .unlisted .vertical-center background-color=blue background-image="../assets/bg.jpg"}

# Literature

:::{.refs}
:::