project:
  output-dir: _output
  type: website
  resources: lib

website:
  title: "Intro to Artificial Intelligence 🧠"
  page-navigation: true
  search: false
  theme: clean

  sidebar:
    - id: nav
      title: ToC
      style: docked
      collapse-level: 1
      align: left
      contents:
        - text: "Administrivia"
          file: administrivia.md

bibliography: bibliography/bibliography.bib

format:   
  html:
    toc: true
    code-copy: true
    code-overflow: wrap
    theme:
      - cosmo
      - theme/html.scss
  revealjs:
    theme: theme/slides.scss
    transition: slide
    menu: true
    disable-layout: true
    slide-number: c
    citations-hover: true
    include-after-body: assets/footer.html
    self-contained: false
    title-slide-attributes: 
      data-background-color: '#0333ff'     