---
title: "Übungsblatt (THE #2)"
subtitle: "`IMUK_1` Grundzüge Informationsmanagement (GIM)"
lang: de-DE

format: 
  html:
    output-file: index.html
---

# Aufgabenstellung 🧐 {visibility="hidden"}

Bearbeiten Sie __selbstständig__ (ohne Abstimmung in der Gruppe) folgende Aufgaben.

## Aufgabe 1 (4 Punkte)

Erstellen Sie das __Entity-Relationship Modell in der (min,max)-Notation__ für das im folgenden Text beschriebene Car-Sharing-Verwaltungssystem der Studierendenvertretungen der Uni Ulm, der THU und der HNU.

Es stehen mehrere Fahrzeuge zur Verfügung. Jedes Fahrzeug hat einen festen Standort (HNU Campus Wiley Straße, THU Campus Prittwitzstraße, THU Campus Albert-Einstein-Allee, etc.). Studierende können Fahrzeuge des Car-Sharing-Dienstes buchen. Mit jeder Buchung können bis zu 2 Fahrzeuge für max. einen Tag genutzt werden.

Jedes Fahrzeug kann über das Kennzeichen, jeder Studierende über die Matrikelnummer und jede Buchung über eine Buchungsnummer eindeutig identifiziert werden. Zum Fahrzeug werden, zusätzlich zum Kennzeichen, Hersteller, Typ und Erstzulassung dokumentiert. Zu den Studierenden Name, Vorname und Adresse. Der Standort hat die Attribute Bezeichnung und Adresse. Zur Buchung werden Datum der Buchung und Tag der Nutzung festgehalten.

Sie können dort und nur dort, wo es für ein formal korrektes ERM notwendig ist, Annahmen treffen.

## Aufgabe 2 (2 Punkte)

Leiten Sie die Relation __Buchung__ ab und stellen Sie diese in der in der Vorlesung vorgestellten tabellarischen Form dar. Ergänzen Sie zwei exemplarische Datensätze.

Zeigen Sie zudem anhand der tabellarischen Form, wie die Beziehung zwischen __Fahrzeug__ und __Buchung__ im Relationenmodell abgebildet ist. Ergänzen Sie zwei exemplarische Datensätze.

## Aufgabe 3 (4 Punkte)

Erstellen Sie ein __eEPK__ zu folgendem Prozess:

Eine neue Student:in registriert sich auf der App des Carsharing Dienst. Um Redundanzen zu vermeiden wird als nächstes anhand der Matrikelnummer geprüft, ob die Student:in bereits im Verwaltungssystem angelegt ist. Nur wenn noch kein Kundenstammdatensatz im Car-Sharing Verwaltungsssystem vorhanden ist, wird dieser in der Datenbank angelegt. Danach wird das Nutzerprofil in der App erstellt und die Matrikelnummer der Student:in vom Verwaltungssystem in das Nutzerprofil der App übertragen. Mit der Benachrichtigung über die erfolgreiche Anlage des Profils per Mail an die Student:in endet der Prozess.

# Abgabe

Legen Sie für jede Aufgabe eine DIN A4 Seite an. Ergänzen Sie im Kopfbereich aller drei Seiten folgende Informationen: „IMUK1 Grundzüge IM, Wintersemester 22/23, Prüfungsleistung THE-2“, Ihren vollständigen Namen, Ihre Matrikel-Nummer und die Bezeichnung der Aufgabe.
Wenn Sie handschriftlich gearbeitet haben, fotografieren Sie alle Seiten und erstellen ein PDF. Wenn Sie am PC gearbeitet haben, erstellen Sie direkt ein PDF. Das PDF mit den Lösungen zu allen Aufgaben laden Sie als Ergebnis in Moodle hoch. Abgabefrist siehe Hinweise im Moodle-Kurs.

Bei Abgabe der Prüfungsleistung versichern Sie, dass Sie die eingereichte Prüfungsleistung ohne fremde Hilfe verfasst haben. Ihnen ist bewusst, dass bereits der Versuch, das Ergebnis der Arbeit durch Täuschung (z.B. durch Mithilfe Dritter, auch Kommilitonen) zu beeinflussen, zur Bewertung 5,0 („nicht ausreichend“) bzw. „nicht bestanden“ führen kann“.